package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestRenderMessagesHeaderOnly(t *testing.T) {
	items := map[string]Item{}
	mf := MessageFile{Stream: 1, Messages: []Message{{
		Function: 1, Name: "Are You There Request", Mnemonic: "R",
		Direction: "bidirectional", Description: "Establishes if the equipment is on-line.",
		Exception: "None", Source: "e5",
		Bodies: []Body{{Actor: "both", ReplyExpected: true, Structure: nil}},
	}}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)
	require.Contains(t, src, "// Code generated by gemgen; DO NOT EDIT.")
	require.Contains(t, src, "package gem")
	require.Contains(t, src, "func S1F1() secs2.SECS2Message {")
	require.Contains(t, src, "return secs2.NewMessage(1, 1, true, secs2.NewEmptyItem())")
}

// TestRenderMessagesFixedListActorVariants proves the fixed-list body +
// per-actor variant path: S1F2 (equipment sends a two-item list) and
// S1F2Host (host sends an empty list) share the same stream/function but
// render as two distinct functions, with the host actor's function name
// carrying the "Host" suffix.
func TestRenderMessagesFixedListActorVariants(t *testing.T) {
	items := testItems()
	mf := MessageFile{Stream: 1, Messages: []Message{{
		Function: 2, Name: "On Line Data", Mnemonic: "D",
		Direction: "bidirectional", Description: "Data signifying that the equipment is alive.",
		Exception: "The host sends a zero-length list to the equipment.", Source: "e5",
		Bodies: []Body{
			{
				Actor: "equipment", ReplyExpected: false,
				Structure: &StructureNode{Type: "list", Items: []StructureNode{{Item: "MDLN"}, {Item: "SOFTREV"}}},
			},
			{
				Actor: "host", ReplyExpected: false,
				Structure: &StructureNode{Type: "list", Items: []StructureNode{}},
			},
		},
	}}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)

	require.Contains(t, src, "func S1F2(mdln string, softrev string) secs2.SECS2Message {\n\treturn secs2.NewMessage(1, 2, false, secs2.L(secs2.A(mdln), secs2.A(softrev)))\n}")
	require.Contains(t, src, "func S1F2Host() secs2.SECS2Message {\n\treturn secs2.NewMessage(1, 2, false, secs2.L())\n}")
}

// TestRenderMessagesBareLeaf proves the bare-fixed-leaf body path: a
// top-level leaf node (no secs2.L(...) wrapper) renders S1F5's body as
// secs2.B(sfcd) directly, not secs2.L(secs2.B(sfcd)).
func TestRenderMessagesBareLeaf(t *testing.T) {
	items := paramsItems()
	mf := MessageFile{Stream: 1, Messages: []Message{{
		Function: 5, Name: "Formatted Status Send", Mnemonic: "FSS",
		Direction: "equipment-to-host", Description: "Equipment reports its status format code.",
		Exception: "None", Source: "e5",
		Bodies: []Body{
			{Actor: "equipment", ReplyExpected: true, Structure: &StructureNode{Item: "SFCD"}},
		},
	}}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)

	require.Contains(t, src, "func S1F5(sfcd byte) secs2.SECS2Message {\n\treturn secs2.NewMessage(1, 5, true, secs2.B(sfcd))\n}")
	require.NotContains(t, src, "secs2.L(secs2.B(sfcd))")
}

// TestRenderMessagesOpenRepeat proves the open-binding repeat body path: a
// top-level list with Repeat set (and no Items) renders S1F3's signature as
// a caller-supplied variadic secs2.Item slice, with the body forwarding it
// unwrapped into secs2.L(svids...).
func TestRenderMessagesOpenRepeat(t *testing.T) {
	items := paramsItems()
	mf := MessageFile{Stream: 1, Messages: []Message{{
		Function: 3, Name: "Selected Equipment Status Request", Mnemonic: "SSR",
		Direction: "host-to-equipment", Description: "Host requests the values of specified status variables.",
		Exception: "None", Source: "e5",
		Bodies: []Body{
			{
				Actor: "both", ReplyExpected: true,
				Structure: &StructureNode{Type: "list", Repeat: "svids", Of: &StructureNode{Item: "SVID"}},
			},
		},
	}}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)

	require.Contains(t, src, "func S1F3(svids ...secs2.Item) secs2.SECS2Message {\n\treturn secs2.NewMessage(1, 3, true, secs2.L(svids...))\n}")
}

// TestRenderMessagesNestedListEnumLeaf proves the nested-list + enum-leaf
// body path: S1F14's body is a top-level list whose first child is a fixed
// enum leaf (COMMACK) and whose second child is itself a nested list
// (MDLN/SOFTREV). The generated parameter for the enum leaf must be the
// named type COMMACK (not the bare byte), and the body must convert it back
// to byte at the secs2.B(...) call site, per Task 6's BuildParams/BodyExpr.
// S1F14Host proves the per-actor variant: only mdln/softrev drop for the
// host variant, since COMMACK is shared across both actors.
func TestRenderMessagesNestedListEnumLeaf(t *testing.T) {
	items := paramsItems()
	mf := MessageFile{Stream: 1, Messages: []Message{{
		Function: 14, Name: "Establish Communications Request Acknowledge", Mnemonic: "CRA",
		Direction: "bidirectional", Description: "Reply to Establish Communications Request.",
		Exception: "None", Source: "e5",
		Bodies: []Body{
			{
				Actor: "equipment", ReplyExpected: false,
				Structure: &StructureNode{Type: "list", Items: []StructureNode{
					{Item: "COMMACK"},
					{Type: "list", Items: []StructureNode{{Item: "MDLN"}, {Item: "SOFTREV"}}},
				}},
			},
			{
				Actor: "host", ReplyExpected: false,
				Structure: &StructureNode{Type: "list", Items: []StructureNode{
					{Item: "COMMACK"},
					{Type: "list", Items: []StructureNode{}},
				}},
			},
		},
	}}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)

	require.Contains(t, src, "func S1F14(commack COMMACK, mdln string, softrev string) secs2.SECS2Message {\n"+
		"\treturn secs2.NewMessage(1, 14, false, secs2.L(secs2.B(byte(commack)), secs2.L(secs2.A(mdln), secs2.A(softrev))))\n}")
	require.Contains(t, src, "func S1F14Host(commack COMMACK) secs2.SECS2Message {\n"+
		"\treturn secs2.NewMessage(1, 14, false, secs2.L(secs2.B(byte(commack)), secs2.L()))\n}")
}

// TestRenderMessagesOpaqueBody proves the opaque body path: a top-level node
// with Type "opaque" (its shape depends on the status form and cannot be
// statically specified) renders S1F6's signature as a single caller-supplied
// secs2.Item, with the body forwarding it unwrapped (no secs2.L(...)).
func TestRenderMessagesOpaqueBody(t *testing.T) {
	items := map[string]Item{}
	mf := MessageFile{Stream: 1, Messages: []Message{{
		Function: 6, Name: "Multi-block Data Send", Mnemonic: "MBS",
		Direction: "equipment-to-host", Description: "Equipment sends multi-block status data.",
		Exception: "None", Source: "e5",
		Bodies: []Body{
			{Actor: "equipment", ReplyExpected: false, Structure: &StructureNode{Type: "opaque"}},
		},
	}}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)

	require.Contains(t, src, "func S1F6(body secs2.Item) secs2.SECS2Message {\n\treturn secs2.NewMessage(1, 6, false, body)\n}")
	require.NotContains(t, src, "secs2.L(body)")
}

// TestRenderMessagesFixedLeafSiblingRepeats proves E5's hardest S1 shape:
// a fixed leaf followed by two independent sibling repeat groups at the same
// list level (S1F19: L[3]{ <OBJTYPE> L{<OBJID>...} L{<ATTRID>...} }). Only the
// final repeat (attrids) is variadic; the non-final repeat (objids) renders as
// a []secs2.Item slice, and the leaf renders ahead of both. The body wraps each
// repeat in its own secs2.L(...) and forwards the leaf unwrapped, per Task 6's
// Repeat/Variadic split and Task 7's three-way params helper.
func TestRenderMessagesFixedLeafSiblingRepeats(t *testing.T) {
	items := paramsItems()
	mf := MessageFile{Stream: 1, Messages: []Message{{
		Function: 19, Name: "Get Attribute", Mnemonic: "GA",
		Direction: "host-to-equipment", Description: "Host requests attributes of an object.",
		Exception: "None", Source: "e5",
		Bodies: []Body{
			{
				Actor: "both", ReplyExpected: true,
				Structure: &StructureNode{Type: "list", Items: []StructureNode{
					{Item: "OBJTYPE"},
					{Type: "list", Repeat: "objids", Of: &StructureNode{Item: "OBJID"}},
					{Type: "list", Repeat: "attrids", Of: &StructureNode{Item: "ATTRID"}},
				}},
			},
		},
	}}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)

	require.Contains(t, src, "func S1F19(objtype secs2.Item, objids []secs2.Item, attrids ...secs2.Item) secs2.SECS2Message {\n"+
		"\treturn secs2.NewMessage(1, 19, true, secs2.L(objtype, secs2.L(objids...), secs2.L(attrids...)))\n}")
}

// TestRenderMessagesSiblingRepeatsOfLists proves two sibling repeat groups
// where each repeat element is itself a multi-item list (S1F20:
// L[2]{ L{objects...} L{errors...} }). Each repeat still contributes a single
// caller-supplied secs2.Item parameter (the walker never recurses into a
// repeat's Of), so the nested-list element shape does not leak into the
// signature. The non-final repeat (objects) is a []secs2.Item slice; only the
// final repeat (errors) is variadic.
func TestRenderMessagesSiblingRepeatsOfLists(t *testing.T) {
	items := paramsItems()
	mf := MessageFile{Stream: 1, Messages: []Message{{
		Function: 20, Name: "Attribute Data", Mnemonic: "AD",
		Direction: "equipment-to-host", Description: "Equipment returns object attribute data.",
		Exception: "None", Source: "e5",
		Bodies: []Body{
			{
				Actor: "both", ReplyExpected: false,
				Structure: &StructureNode{Type: "list", Items: []StructureNode{
					{Type: "list", Repeat: "objects", Of: &StructureNode{Type: "list", Items: []StructureNode{{Item: "OBJTYPE"}}}},
					{Type: "list", Repeat: "errors", Of: &StructureNode{Type: "list", Items: []StructureNode{{Item: "OBJID"}}}},
				}},
			},
		},
	}}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)

	require.Contains(t, src, "func S1F20(objects []secs2.Item, errors ...secs2.Item) secs2.SECS2Message {\n"+
		"\treturn secs2.NewMessage(1, 20, false, secs2.L(secs2.L(objects...), secs2.L(errors...)))\n}")
}

// TestRenderMessagesNestedRepeatOfList proves a top-level repeat whose every
// element is a multi-item list (S1F22: L[n]{ L[3]{<VID> A A} ... } and
// S1F24: L[n]{ L[3]{<CEID> A L{<VID>...}} ... }). Because the walker stops at
// the repeat and never descends into Of, the inner list arity is irrelevant to
// the signature: each renders as a single final variadic secs2.Item, with the
// body forwarding it unwrapped into secs2.L(...). This mirrors the open-repeat
// S1F3 shape at the render level regardless of how deep each element nests.
func TestRenderMessagesNestedRepeatOfList(t *testing.T) {
	items := paramsItems()
	mf := MessageFile{Stream: 1, Messages: []Message{
		{
			Function: 22, Name: "Data Variable Namelist Reply", Mnemonic: "DVNR",
			Direction: "equipment-to-host", Description: "Equipment reports the data variable namelist.",
			Exception: "None", Source: "e5",
			Bodies: []Body{
				{
					Actor: "both", ReplyExpected: false,
					Structure: &StructureNode{Type: "list", Repeat: "vids", Of: &StructureNode{Type: "list", Items: []StructureNode{
						{Item: "VID"}, {Item: "DVVALNAME"}, {Item: "UNITS"},
					}}},
				},
			},
		},
		{
			Function: 24, Name: "Collection Event Namelist Reply", Mnemonic: "CENR",
			Direction: "equipment-to-host", Description: "Equipment reports the collection event namelist.",
			Exception: "None", Source: "e5",
			Bodies: []Body{
				{
					Actor: "both", ReplyExpected: false,
					Structure: &StructureNode{Type: "list", Repeat: "ceids", Of: &StructureNode{Type: "list", Items: []StructureNode{
						{Item: "CEID"}, {Item: "CENAME"}, {Type: "list", Repeat: "vids", Of: &StructureNode{Item: "VID"}},
					}}},
				},
			},
		},
	}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)

	require.Contains(t, src, "func S1F22(vids ...secs2.Item) secs2.SECS2Message {\n"+
		"\treturn secs2.NewMessage(1, 22, false, secs2.L(vids...))\n}")
	require.Contains(t, src, "func S1F24(ceids ...secs2.Item) secs2.SECS2Message {\n"+
		"\treturn secs2.NewMessage(1, 24, false, secs2.L(ceids...))\n}")
}

// TestRenderMessagesPackedGroups proves E5's packed multi-value single item
// (S1F10): two sibling packed groups over the fixed byte items TSIP/TSOP render
// as concrete-typed params (tsips []byte, tsops ...byte -- NOT []secs2.Item /
// ...secs2.Item), and each group's body expression calls the item's own
// constructor directly (secs2.B(tsips)), never wrapped in secs2.L(...).
func TestRenderMessagesPackedGroups(t *testing.T) {
	items := paramsItems()
	mf := MessageFile{Stream: 1, Messages: []Message{{
		Function: 10, Name: "Port Transfer Status Data", Mnemonic: "PTSD",
		Direction: "equipment-to-host", Description: "Equipment reports port transfer status.",
		Exception: "None", Source: "e5",
		Bodies: []Body{{
			Actor: "both", ReplyExpected: false,
			Structure: &StructureNode{Type: "list", Items: []StructureNode{
				{Type: "list", Packed: "tsips", Of: &StructureNode{Item: "TSIP"}},
				{Type: "list", Packed: "tsops", Of: &StructureNode{Item: "TSOP"}},
			}},
		}},
	}}}
	out, err := renderMessages(mf, items)
	require.NoError(t, err)
	src := string(out)

	require.Contains(t, src, "func S1F10(tsips []byte, tsops ...byte) secs2.SECS2Message {\n"+
		"\treturn secs2.NewMessage(1, 10, false, secs2.L(secs2.B(tsips), secs2.B(tsops)))\n}")
}

// TestMessageDoc covers the messageDoc godoc-line helper directly: a
// source: external message must carry the trailing disclaimer paragraph
// (preceded by its own blank line), and a non-external message must not.
func TestMessageDoc(t *testing.T) {
	items := map[string]Item{}
	body := Body{Actor: "both", ReplyExpected: false, Structure: nil}

	t.Run("external source appends disclaimer", func(t *testing.T) {
		m := Message{
			Function: 12, Name: "Status Variable Namelist Reply", Mnemonic: "SVNR",
			Direction: "equipment-to-host", Description: "Equipment reports the namelist.",
			Exception: "None", Source: "external",
		}
		doc := messageDoc("S1F12", "S1F12", m, body, items)

		require.Contains(t, doc, externalSourceDisclaimer)

		idx := indexOf(doc, externalSourceDisclaimer)
		require.Greater(t, idx, 0, "disclaimer must not be the first line")
		require.Equal(t, "", doc[idx-1], "a blank line must precede the disclaimer paragraph")

		// Body: and Exception: paragraphs are still separated by a genuine
		// blank line even when the disclaimer is appended afterward.
		bodyIdx := indexOfPrefix(doc, "Body:")
		excIdx := indexOfPrefix(doc, "Exception:")
		require.Equal(t, "", doc[bodyIdx+1])
		require.Equal(t, excIdx, bodyIdx+2)
	})

	t.Run("non-external source has no disclaimer", func(t *testing.T) {
		m := Message{
			Function: 1, Name: "Are You There Request", Mnemonic: "R",
			Direction: "bidirectional", Description: "Establishes if the equipment is on-line.",
			Exception: "None", Source: "e5",
		}
		doc := messageDoc("S1F1", "S1F1", m, body, items)

		for _, line := range doc {
			require.NotContains(t, line, "reconstructed from an external reference")
		}
	})
}

func indexOf(lines []string, s string) int {
	for i, l := range lines {
		if l == s {
			return i
		}
	}

	return -1
}

func indexOfPrefix(lines []string, prefix string) int {
	for i, l := range lines {
		if strings.HasPrefix(l, prefix) {
			return i
		}
	}

	return -1
}
