package gem

// Files with a YAML source under tools/gemgen/data are generated by the
// tools/gemgen generator: today that's items.go and s1.go/s1_test.go,
// s2.go/s2_test.go, s5.go/s5_test.go, s6.go/s6_test.go, and
// s9.go/s9_test.go, driven by data/items.yaml and data/messages/s1.yaml,
// s2.yaml, s5.yaml, s6.yaml, s9.yaml. Other stream files in this package
// have no corresponding YAML source yet and remain hand-written until a
// messages/sN.yaml is added for them. Run `go generate ./...` from the
// repo root (or `go generate .` from this directory) to regenerate the
// files that do have a YAML source.
//
// The `-C ../tools/gemgen` flag performs a real process chdir into
// tools/gemgen before `go run` builds and executes the gemgen binary, so the
// binary's own relative flag values (-items, -messages, -out) resolve
// relative to tools/gemgen, not to this package's directory. This was
// verified empirically: running the directive lands items.go/s1.go/s1_test.go
// in gem/ with no stray gem/data/ tree, confirming -C sets the child
// process's working directory as expected on this toolchain (go1.26.1).
//
//go:generate go run -C ../tools/gemgen . -items data/items.yaml -messages data/messages -out ../../gem
