package gem

// Files with a YAML source under tools/gemgen/data are generated by the
// tools/gemgen generator: today that's items.go, decode.go, and the four
// files each covered stream contributes — sN.go, sN_test.go, sN_decode.go,
// and sN_decode_test.go — for streams 1, 2, 5, 6, and 9, driven by
// data/items.yaml and data/messages/s1.yaml, s2.yaml, s5.yaml, s6.yaml,
// s9.yaml. decode.go holds the shared helpers every generated decoder
// calls; it carries no per-message data but is written by the generator so
// the decoders and the helpers they need never drift apart.
// Other stream files in this package have no corresponding YAML source yet
// and remain hand-written until a messages/sN.yaml is added for them.
// Run `go generate ./...` from the repo root (or `go generate .` from this
// directory) to regenerate the files that do have a YAML source.
//
// The `-C ../tools/gemgen` flag performs a real process chdir into
// tools/gemgen before `go run` builds and executes the gemgen binary, so the
// binary's own relative flag values (-items, -messages, -out) resolve
// relative to tools/gemgen, not to this package's directory. This was
// verified empirically: running the directive lands items.go/s1.go/s1_test.go
// in gem/ with no stray gem/data/ tree, confirming -C sets the child
// process's working directory as expected on this toolchain (go1.26.1).
//
//go:generate go run -C ../tools/gemgen . -items data/items.yaml -messages data/messages -out ../../gem
