// Code generated by gemgen; DO NOT EDIT.

package gem

// COMMACK enumerates the defined values of the COMMACK item.
type COMMACK byte

const (
	COMMACKAccepted COMMACK = 0
	COMMACKDenied   COMMACK = 1
)
