// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S1F1 creates the S1F1 (Are You There Request) message, direction: bidirectional.
//
// Establishes if the equipment is on-line.
//
// Body: Header only.
//
// Exception: None.
func S1F1() secs2.SECS2Message {
	return secs2.NewMessage(1, 1, true, secs2.NewEmptyItem())
}

// S1F2 creates the S1F2 (On Line Data) message for equipment, direction: bidirectional.
//
// Data signifying that the equipment is alive.
//
// Body: L[2]{ A[mdln] A[softrev] }.
//
// Exception: The host sends a zero-length list to the equipment.
func S1F2(mdln string, softrev string) secs2.SECS2Message {
	return secs2.NewMessage(1, 2, false, secs2.L(secs2.A(mdln), secs2.A(softrev)))
}

// S1F2Host creates the S1F2 (On Line Data) message for host, direction: bidirectional.
//
// Data signifying that the equipment is alive.
//
// Body: L[0]{  }.
//
// Exception: The host sends a zero-length list to the equipment.
func S1F2Host() secs2.SECS2Message {
	return secs2.NewMessage(1, 2, false, secs2.L())
}

// S1F3 creates the S1F3 (Selected Equipment Status Request) message, direction: host-to-equipment.
//
// A request to the equipment to report selected values of its status.
//
// Body: L[n]{ <svids>... }.
//
// Exception: A zero-length list means report all SVIDs.
func S1F3(svids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 3, true, secs2.L(svids...))
}

// S1F4 creates the S1F4 (Selected Equipment Status Data) message, direction: equipment-to-host.
//
// The equipment reports the value of each SVID requested, in the order requested.
//
// Body: L[n]{ <svs>... }.
//
// Exception: A zero-length list item for an SV means the corresponding SVID does not exist.
func S1F4(svs ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 4, false, secs2.L(svs...))
}

// S1F5 creates the S1F5 (Formatted Status Request) message, direction: host-to-equipment.
//
// A request for the equipment to report status according to a predefined fixed format.
//
// Body: B[sfcd].
//
// Exception: None.
func S1F5(sfcd byte) secs2.SECS2Message {
	return secs2.NewMessage(1, 5, true, secs2.B(sfcd))
}

// S1F6 creates the S1F6 (Formatted Status Data) message, direction: equipment-to-host.
//
// The equipment reports the value of status variables according to the SFCD.
//
// Body: form-dependent (see description).
//
// Exception: A zero-length item means that no report can be made.
func S1F6(body secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 6, false, body)
}

// S1F7 creates the S1F7 (Fixed Form Request) message, direction: host-to-equipment.
//
// A request for the form used in S1F6.
//
// Body: B[sfcd].
//
// Exception: None.
func S1F7(sfcd byte) secs2.SECS2Message {
	return secs2.NewMessage(1, 7, true, secs2.B(sfcd))
}

// S1F8 creates the S1F8 (Fixed Form Data) message, direction: equipment-to-host.
//
// The equipment returns the fixed form specified for S1F6.
//
// Body: form-dependent (see description).
//
// Exception: A zero-length item means the form is unavailable.
func S1F8(body secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 8, false, body)
}

// S1F9 creates the S1F9 (Material Transfer Status Request) message, direction: host-to-equipment.
//
// A request to report the status of all material ports to the host.
//
// Body: Header only.
//
// Exception: None.
func S1F9() secs2.SECS2Message {
	return secs2.NewMessage(1, 9, true, secs2.NewEmptyItem())
}

// S1F10 creates the S1F10 (Material Transfer Status Data) message, direction: equipment-to-host.
//
// The equipment reports the transfer status of all material ports.
//
// Body: L[2]{ B[n]{ <tsips>... } B[n]{ <tsops>... } }.
//
// Exception: A zero-length input or output port list means there are no such ports.
func S1F10(tsips []byte, tsops ...byte) secs2.SECS2Message {
	return secs2.NewMessage(1, 10, false, secs2.L(secs2.B(tsips), secs2.B(tsops)))
}

// S1F11 creates the S1F11 (Status Variable Namelist Request) message, direction: host-to-equipment.
//
// A request to the equipment to identify certain status variables.
//
// Body: L[n]{ <svids>... }.
//
// Exception: A zero-length list means report all SVIDs.
func S1F11(svids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 11, true, secs2.L(svids...))
}

// S1F12 creates the S1F12 (Status Variable Namelist Reply) message, direction: equipment-to-host.
//
// The equipment reports the name and units for each status variable requested in S1F11.
//
// Body: L[n]{ <svids>... }.
//
// Exception: Zero-length SVNAME and UNITS items indicate that the SVID does not exist.
//
// Source: reconstructed from an external reference, not verified against the purchased SEMI standard.
func S1F12(svids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 12, false, secs2.L(svids...))
}

// S1F13 creates the S1F13 (Establish Communications Request) message for equipment, direction: bidirectional.
//
// Provides a formal means of initializing communications at the application level.
//
// Body: L[2]{ A[mdln] A[softrev] }.
//
// Exception: The host sends a zero-length list to the equipment.
func S1F13(mdln string, softrev string) secs2.SECS2Message {
	return secs2.NewMessage(1, 13, true, secs2.L(secs2.A(mdln), secs2.A(softrev)))
}

// S1F13Host creates the S1F13 (Establish Communications Request) message for host, direction: bidirectional.
//
// Provides a formal means of initializing communications at the application level.
//
// Body: L[0]{  }.
//
// Exception: The host sends a zero-length list to the equipment.
func S1F13Host() secs2.SECS2Message {
	return secs2.NewMessage(1, 13, true, secs2.L())
}

// S1F14 creates the S1F14 (Establish Communications Request Acknowledge) message for equipment, direction: bidirectional.
//
// Accepts or denies an Establish Communications Request. MDLN and SOFTREV are valid only if COMMACK is 0.
//
// Body: L[2]{ B[commack] L[2]{ A[mdln] A[softrev] } }.
//
// Exception: The host sends a zero-length list for the second item to the equipment.
func S1F14(commack COMMACK, mdln string, softrev string) secs2.SECS2Message {
	return secs2.NewMessage(1, 14, false, secs2.L(secs2.B(byte(commack)), secs2.L(secs2.A(mdln), secs2.A(softrev))))
}

// S1F14Host creates the S1F14 (Establish Communications Request Acknowledge) message for host, direction: bidirectional.
//
// Accepts or denies an Establish Communications Request. MDLN and SOFTREV are valid only if COMMACK is 0.
//
// Body: L[2]{ B[commack] L[0]{  } }.
//
// Exception: The host sends a zero-length list for the second item to the equipment.
func S1F14Host(commack COMMACK) secs2.SECS2Message {
	return secs2.NewMessage(1, 14, false, secs2.L(secs2.B(byte(commack)), secs2.L()))
}

// S1F15 creates the S1F15 (Request OFF-LINE) message, direction: host-to-equipment.
//
// The host requests that the equipment transition to the OFF-LINE state.
//
// Body: Header only.
//
// Exception: None.
func S1F15() secs2.SECS2Message {
	return secs2.NewMessage(1, 15, true, secs2.NewEmptyItem())
}

// S1F16 creates the S1F16 (OFF-LINE Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error for the OFF-LINE request.
//
// Body: B[oflack].
//
// Exception: None.
func S1F16(oflack byte) secs2.SECS2Message {
	return secs2.NewMessage(1, 16, false, secs2.B(oflack))
}

// S1F17 creates the S1F17 (Request ON-LINE) message, direction: host-to-equipment.
//
// The host requests that the equipment transition to the ON-LINE state.
//
// Body: Header only.
//
// Exception: None.
func S1F17() secs2.SECS2Message {
	return secs2.NewMessage(1, 17, true, secs2.NewEmptyItem())
}

// S1F18 creates the S1F18 (ON-LINE Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error for the ON-LINE request.
//
// Body: B[onlack].
//
// Exception: None.
func S1F18(onlack byte) secs2.SECS2Message {
	return secs2.NewMessage(1, 18, false, secs2.B(onlack))
}

// S1F19 creates the S1F19 (Get Attribute) message, direction: bidirectional.
//
// Request for attribute data relating to the specified object or entity within the equipment.
//
// Body: L[3]{ <objtype> L[n]{ <objids>... } L[n]{ <attrids>... } }.
//
// Exception: A zero-length object list (m = 0) requests all objects of the type. A zero-length attribute list (n = 0) requests all attributes.
func S1F19(objtype secs2.Item, objids []secs2.Item, attrids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 19, true, secs2.L(objtype, secs2.L(objids...), secs2.L(attrids...)))
}

// S1F20 creates the S1F20 (Attribute Data) message, direction: bidirectional.
//
// Transfers the requested set of object attributes, in request order.
//
// Body: L[2]{ L[n]{ <objects>... } L[n]{ <errors>... } }.
//
// Exception: m = 0 means the OBJTYPE is unknown. n = 0 means the object was not found. A zero-length ATTRDATA means the attribute does not exist. p = 0 means no errors.
func S1F20(objects []secs2.Item, errors ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 20, false, secs2.L(secs2.L(objects...), secs2.L(errors...)))
}

// S1F21 creates the S1F21 (Data Variable Namelist Request) message, direction: host-to-equipment.
//
// Allows the host to request basic information about the data variables available in the equipment.
//
// Body: L[n]{ <vids>... }.
//
// Exception: A zero-length list means send information for all data variables.
func S1F21(vids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 21, true, secs2.L(vids...))
}

// S1F22 creates the S1F22 (Data Variable Namelist) message, direction: equipment-to-host.
//
// The equipment reports the information for the VIDs requested in S1F21.
//
// Body: L[n]{ <vids>... }.
//
// Exception: Zero-length DVVALNAME and UNITS items indicate that the VID does not exist or is not a DVVAL-class variable.
func S1F22(vids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 22, false, secs2.L(vids...))
}

// S1F23 creates the S1F23 (Collection Event Namelist Request) message, direction: host-to-equipment.
//
// Allows the host to retrieve which collection event IDs are available and which DVVALs are valid for each.
//
// Body: L[n]{ <ceids>... }.
//
// Exception: A zero-length list means send information for all CEIDs.
func S1F23(ceids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 23, true, secs2.L(ceids...))
}

// S1F24 creates the S1F24 (Collection Event Namelist) message, direction: equipment-to-host.
//
// The equipment reports the collection events and associated VIDs for the CEIDs requested in S1F23.
//
// Body: L[n]{ <ceids>... }.
//
// Exception: Zero-length CENAME and associated-VID list indicate that the CEID does not exist.
func S1F24(ceids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(1, 24, false, secs2.L(ceids...))
}
