// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

func TestDecodeS1F2RoundTrip(t *testing.T) {
	msg := gem.S1F2("mdln", "softrev")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F2(body)
	if err != nil {
		t.Fatalf("DecodeS1F2: %v", err)
	}

	if got.MDLN != "mdln" {
		t.Errorf("MDLN: got %v, want %v", got.MDLN, "mdln")
	}

	if got.SOFTREV != "softrev" {
		t.Errorf("SOFTREV: got %v, want %v", got.SOFTREV, "softrev")
	}
}

func TestDecodeS1F2HostRoundTrip(t *testing.T) {
	msg := gem.S1F2Host()

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	if _, err := gem.DecodeS1F2Host(body); err != nil {
		t.Fatalf("DecodeS1F2Host: %v", err)
	}
}

func TestDecodeS1F3RoundTrip(t *testing.T) {
	msg := gem.S1F3(secs2.A("svids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F3(body)
	if err != nil {
		t.Fatalf("DecodeS1F3: %v", err)
	}

	if len(got.SVIDS) != 1 {
		t.Fatalf("SVIDS: got %d elements, want 1", len(got.SVIDS))
	}

	if !bytes.Equal(got.SVIDS[0].ToBytes(), secs2.A("svids").ToBytes()) {
		t.Errorf("SVIDS: got %x, want %x", got.SVIDS[0].ToBytes(), secs2.A("svids").ToBytes())
	}
}

func TestDecodeS1F4RoundTrip(t *testing.T) {
	msg := gem.S1F4(secs2.A("svs"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F4(body)
	if err != nil {
		t.Fatalf("DecodeS1F4: %v", err)
	}

	if len(got.SVS) != 1 {
		t.Fatalf("SVS: got %d elements, want 1", len(got.SVS))
	}

	if !bytes.Equal(got.SVS[0].ToBytes(), secs2.A("svs").ToBytes()) {
		t.Errorf("SVS: got %x, want %x", got.SVS[0].ToBytes(), secs2.A("svs").ToBytes())
	}
}

func TestDecodeS1F5RoundTrip(t *testing.T) {
	msg := gem.S1F5(0xd7)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F5(body)
	if err != nil {
		t.Fatalf("DecodeS1F5: %v", err)
	}

	if got.SFCD != 0xd7 {
		t.Errorf("SFCD: got %v, want %v", got.SFCD, 0xd7)
	}
}

func TestDecodeS1F6RoundTrip(t *testing.T) {
	msg := gem.S1F6(secs2.A("body"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F6(body)
	if err != nil {
		t.Fatalf("DecodeS1F6: %v", err)
	}

	if !bytes.Equal(got.BODY.ToBytes(), secs2.A("body").ToBytes()) {
		t.Errorf("BODY: got %x, want %x", got.BODY.ToBytes(), secs2.A("body").ToBytes())
	}
}

func TestDecodeS1F7RoundTrip(t *testing.T) {
	msg := gem.S1F7(0xd7)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F7(body)
	if err != nil {
		t.Fatalf("DecodeS1F7: %v", err)
	}

	if got.SFCD != 0xd7 {
		t.Errorf("SFCD: got %v, want %v", got.SFCD, 0xd7)
	}
}

func TestDecodeS1F8RoundTrip(t *testing.T) {
	msg := gem.S1F8(secs2.A("body"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F8(body)
	if err != nil {
		t.Fatalf("DecodeS1F8: %v", err)
	}

	if !bytes.Equal(got.BODY.ToBytes(), secs2.A("body").ToBytes()) {
		t.Errorf("BODY: got %x, want %x", got.BODY.ToBytes(), secs2.A("body").ToBytes())
	}
}

func TestDecodeS1F10RoundTrip(t *testing.T) {
	msg := gem.S1F10([]byte{0x39}, 0xe3)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F10(body)
	if err != nil {
		t.Fatalf("DecodeS1F10: %v", err)
	}

	if !bytes.Equal(got.TSIPS, []byte{0x39}) {
		t.Errorf("TSIPS: got %x, want %x", got.TSIPS, []byte{0x39})
	}

	if !bytes.Equal(got.TSOPS, []byte{0xe3}) {
		t.Errorf("TSOPS: got %x, want %x", got.TSOPS, []byte{0xe3})
	}
}

func TestDecodeS1F11RoundTrip(t *testing.T) {
	msg := gem.S1F11(secs2.A("svids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F11(body)
	if err != nil {
		t.Fatalf("DecodeS1F11: %v", err)
	}

	if len(got.SVIDS) != 1 {
		t.Fatalf("SVIDS: got %d elements, want 1", len(got.SVIDS))
	}

	if !bytes.Equal(got.SVIDS[0].ToBytes(), secs2.A("svids").ToBytes()) {
		t.Errorf("SVIDS: got %x, want %x", got.SVIDS[0].ToBytes(), secs2.A("svids").ToBytes())
	}
}

func TestDecodeS1F12RoundTrip(t *testing.T) {
	msg := gem.S1F12(secs2.A("svids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F12(body)
	if err != nil {
		t.Fatalf("DecodeS1F12: %v", err)
	}

	if len(got.SVIDS) != 1 {
		t.Fatalf("SVIDS: got %d elements, want 1", len(got.SVIDS))
	}

	if !bytes.Equal(got.SVIDS[0].ToBytes(), secs2.A("svids").ToBytes()) {
		t.Errorf("SVIDS: got %x, want %x", got.SVIDS[0].ToBytes(), secs2.A("svids").ToBytes())
	}
}

func TestDecodeS1F13RoundTrip(t *testing.T) {
	msg := gem.S1F13("mdln", "softrev")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F13(body)
	if err != nil {
		t.Fatalf("DecodeS1F13: %v", err)
	}

	if got.MDLN != "mdln" {
		t.Errorf("MDLN: got %v, want %v", got.MDLN, "mdln")
	}

	if got.SOFTREV != "softrev" {
		t.Errorf("SOFTREV: got %v, want %v", got.SOFTREV, "softrev")
	}
}

func TestDecodeS1F13HostRoundTrip(t *testing.T) {
	msg := gem.S1F13Host()

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	if _, err := gem.DecodeS1F13Host(body); err != nil {
		t.Fatalf("DecodeS1F13Host: %v", err)
	}
}

func TestDecodeS1F14RoundTrip(t *testing.T) {
	msg := gem.S1F14(0xb5, "mdln", "softrev")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F14(body)
	if err != nil {
		t.Fatalf("DecodeS1F14: %v", err)
	}

	if got.COMMACK != 0xb5 {
		t.Errorf("COMMACK: got %v, want %v", got.COMMACK, 0xb5)
	}

	if got.MDLN != "mdln" {
		t.Errorf("MDLN: got %v, want %v", got.MDLN, "mdln")
	}

	if got.SOFTREV != "softrev" {
		t.Errorf("SOFTREV: got %v, want %v", got.SOFTREV, "softrev")
	}
}

func TestDecodeS1F14HostRoundTrip(t *testing.T) {
	msg := gem.S1F14Host(0xb5)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F14Host(body)
	if err != nil {
		t.Fatalf("DecodeS1F14Host: %v", err)
	}

	if got.COMMACK != 0xb5 {
		t.Errorf("COMMACK: got %v, want %v", got.COMMACK, 0xb5)
	}
}

func TestDecodeS1F16RoundTrip(t *testing.T) {
	msg := gem.S1F16(0x0a)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F16(body)
	if err != nil {
		t.Fatalf("DecodeS1F16: %v", err)
	}

	if got.OFLACK != 0x0a {
		t.Errorf("OFLACK: got %v, want %v", got.OFLACK, 0x0a)
	}
}

func TestDecodeS1F18RoundTrip(t *testing.T) {
	msg := gem.S1F18(0xc9)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F18(body)
	if err != nil {
		t.Fatalf("DecodeS1F18: %v", err)
	}

	if got.ONLACK != 0xc9 {
		t.Errorf("ONLACK: got %v, want %v", got.ONLACK, 0xc9)
	}
}

func TestDecodeS1F19RoundTrip(t *testing.T) {
	msg := gem.S1F19(secs2.A("objtype"), []secs2.Item{secs2.A("objids")}, secs2.A("attrids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F19(body)
	if err != nil {
		t.Fatalf("DecodeS1F19: %v", err)
	}

	if !bytes.Equal(got.OBJTYPE.ToBytes(), secs2.A("objtype").ToBytes()) {
		t.Errorf("OBJTYPE: got %x, want %x", got.OBJTYPE.ToBytes(), secs2.A("objtype").ToBytes())
	}

	if len(got.OBJIDS) != 1 {
		t.Fatalf("OBJIDS: got %d elements, want 1", len(got.OBJIDS))
	}

	if !bytes.Equal(got.OBJIDS[0].ToBytes(), secs2.A("objids").ToBytes()) {
		t.Errorf("OBJIDS: got %x, want %x", got.OBJIDS[0].ToBytes(), secs2.A("objids").ToBytes())
	}

	if len(got.ATTRIDS) != 1 {
		t.Fatalf("ATTRIDS: got %d elements, want 1", len(got.ATTRIDS))
	}

	if !bytes.Equal(got.ATTRIDS[0].ToBytes(), secs2.A("attrids").ToBytes()) {
		t.Errorf("ATTRIDS: got %x, want %x", got.ATTRIDS[0].ToBytes(), secs2.A("attrids").ToBytes())
	}
}

func TestDecodeS1F20RoundTrip(t *testing.T) {
	msg := gem.S1F20([]secs2.Item{secs2.A("objects")}, secs2.A("errors"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F20(body)
	if err != nil {
		t.Fatalf("DecodeS1F20: %v", err)
	}

	if len(got.OBJECTS) != 1 {
		t.Fatalf("OBJECTS: got %d elements, want 1", len(got.OBJECTS))
	}

	if !bytes.Equal(got.OBJECTS[0].ToBytes(), secs2.A("objects").ToBytes()) {
		t.Errorf("OBJECTS: got %x, want %x", got.OBJECTS[0].ToBytes(), secs2.A("objects").ToBytes())
	}

	if len(got.ERRORS) != 1 {
		t.Fatalf("ERRORS: got %d elements, want 1", len(got.ERRORS))
	}

	if !bytes.Equal(got.ERRORS[0].ToBytes(), secs2.A("errors").ToBytes()) {
		t.Errorf("ERRORS: got %x, want %x", got.ERRORS[0].ToBytes(), secs2.A("errors").ToBytes())
	}
}

func TestDecodeS1F21RoundTrip(t *testing.T) {
	msg := gem.S1F21(secs2.A("vids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F21(body)
	if err != nil {
		t.Fatalf("DecodeS1F21: %v", err)
	}

	if len(got.VIDS) != 1 {
		t.Fatalf("VIDS: got %d elements, want 1", len(got.VIDS))
	}

	if !bytes.Equal(got.VIDS[0].ToBytes(), secs2.A("vids").ToBytes()) {
		t.Errorf("VIDS: got %x, want %x", got.VIDS[0].ToBytes(), secs2.A("vids").ToBytes())
	}
}

func TestDecodeS1F22RoundTrip(t *testing.T) {
	msg := gem.S1F22(secs2.A("vids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F22(body)
	if err != nil {
		t.Fatalf("DecodeS1F22: %v", err)
	}

	if len(got.VIDS) != 1 {
		t.Fatalf("VIDS: got %d elements, want 1", len(got.VIDS))
	}

	if !bytes.Equal(got.VIDS[0].ToBytes(), secs2.A("vids").ToBytes()) {
		t.Errorf("VIDS: got %x, want %x", got.VIDS[0].ToBytes(), secs2.A("vids").ToBytes())
	}
}

func TestDecodeS1F23RoundTrip(t *testing.T) {
	msg := gem.S1F23(secs2.A("ceids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F23(body)
	if err != nil {
		t.Fatalf("DecodeS1F23: %v", err)
	}

	if len(got.CEIDS) != 1 {
		t.Fatalf("CEIDS: got %d elements, want 1", len(got.CEIDS))
	}

	if !bytes.Equal(got.CEIDS[0].ToBytes(), secs2.A("ceids").ToBytes()) {
		t.Errorf("CEIDS: got %x, want %x", got.CEIDS[0].ToBytes(), secs2.A("ceids").ToBytes())
	}
}

func TestDecodeS1F24RoundTrip(t *testing.T) {
	msg := gem.S1F24(secs2.A("ceids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS1F24(body)
	if err != nil {
		t.Fatalf("DecodeS1F24: %v", err)
	}

	if len(got.CEIDS) != 1 {
		t.Fatalf("CEIDS: got %d elements, want 1", len(got.CEIDS))
	}

	if !bytes.Equal(got.CEIDS[0].ToBytes(), secs2.A("ceids").ToBytes()) {
		t.Errorf("CEIDS: got %x, want %x", got.CEIDS[0].ToBytes(), secs2.A("ceids").ToBytes())
	}
}
