// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S1F2Reply is the decoded body of the S1F2 (On Line Data) message for equipment.
//
// Body: L[2]{ A[mdln] A[softrev] }.
//
// It is filled by [DecodeS1F2] and mirrors the parameters of [S1F2], in order.
type S1F2Reply struct {
	MDLN    string
	SOFTREV string
}

// DecodeS1F2 decodes the body of an S1F2 (On Line Data) message for equipment into a [S1F2Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F2Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F2(item secs2.Item) (S1F2Reply, error) {
	var out S1F2Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S1F2 body", 2); err != nil {
		return out, err
	}

	if out.MDLN, err = decodeASCII(root.At(0), "MDLN"); err != nil {
		return out, err
	}

	if out.SOFTREV, err = decodeASCII(root.At(1), "SOFTREV"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F2HostReply is the decoded body of the S1F2 (On Line Data) message for host.
//
// Body: L[0]{  }.
//
// It is filled by [DecodeS1F2Host] and mirrors the parameters of [S1F2Host], in order.
type S1F2HostReply struct{}

// DecodeS1F2Host decodes the body of an S1F2 (On Line Data) message for host into a [S1F2HostReply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F2HostReply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F2Host(item secs2.Item) (S1F2HostReply, error) {
	var out S1F2HostReply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S1F2 body", 0); err != nil {
		return out, err
	}

	return out, nil
}

// S1F3Body is the decoded body of the S1F3 (Selected Equipment Status Request) message.
//
// Body: L[n]{ <svids>... }.
//
// It is filled by [DecodeS1F3] and mirrors the parameters of [S1F3], in order.
type S1F3Body struct {
	SVIDS []secs2.Item
}

// DecodeS1F3 decodes the body of an S1F3 (Selected Equipment Status Request) message into a [S1F3Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F3Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F3(item secs2.Item) (S1F3Body, error) {
	var out S1F3Body

	var err error

	root := secs2.NewCursor(item)

	if out.SVIDS, err = decodeItems(root, "SVIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F4Reply is the decoded body of the S1F4 (Selected Equipment Status Data) message.
//
// Body: L[n]{ <svs>... }.
//
// It is filled by [DecodeS1F4] and mirrors the parameters of [S1F4], in order.
type S1F4Reply struct {
	SVS []secs2.Item
}

// DecodeS1F4 decodes the body of an S1F4 (Selected Equipment Status Data) message into a [S1F4Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F4Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F4(item secs2.Item) (S1F4Reply, error) {
	var out S1F4Reply

	var err error

	root := secs2.NewCursor(item)

	if out.SVS, err = decodeItems(root, "SVS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F5Body is the decoded body of the S1F5 (Formatted Status Request) message.
//
// Body: B[sfcd].
//
// It is filled by [DecodeS1F5] and mirrors the parameters of [S1F5], in order.
type S1F5Body struct {
	SFCD byte
}

// DecodeS1F5 decodes the body of an S1F5 (Formatted Status Request) message into a [S1F5Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F5Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F5(item secs2.Item) (S1F5Body, error) {
	var out S1F5Body

	var err error

	root := secs2.NewCursor(item)

	if out.SFCD, err = decodeByteAs[byte](root, "SFCD"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F6Reply is the decoded body of the S1F6 (Formatted Status Data) message.
//
// Body: form-dependent (see description).
//
// It is filled by [DecodeS1F6] and mirrors the parameters of [S1F6], in order.
type S1F6Reply struct {
	BODY secs2.Item
}

// DecodeS1F6 decodes the body of an S1F6 (Formatted Status Data) message into a [S1F6Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F6Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F6(item secs2.Item) (S1F6Reply, error) {
	var out S1F6Reply

	var err error

	root := secs2.NewCursor(item)

	if out.BODY, err = decodeItem(root, "body"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F7Body is the decoded body of the S1F7 (Fixed Form Request) message.
//
// Body: B[sfcd].
//
// It is filled by [DecodeS1F7] and mirrors the parameters of [S1F7], in order.
type S1F7Body struct {
	SFCD byte
}

// DecodeS1F7 decodes the body of an S1F7 (Fixed Form Request) message into a [S1F7Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F7Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F7(item secs2.Item) (S1F7Body, error) {
	var out S1F7Body

	var err error

	root := secs2.NewCursor(item)

	if out.SFCD, err = decodeByteAs[byte](root, "SFCD"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F8Reply is the decoded body of the S1F8 (Fixed Form Data) message.
//
// Body: form-dependent (see description).
//
// It is filled by [DecodeS1F8] and mirrors the parameters of [S1F8], in order.
type S1F8Reply struct {
	BODY secs2.Item
}

// DecodeS1F8 decodes the body of an S1F8 (Fixed Form Data) message into a [S1F8Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F8Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F8(item secs2.Item) (S1F8Reply, error) {
	var out S1F8Reply

	var err error

	root := secs2.NewCursor(item)

	if out.BODY, err = decodeItem(root, "body"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F10Reply is the decoded body of the S1F10 (Material Transfer Status Data) message.
//
// Body: L[2]{ B[n]{ <tsips>... } B[n]{ <tsops>... } }.
//
// It is filled by [DecodeS1F10] and mirrors the parameters of [S1F10], in order.
type S1F10Reply struct {
	TSIPS []byte
	TSOPS []byte
}

// DecodeS1F10 decodes the body of an S1F10 (Material Transfer Status Data) message into a [S1F10Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F10Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F10(item secs2.Item) (S1F10Reply, error) {
	var out S1F10Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S1F10 body", 2); err != nil {
		return out, err
	}

	if out.TSIPS, err = decodeBinary(root.At(0), "TSIPS"); err != nil {
		return out, err
	}

	if out.TSOPS, err = decodeBinary(root.At(1), "TSOPS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F11Body is the decoded body of the S1F11 (Status Variable Namelist Request) message.
//
// Body: L[n]{ <svids>... }.
//
// It is filled by [DecodeS1F11] and mirrors the parameters of [S1F11], in order.
type S1F11Body struct {
	SVIDS []secs2.Item
}

// DecodeS1F11 decodes the body of an S1F11 (Status Variable Namelist Request) message into a [S1F11Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F11Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F11(item secs2.Item) (S1F11Body, error) {
	var out S1F11Body

	var err error

	root := secs2.NewCursor(item)

	if out.SVIDS, err = decodeItems(root, "SVIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F12Reply is the decoded body of the S1F12 (Status Variable Namelist Reply) message.
//
// Body: L[n]{ <svids>... }.
//
// It is filled by [DecodeS1F12] and mirrors the parameters of [S1F12], in order.
//
// Source: reconstructed from an external reference, not verified against the purchased SEMI standard.
type S1F12Reply struct {
	SVIDS []secs2.Item
}

// DecodeS1F12 decodes the body of an S1F12 (Status Variable Namelist Reply) message into a [S1F12Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F12Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
//
// Source: reconstructed from an external reference, not verified against the purchased SEMI standard.
func DecodeS1F12(item secs2.Item) (S1F12Reply, error) {
	var out S1F12Reply

	var err error

	root := secs2.NewCursor(item)

	if out.SVIDS, err = decodeItems(root, "SVIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F13Body is the decoded body of the S1F13 (Establish Communications Request) message for equipment.
//
// Body: L[2]{ A[mdln] A[softrev] }.
//
// It is filled by [DecodeS1F13] and mirrors the parameters of [S1F13], in order.
type S1F13Body struct {
	MDLN    string
	SOFTREV string
}

// DecodeS1F13 decodes the body of an S1F13 (Establish Communications Request) message for equipment into a [S1F13Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F13Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F13(item secs2.Item) (S1F13Body, error) {
	var out S1F13Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S1F13 body", 2); err != nil {
		return out, err
	}

	if out.MDLN, err = decodeASCII(root.At(0), "MDLN"); err != nil {
		return out, err
	}

	if out.SOFTREV, err = decodeASCII(root.At(1), "SOFTREV"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F13HostBody is the decoded body of the S1F13 (Establish Communications Request) message for host.
//
// Body: L[0]{  }.
//
// It is filled by [DecodeS1F13Host] and mirrors the parameters of [S1F13Host], in order.
type S1F13HostBody struct{}

// DecodeS1F13Host decodes the body of an S1F13 (Establish Communications Request) message for host into a [S1F13HostBody].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F13HostBody] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F13Host(item secs2.Item) (S1F13HostBody, error) {
	var out S1F13HostBody

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S1F13 body", 0); err != nil {
		return out, err
	}

	return out, nil
}

// S1F14Reply is the decoded body of the S1F14 (Establish Communications Request Acknowledge) message for equipment.
//
// Body: L[2]{ B[commack] L[2]{ A[mdln] A[softrev] } }.
//
// It is filled by [DecodeS1F14] and mirrors the parameters of [S1F14], in order.
type S1F14Reply struct {
	COMMACK COMMACK
	MDLN    string
	SOFTREV string
}

// DecodeS1F14 decodes the body of an S1F14 (Establish Communications Request Acknowledge) message for equipment into a [S1F14Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F14Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F14(item secs2.Item) (S1F14Reply, error) {
	var out S1F14Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S1F14 body", 2); err != nil {
		return out, err
	}

	if out.COMMACK, err = decodeByteAs[COMMACK](root.At(0), "COMMACK"); err != nil {
		return out, err
	}

	if err = requireArity(root.At(1), "S1F14 body[1]", 2); err != nil {
		return out, err
	}

	if out.MDLN, err = decodeASCII(root.At(1, 0), "MDLN"); err != nil {
		return out, err
	}

	if out.SOFTREV, err = decodeASCII(root.At(1, 1), "SOFTREV"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F14HostReply is the decoded body of the S1F14 (Establish Communications Request Acknowledge) message for host.
//
// Body: L[2]{ B[commack] L[0]{  } }.
//
// It is filled by [DecodeS1F14Host] and mirrors the parameters of [S1F14Host], in order.
type S1F14HostReply struct {
	COMMACK COMMACK
}

// DecodeS1F14Host decodes the body of an S1F14 (Establish Communications Request Acknowledge) message for host into a [S1F14HostReply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F14HostReply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F14Host(item secs2.Item) (S1F14HostReply, error) {
	var out S1F14HostReply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S1F14 body", 2); err != nil {
		return out, err
	}

	if out.COMMACK, err = decodeByteAs[COMMACK](root.At(0), "COMMACK"); err != nil {
		return out, err
	}

	if err = requireArity(root.At(1), "S1F14 body[1]", 0); err != nil {
		return out, err
	}

	return out, nil
}

// S1F16Reply is the decoded body of the S1F16 (OFF-LINE Acknowledge) message.
//
// Body: B[oflack].
//
// It is filled by [DecodeS1F16] and mirrors the parameters of [S1F16], in order.
type S1F16Reply struct {
	OFLACK byte
}

// DecodeS1F16 decodes the body of an S1F16 (OFF-LINE Acknowledge) message into a [S1F16Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F16Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F16(item secs2.Item) (S1F16Reply, error) {
	var out S1F16Reply

	var err error

	root := secs2.NewCursor(item)

	if out.OFLACK, err = decodeByteAs[byte](root, "OFLACK"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F18Reply is the decoded body of the S1F18 (ON-LINE Acknowledge) message.
//
// Body: B[onlack].
//
// It is filled by [DecodeS1F18] and mirrors the parameters of [S1F18], in order.
type S1F18Reply struct {
	ONLACK byte
}

// DecodeS1F18 decodes the body of an S1F18 (ON-LINE Acknowledge) message into a [S1F18Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F18Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F18(item secs2.Item) (S1F18Reply, error) {
	var out S1F18Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ONLACK, err = decodeByteAs[byte](root, "ONLACK"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F19Body is the decoded body of the S1F19 (Get Attribute) message.
//
// Body: L[3]{ <objtype> L[n]{ <objids>... } L[n]{ <attrids>... } }.
//
// It is filled by [DecodeS1F19] and mirrors the parameters of [S1F19], in order.
type S1F19Body struct {
	OBJTYPE secs2.Item
	OBJIDS  []secs2.Item
	ATTRIDS []secs2.Item
}

// DecodeS1F19 decodes the body of an S1F19 (Get Attribute) message into a [S1F19Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F19Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F19(item secs2.Item) (S1F19Body, error) {
	var out S1F19Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S1F19 body", 3); err != nil {
		return out, err
	}

	if out.OBJTYPE, err = decodeItem(root.At(0), "OBJTYPE"); err != nil {
		return out, err
	}

	if out.OBJIDS, err = decodeItems(root.At(1), "OBJIDS"); err != nil {
		return out, err
	}

	if out.ATTRIDS, err = decodeItems(root.At(2), "ATTRIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F20Reply is the decoded body of the S1F20 (Attribute Data) message.
//
// Body: L[2]{ L[n]{ <objects>... } L[n]{ <errors>... } }.
//
// It is filled by [DecodeS1F20] and mirrors the parameters of [S1F20], in order.
type S1F20Reply struct {
	OBJECTS []secs2.Item
	ERRORS  []secs2.Item
}

// DecodeS1F20 decodes the body of an S1F20 (Attribute Data) message into a [S1F20Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F20Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F20(item secs2.Item) (S1F20Reply, error) {
	var out S1F20Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S1F20 body", 2); err != nil {
		return out, err
	}

	if out.OBJECTS, err = decodeItems(root.At(0), "OBJECTS"); err != nil {
		return out, err
	}

	if out.ERRORS, err = decodeItems(root.At(1), "ERRORS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F21Body is the decoded body of the S1F21 (Data Variable Namelist Request) message.
//
// Body: L[n]{ <vids>... }.
//
// It is filled by [DecodeS1F21] and mirrors the parameters of [S1F21], in order.
type S1F21Body struct {
	VIDS []secs2.Item
}

// DecodeS1F21 decodes the body of an S1F21 (Data Variable Namelist Request) message into a [S1F21Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F21Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F21(item secs2.Item) (S1F21Body, error) {
	var out S1F21Body

	var err error

	root := secs2.NewCursor(item)

	if out.VIDS, err = decodeItems(root, "VIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F22Reply is the decoded body of the S1F22 (Data Variable Namelist) message.
//
// Body: L[n]{ <vids>... }.
//
// It is filled by [DecodeS1F22] and mirrors the parameters of [S1F22], in order.
type S1F22Reply struct {
	VIDS []secs2.Item
}

// DecodeS1F22 decodes the body of an S1F22 (Data Variable Namelist) message into a [S1F22Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F22Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F22(item secs2.Item) (S1F22Reply, error) {
	var out S1F22Reply

	var err error

	root := secs2.NewCursor(item)

	if out.VIDS, err = decodeItems(root, "VIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F23Body is the decoded body of the S1F23 (Collection Event Namelist Request) message.
//
// Body: L[n]{ <ceids>... }.
//
// It is filled by [DecodeS1F23] and mirrors the parameters of [S1F23], in order.
type S1F23Body struct {
	CEIDS []secs2.Item
}

// DecodeS1F23 decodes the body of an S1F23 (Collection Event Namelist Request) message into a [S1F23Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F23Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F23(item secs2.Item) (S1F23Body, error) {
	var out S1F23Body

	var err error

	root := secs2.NewCursor(item)

	if out.CEIDS, err = decodeItems(root, "CEIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S1F24Reply is the decoded body of the S1F24 (Collection Event Namelist) message.
//
// Body: L[n]{ <ceids>... }.
//
// It is filled by [DecodeS1F24] and mirrors the parameters of [S1F24], in order.
type S1F24Reply struct {
	CEIDS []secs2.Item
}

// DecodeS1F24 decodes the body of an S1F24 (Collection Event Namelist) message into a [S1F24Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S1F24Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS1F24(item secs2.Item) (S1F24Reply, error) {
	var out S1F24Reply

	var err error

	root := secs2.NewCursor(item)

	if out.CEIDS, err = decodeItems(root, "CEIDS"); err != nil {
		return out, err
	}

	return out, nil
}
