// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

// assertS1Header checks that msg is an S1 message with the given function code and wait bit.
func assertS1Header(t *testing.T, msg secs2.SECS2Message, function uint8, wantW bool) {
	t.Helper()

	if msg.StreamCode() != 1 {
		t.Errorf("StreamCode: got %d, want 1", msg.StreamCode())
	}

	if msg.FunctionCode() != function {
		t.Errorf("FunctionCode: got %d, want %d", msg.FunctionCode(), function)
	}

	if msg.WaitBit() != wantW {
		t.Errorf("WaitBit: got %v, want %v", msg.WaitBit(), wantW)
	}
}

func TestS1F1(t *testing.T) {
	msg := gem.S1F1()

	assertS1Header(t, msg, 1, true)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS1F2(t *testing.T) {
	msg := gem.S1F2("mdln", "softrev")

	assertS1Header(t, msg, 2, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "mdln" {
		t.Errorf("mdln: got %q, want %q", v2, "mdln")
	}
	v3, err := list1[1].ToASCII()
	if err != nil {
		t.Fatalf("list1[1].ToASCII: %v", err)
	}
	if v3 != "softrev" {
		t.Errorf("softrev: got %q, want %q", v3, "softrev")
	}
}

func TestS1F2Host(t *testing.T) {
	msg := gem.S1F2Host()

	assertS1Header(t, msg, 2, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 0 {
		t.Fatalf("list length: got %d, want 0", len(list1))
	}
}

func TestS1F3(t *testing.T) {
	msg := gem.S1F3(secs2.A("svids"))

	assertS1Header(t, msg, 3, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("svids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("svids: got %x, want %x", got2, want2)
	}
}

func TestS1F4(t *testing.T) {
	msg := gem.S1F4(secs2.A("svs"))

	assertS1Header(t, msg, 4, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("svs").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("svs: got %x, want %x", got2, want2)
	}
}

func TestS1F5(t *testing.T) {
	msg := gem.S1F5(0xd7)

	assertS1Header(t, msg, 5, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xd7 {
		t.Errorf("sfcd: got %v, want %v", v1, 0xd7)
	}
}

func TestS1F6(t *testing.T) {
	msg := gem.S1F6(secs2.A("body"))

	assertS1Header(t, msg, 6, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("body").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("body: got %x, want %x", got1, want1)
	}
}

func TestS1F7(t *testing.T) {
	msg := gem.S1F7(0xd7)

	assertS1Header(t, msg, 7, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xd7 {
		t.Errorf("sfcd: got %v, want %v", v1, 0xd7)
	}
}

func TestS1F8(t *testing.T) {
	msg := gem.S1F8(secs2.A("body"))

	assertS1Header(t, msg, 8, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("body").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("body: got %x, want %x", got1, want1)
	}
}

func TestS1F9(t *testing.T) {
	msg := gem.S1F9()

	assertS1Header(t, msg, 9, true)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS1F10(t *testing.T) {
	msg := gem.S1F10([]byte{0x39}, 0xe3)

	assertS1Header(t, msg, 10, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0x39 {
		t.Errorf("tsips: got %v, want %v", v2, 0x39)
	}
	v3, err := list1[1].ToBinary()
	if err != nil {
		t.Fatalf("list1[1].ToBinary: %v", err)
	}
	if len(v3) != 1 || v3[0] != 0xe3 {
		t.Errorf("tsops: got %v, want %v", v3, 0xe3)
	}
}

func TestS1F11(t *testing.T) {
	msg := gem.S1F11(secs2.A("svids"))

	assertS1Header(t, msg, 11, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("svids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("svids: got %x, want %x", got2, want2)
	}
}

func TestS1F12(t *testing.T) {
	msg := gem.S1F12(secs2.A("svids"))

	assertS1Header(t, msg, 12, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("svids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("svids: got %x, want %x", got2, want2)
	}
}

func TestS1F13(t *testing.T) {
	msg := gem.S1F13("mdln", "softrev")

	assertS1Header(t, msg, 13, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "mdln" {
		t.Errorf("mdln: got %q, want %q", v2, "mdln")
	}
	v3, err := list1[1].ToASCII()
	if err != nil {
		t.Fatalf("list1[1].ToASCII: %v", err)
	}
	if v3 != "softrev" {
		t.Errorf("softrev: got %q, want %q", v3, "softrev")
	}
}

func TestS1F13Host(t *testing.T) {
	msg := gem.S1F13Host()

	assertS1Header(t, msg, 13, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 0 {
		t.Fatalf("list length: got %d, want 0", len(list1))
	}
}

func TestS1F14(t *testing.T) {
	msg := gem.S1F14(0xb5, "mdln", "softrev")

	assertS1Header(t, msg, 14, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0xb5 {
		t.Errorf("commack: got %v, want %v", v2, 0xb5)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list3))
	}
	v4, err := list3[0].ToASCII()
	if err != nil {
		t.Fatalf("list3[0].ToASCII: %v", err)
	}
	if v4 != "mdln" {
		t.Errorf("mdln: got %q, want %q", v4, "mdln")
	}
	v5, err := list3[1].ToASCII()
	if err != nil {
		t.Fatalf("list3[1].ToASCII: %v", err)
	}
	if v5 != "softrev" {
		t.Errorf("softrev: got %q, want %q", v5, "softrev")
	}
}

func TestS1F14Host(t *testing.T) {
	msg := gem.S1F14Host(0xb5)

	assertS1Header(t, msg, 14, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0xb5 {
		t.Errorf("commack: got %v, want %v", v2, 0xb5)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 0 {
		t.Fatalf("list length: got %d, want 0", len(list3))
	}
}

func TestS1F15(t *testing.T) {
	msg := gem.S1F15()

	assertS1Header(t, msg, 15, true)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS1F16(t *testing.T) {
	msg := gem.S1F16(0x0a)

	assertS1Header(t, msg, 16, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x0a {
		t.Errorf("oflack: got %v, want %v", v1, 0x0a)
	}
}

func TestS1F17(t *testing.T) {
	msg := gem.S1F17()

	assertS1Header(t, msg, 17, true)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS1F18(t *testing.T) {
	msg := gem.S1F18(0xc9)

	assertS1Header(t, msg, 18, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xc9 {
		t.Errorf("onlack: got %v, want %v", v1, 0xc9)
	}
}

func TestS1F19(t *testing.T) {
	msg := gem.S1F19(secs2.A("objtype"), []secs2.Item{secs2.A("objids")}, secs2.A("attrids"))

	assertS1Header(t, msg, 19, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("objtype").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("objtype: got %x, want %x", got2, want2)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("objids").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("objids: got %x, want %x", got4, want4)
	}
	list5, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list5) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list5))
	}
	got6 := list5[0].ToBytes()
	want6 := secs2.A("attrids").ToBytes()
	if !bytes.Equal(got6, want6) {
		t.Errorf("attrids: got %x, want %x", got6, want6)
	}
}

func TestS1F20(t *testing.T) {
	msg := gem.S1F20([]secs2.Item{secs2.A("objects")}, secs2.A("errors"))

	assertS1Header(t, msg, 20, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	list2, err := list1[0].ToList()
	if err != nil {
		t.Fatalf("list1[0].ToList: %v", err)
	}
	if len(list2) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list2))
	}
	got3 := list2[0].ToBytes()
	want3 := secs2.A("objects").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("objects: got %x, want %x", got3, want3)
	}
	list4, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list4) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list4))
	}
	got5 := list4[0].ToBytes()
	want5 := secs2.A("errors").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("errors: got %x, want %x", got5, want5)
	}
}

func TestS1F21(t *testing.T) {
	msg := gem.S1F21(secs2.A("vids"))

	assertS1Header(t, msg, 21, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("vids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("vids: got %x, want %x", got2, want2)
	}
}

func TestS1F22(t *testing.T) {
	msg := gem.S1F22(secs2.A("vids"))

	assertS1Header(t, msg, 22, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("vids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("vids: got %x, want %x", got2, want2)
	}
}

func TestS1F23(t *testing.T) {
	msg := gem.S1F23(secs2.A("ceids"))

	assertS1Header(t, msg, 23, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("ceids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("ceids: got %x, want %x", got2, want2)
	}
}

func TestS1F24(t *testing.T) {
	msg := gem.S1F24(secs2.A("ceids"))

	assertS1Header(t, msg, 24, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("ceids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("ceids: got %x, want %x", got2, want2)
	}
}
