// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S2F1 creates the S2F1 (Service Program Load Inquire) message, direction: bidirectional.
//
// Either the host or equipment wants to send the specified service program.
//
// Body: L[2]{ A[spid] <length> }.
//
// Exception: None.
func S2F1(spid string, length secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 1, true, secs2.L(secs2.A(spid), length))
}

// S2F2 creates the S2F2 (Service Program Load Grant) message, direction: bidirectional.
//
// Provides permission to load.
//
// Body: B[grant].
//
// Exception: None.
func S2F2(grant GRANT) secs2.SECS2Message {
	return secs2.NewMessage(2, 2, false, secs2.B(byte(grant)))
}

// S2F3 creates the S2F3 (Service Program Send) message, direction: bidirectional.
//
// The data associated with the S2F1 inquire is sent. If S2F3 is multi-block, it must be preceded by the S2F1/S2F2 Inquire/Grant transaction.
//
// Body: B[spd].
//
// Exception: None.
func S2F3(spd byte) secs2.SECS2Message {
	return secs2.NewMessage(2, 3, true, secs2.B(spd))
}

// S2F4 creates the S2F4 (Service Program Send Acknowledge) message, direction: bidirectional.
//
// Acknowledge or error.
//
// Body: B[spaack].
//
// Exception: None.
func S2F4(spaack SPAACK) secs2.SECS2Message {
	return secs2.NewMessage(2, 4, false, secs2.B(byte(spaack)))
}

// S2F5 creates the S2F5 (Service Program Load Request) message, direction: bidirectional.
//
// A service program is requested.
//
// Body: A[spid].
//
// Exception: None.
func S2F5(spid string) secs2.SECS2Message {
	return secs2.NewMessage(2, 5, true, secs2.A(spid))
}

// S2F6 creates the S2F6 (Service Program Load Data) message, direction: bidirectional.
//
// A service program is sent.
//
// Body: B[spd].
//
// Exception: A zero-length item means that the requested program cannot be returned.
func S2F6(spd byte) secs2.SECS2Message {
	return secs2.NewMessage(2, 6, false, secs2.B(spd))
}

// S2F7 creates the S2F7 (Service Program Run Send) message, direction: host-to-equipment.
//
// Start the requested program.
//
// Body: A[spid].
//
// Exception: None.
func S2F7(spid string) secs2.SECS2Message {
	return secs2.NewMessage(2, 7, true, secs2.A(spid))
}

// S2F8 creates the S2F8 (Service Program Run Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error.
//
// Body: B[csaack].
//
// Exception: None.
func S2F8(csaack CSAACK) secs2.SECS2Message {
	return secs2.NewMessage(2, 8, false, secs2.B(byte(csaack)))
}

// S2F9 creates the S2F9 (Service Program Results Request) message, direction: host-to-equipment.
//
// Ask for results of service program.
//
// Body: A[spid].
//
// Exception: None.
func S2F9(spid string) secs2.SECS2Message {
	return secs2.NewMessage(2, 9, true, secs2.A(spid))
}

// S2F10 creates the S2F10 (Service Program Results Data) message, direction: equipment-to-host.
//
// Get the results back.
//
// Body: <spr>.
//
// Exception: A zero-length item means SPR does not exist.
func S2F10(spr secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 10, false, spr)
}

// S2F11 creates the S2F11 (Service Program Directory Request) message, direction: bidirectional.
//
// There may be more than one service program.
//
// Body: Header only.
//
// Exception: None.
func S2F11() secs2.SECS2Message {
	return secs2.NewMessage(2, 11, true, secs2.NewEmptyItem())
}

// S2F12 creates the S2F12 (Service Program Directory Data) message, direction: bidirectional.
//
// A list of service program names.
//
// Body: L[n]{ <spids>... }.
//
// Exception: If n = 0, there are no service programs.
func S2F12(spids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 12, false, secs2.L(spids...))
}

// S2F13 creates the S2F13 (Equipment Constant Request) message, direction: host-to-equipment.
//
// Constants such as for calibration, servo gain, alarm limits, data collection mode, and other values that are changed infrequently can be obtained using this message.
//
// Body: L[n]{ <ecids>... }.
//
// Exception: A zero-length list means report all ECVs according to a predefined order.
func S2F13(ecids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 13, true, secs2.L(ecids...))
}

// S2F14 creates the S2F14 (Equipment Constant Data) message, direction: equipment-to-host.
//
// Data response to S2F13 in the order requested.
//
// Body: L[n]{ <ecvs>... }.
//
// Exception: A zero-length list item for ECVi means that ECIDi does not exist. The list format for this data item is not allowed, except in this case.
func S2F14(ecvs ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 14, false, secs2.L(ecvs...))
}

// S2F15 creates the S2F15 (New Equipment Constant Send) message, direction: host-to-equipment.
//
// Change one or more equipment constants.
//
// Body: L[n]{ <constants>... }.
//
// Exception: None.
func S2F15(constants ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 15, true, secs2.L(constants...))
}

// S2F16 creates the S2F16 (New Equipment Constant Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error. If EAC contains a non-zero error code, the equipment does not change any of the ECIDs specified in S2F15.
//
// Body: B[eac].
//
// Exception: None.
func S2F16(eac EAC) secs2.SECS2Message {
	return secs2.NewMessage(2, 16, false, secs2.B(byte(eac)))
}

// S2F17 creates the S2F17 (Date and Time Request) message, direction: bidirectional.
//
// Useful to check equipment time base or for equipment to synchronize with the host time base.
//
// Body: Header only.
//
// Exception: None.
func S2F17() secs2.SECS2Message {
	return secs2.NewMessage(2, 17, true, secs2.NewEmptyItem())
}

// S2F18 creates the S2F18 (Date and Time Data) message, direction: bidirectional.
//
// Actual time data.
//
// Body: A[time].
//
// Exception: A zero-length item means no time exists.
func S2F18(time string) secs2.SECS2Message {
	return secs2.NewMessage(2, 18, false, secs2.A(time))
}

// S2F19 creates the S2F19 (Reset/Initialize Send) message, direction: host-to-equipment.
//
// Causes equipment to reach one of several predetermined initialized conditions.
//
// Body: <ric>.
//
// Exception: None.
func S2F19(ric secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 19, true, ric)
}

// S2F20 creates the S2F20 (Reset Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error.
//
// Body: <rac>.
//
// Exception: None.
func S2F20(rac secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 20, false, rac)
}

// S2F21 creates the S2F21 (Remote Command Send) message, direction: host-to-equipment.
//
// Similar to pressing buttons on the front panel or causes some equipment activity to commence or to cease. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: <rcmd>.
//
// Exception: None.
func S2F21(rcmd secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 21, true, rcmd)
}

// S2F22 creates the S2F22 (Remote Command Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error.
//
// Body: <cmda>.
//
// Exception: None.
func S2F22(cmda secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 22, false, cmda)
}

// S2F23 creates the S2F23 (Trace Initialize Send) message, direction: host-to-equipment.
//
// Status variables exist at all times. This function provides a way to sample a subset of those status variables as a function of time. The trace data is returned on S6F1 and is related to the original request by the TRID. If equipment receives S2F23 with the same TRID as a trace function currently in progress, the equipment should terminate the old trace and then initiate the new trace. A trace currently in progress may be terminated by S2F23 with that TRID and TOTSMP = 0. If S2F23 is multi-block, it must be preceded by the S2F39/S2F40 Inquire/Grant transaction.
//
// Body: L[5]{ <trid> A[dsper] <totsmp> <repgsz> L[n]{ <svids>... } }.
//
// Exception: None.
func S2F23(trid secs2.Item, dsper string, totsmp secs2.Item, repgsz secs2.Item, svids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 23, true, secs2.L(trid, secs2.A(dsper), totsmp, repgsz, secs2.L(svids...)))
}

// S2F24 creates the S2F24 (Trace Initialize Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error.
//
// Body: B[tiaack].
//
// Exception: None.
func S2F24(tiaack TIAACK) secs2.SECS2Message {
	return secs2.NewMessage(2, 24, false, secs2.B(byte(tiaack)))
}

// S2F25 creates the S2F25 (Loopback Diagnostic Request) message, direction: bidirectional.
//
// A diagnostic message for checkout of protocol and communication circuits. The binary string sent is echoed back.
//
// Body: B[abs].
//
// Exception: None.
func S2F25(abs []byte) secs2.SECS2Message {
	return secs2.NewMessage(2, 25, true, secs2.B(abs))
}

// S2F26 creates the S2F26 (Loopback Diagnostic Data) message, direction: bidirectional.
//
// The echoed binary string.
//
// Body: B[abs].
//
// Exception: None.
func S2F26(abs []byte) secs2.SECS2Message {
	return secs2.NewMessage(2, 26, false, secs2.B(abs))
}

// S2F27 creates the S2F27 (Initiate Processing Request) message, direction: host-to-equipment.
//
// Host requests equipment to initiate processing of the identified material at the specified location in the machine using the specified process program.
//
// Body: L[3]{ B[loc] <ppid> L[n]{ <mids>... } }.
//
// Exception: A zero-length PPID indicates no process program is being specified and the equipment is to take whatever action is appropriate for it to determine the proper program to use. A zero-length MID list indicates no MID is to be associated with the material to be processed.
func S2F27(loc byte, ppid secs2.Item, mids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 27, true, secs2.L(secs2.B(loc), ppid, secs2.L(mids...)))
}

// S2F28 creates the S2F28 (Initiate Processing Acknowledge) message, direction: equipment-to-host.
//
// Response by equipment to Initiate Processing Request. Returned status indicates whether or not the request was honored by the equipment.
//
// Body: <cmda>.
//
// Exception: None.
func S2F28(cmda secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 28, false, cmda)
}

// S2F29 creates the S2F29 (Equipment Constant Namelist Request) message, direction: host-to-equipment.
//
// This function allows the host to retrieve basic information about what equipment constants are available in the equipment.
//
// Body: L[n]{ <ecids>... }.
//
// Exception: A zero-length list means send information for all ECIDs.
func S2F29(ecids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 29, true, secs2.L(ecids...))
}

// S2F30 creates the S2F30 (Equipment Constant Namelist) message, direction: equipment-to-host.
//
// Data response.
//
// Body: L[n]{ <constants>... }.
//
// Exception: Zero-length ASCII items for ECNAMEi, ECMINi, ECMAXi, ECDEFi, and UNITSi indicate that the ECID does not exist.
func S2F30(constants ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 30, false, secs2.L(constants...))
}

// S2F31 creates the S2F31 (Date and Time Set Request) message, direction: host-to-equipment.
//
// Useful to synchronize the equipment time with the host time base.
//
// Body: A[time].
//
// Exception: None.
func S2F31(time string) secs2.SECS2Message {
	return secs2.NewMessage(2, 31, true, secs2.A(time))
}

// S2F32 creates the S2F32 (Date and Time Set Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge the receipt of time and date.
//
// Body: B[tiack].
//
// Exception: None.
func S2F32(tiack TIACK) secs2.SECS2Message {
	return secs2.NewMessage(2, 32, false, secs2.B(byte(tiack)))
}

// S2F33 creates the S2F33 (Define Report) message, direction: host-to-equipment.
//
// The host defines a group of reports for the equipment. The type of report is designated by a Boolean equipment constant: a value of False means an Event Report (S6F11) will be sent, and a value of True means an Annotated Event Report (S6F13) will be sent. If S2F33 is multi-block, it must be preceded by the S2F39/S2F40 Inquire/Grant transaction.
//
// Body: L[2]{ <dataid> L[n]{ <reports>... } }.
//
// Exception: A list of zero length following DATAID deletes all report definitions and associated links (see S2F35). A list of zero length following a RPTID deletes that report type; all CEID links to that RPTID are also deleted.
func S2F33(dataid secs2.Item, reports ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 33, true, secs2.L(dataid, secs2.L(reports...)))
}

// S2F34 creates the S2F34 (Define Report Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error. If an error condition is detected the entire message is rejected (i.e., partial changes are not allowed).
//
// Body: B[drack].
//
// Exception: None.
func S2F34(drack DRACK) secs2.SECS2Message {
	return secs2.NewMessage(2, 34, false, secs2.B(byte(drack)))
}

// S2F35 creates the S2F35 (Link Event Report) message, direction: host-to-equipment.
//
// The host links n reports to an event (CEID). These linked event reports default to disabled upon linking; the occurrence of an event does not cause the report to be sent until enabled (see S2F37). If S2F35 is multi-block, it must be preceded by the S2F39/S2F40 Inquire/Grant transaction.
//
// Body: L[2]{ <dataid> L[n]{ <events>... } }.
//
// Exception: A list of zero length following a CEID deletes all report links to that event.
func S2F35(dataid secs2.Item, events ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 35, true, secs2.L(dataid, secs2.L(events...)))
}

// S2F36 creates the S2F36 (Link Event Report Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error. If an error condition is detected the entire message is rejected (i.e., partial changes are not allowed).
//
// Body: B[lrack].
//
// Exception: None.
func S2F36(lrack LRACK) secs2.SECS2Message {
	return secs2.NewMessage(2, 36, false, secs2.B(byte(lrack)))
}

// S2F37 creates the S2F37 (Enable/Disable Event Report) message, direction: host-to-equipment.
//
// The host enables or disables reporting for a group of events (CEIDs). When n is not zero, this message enables or disables reporting for the listed CEIDs; reporting for unlisted CEIDs is not affected.
//
// Body: L[2]{ BOOLEAN[ceed] L[n]{ <ceids>... } }.
//
// Exception: A list of zero length following CEED means all CEIDs.
func S2F37(ceed bool, ceids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 37, true, secs2.L(secs2.BOOLEAN(ceed), secs2.L(ceids...)))
}

// S2F38 creates the S2F38 (Enable/Disable Event Report Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error. If an error condition is detected the entire message is rejected (i.e., partial changes are not allowed).
//
// Body: B[erack].
//
// Exception: None.
func S2F38(erack ERACK) secs2.SECS2Message {
	return secs2.NewMessage(2, 38, false, secs2.B(byte(erack)))
}

// S2F39 creates the S2F39 (Multi-block Inquire) message, direction: host-to-equipment.
//
// If an S2F23, S2F33, S2F35, S2F45, or S2F49 message is more than one block, this transaction must precede the message.
//
// Body: L[2]{ <dataid> <datalength> }.
//
// Exception: None.
func S2F39(dataid secs2.Item, datalength secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 39, true, secs2.L(dataid, datalength))
}

// S2F40 creates the S2F40 (Multi-block Grant) message, direction: equipment-to-host.
//
// Grant permission to send a multi-block message.
//
// Body: B[grant].
//
// Exception: None.
func S2F40(grant GRANT) secs2.SECS2Message {
	return secs2.NewMessage(2, 40, false, secs2.B(byte(grant)))
}

// S2F41 creates the S2F41 (Host Command Send) message, direction: host-to-equipment.
//
// The host requests the equipment perform the specified remote command with the associated parameters.
//
// Body: L[2]{ <rcmd> L[n]{ <params>... } }.
//
// Exception: None.
func S2F41(rcmd secs2.Item, params ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 41, true, secs2.L(rcmd, secs2.L(params...)))
}

// S2F42 creates the S2F42 (Host Command Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge host command or error. If the command is not accepted due to one or more invalid parameters (i.e., HCACK = 3), a list of invalid parameters is returned containing the parameter name and reason for being invalid.
//
// Body: L[2]{ B[hcack] L[n]{ <params>... } }.
//
// Exception: If there are no invalid parameters, a list of zero length is sent for the second item.
func S2F42(hcack HCACK, params ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 42, false, secs2.L(secs2.B(byte(hcack)), secs2.L(params...)))
}

// S2F43 creates the S2F43 (Reset Spooling Streams and Functions) message, direction: host-to-equipment.
//
// The host selects specific streams and functions to be spooled whenever spooling is active. A defined list of functions for a stream replaces any previously selected functions. Spooling for Stream 1 is not allowed.
//
// Body: L[n]{ <streams>... }.
//
// Exception: A zero-length list, m = 0, turns off spooling for all streams and functions. A zero-length list, n = 0, turns on spooling for all functions for the associated stream.
func S2F43(streams ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 43, true, secs2.L(streams...))
}

// S2F44 creates the S2F44 (Reset Spooling Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error.
//
// Body: L[2]{ B[rspack] L[n]{ <streams>... } }.
//
// Exception: If RSPACK = 0, a zero-length list, m = 0, is given, indicating no streams or functions in error. A zero-length list, n = 0, indicates no functions in error for the specified stream.
func S2F44(rspack RSPACK, streams ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 44, false, secs2.L(secs2.B(byte(rspack)), secs2.L(streams...)))
}

// S2F45 creates the S2F45 (Define Variable Limit Attributes) message, direction: host-to-equipment.
//
// The host defines or changes the limit attributes for a group of variables. Each limit carries an upper and lower deadband pair. If S2F45 is multi-block, it must be preceded by the S2F39/S2F40 Inquire/Grant transaction.
//
// Body: L[2]{ <dataid> L[n]{ <variables>... } }.
//
// Exception: A zero-length list, m = 0, sets all limit values for all monitored VIDs to undefined. A zero-length list, n = 0, sets all limit values for that VID to undefined. A zero-length list, p = 0, sets that limit to undefined.
func S2F45(dataid secs2.Item, variables ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 45, true, secs2.L(dataid, secs2.L(variables...)))
}

// S2F46 creates the S2F46 (Variable Limit Attribute Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge definition of variable limit attributes or report error. If the definition is not accepted due to one or more invalid parameters (e.g., LIMITACK = 3), a list of invalid parameters is returned containing the variable limit attribute and reason for rejection. If an error condition is detected, the entire message is rejected (i.e., partial changes are not allowed).
//
// Body: L[2]{ B[vlaack] L[n]{ <variables>... } }.
//
// Exception: A zero-length list, m = 0, indicates no invalid variable limit attributes. A zero-length list, n = 0, indicates no invalid limit values for that VID.
func S2F46(vlaack VLAACK, variables ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 46, false, secs2.L(secs2.B(byte(vlaack)), secs2.L(variables...)))
}

// S2F47 creates the S2F47 (Variable Limit Attribute Request) message, direction: host-to-equipment.
//
// The host queries the equipment for current variable limit attribute definitions.
//
// Body: L[n]{ <vids>... }.
//
// Exception: A zero-length list, m = 0, requests a list of all VID values that can have variable limit attributes.
func S2F47(vids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 47, true, secs2.L(vids...))
}

// S2F48 creates the S2F48 (Variable Limit Attributes Send) message, direction: equipment-to-host.
//
// Equipment sends the values of the requested variable limit attribute definitions in the order requested.
//
// Body: L[n]{ <variables>... }.
//
// Exception: A zero-length list, p = 0, indicates that limits are not supported for the VID. A zero-length list, n = 0, means no limits are currently defined for the specified variable.
func S2F48(variables ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 48, false, secs2.L(variables...))
}

// S2F49 creates the S2F49 (Enhanced Remote Command) message, direction: host-to-equipment.
//
// The host requests an object to perform the specified remote command with its associated parameters (DATAID, OBJSPEC, RCMD, and a list of CPNAME/CEPVAL parameter groups). If multi-block, it must be preceded by the S2F39/S2F40 Multi-block Inquire/Grant transaction. The body is opaque because each CEPVAL's shape is chosen at the value level and cannot be described by a static structure: a given CEPVAL may be a single scalar, a list of same-format items, or a recursively nested list of CPNAME/CEPVAL pairs. The caller assembles the body manually via secs2 primitives.
//
// Body: form-dependent (see description).
//
// Exception: A zero-length list, m = 0, indicates that no parameter groups are sent with the command. OBJSPEC may be a null-length item.
func S2F49(body secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 49, false, body)
}

// S2F50 creates the S2F50 (Enhanced Remote Command Acknowledge) message, direction: equipment-to-host.
//
// The equipment acknowledges an Enhanced Remote Command (S2F49) or reports any errors. If the command is not accepted due to one or more invalid parameters (i.e., HCACK = 3), a list of invalid parameters is returned containing the parameter name (CPNAME) and reason for being invalid (CEPACK). The body is opaque because each CEPACK mirrors the value-dependent, possibly recursively nested shape of the corresponding CEPVAL in S2F49, which cannot be described by a static structure. The caller assembles the body manually via secs2 primitives.
//
// Body: form-dependent (see description).
//
// Exception: None.
func S2F50(body secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(2, 50, false, body)
}
