// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S2F1Body is the decoded body of the S2F1 (Service Program Load Inquire) message.
//
// Body: L[2]{ A[spid] <length> }.
//
// It is filled by [DecodeS2F1] and mirrors the parameters of [S2F1], in order.
type S2F1Body struct {
	SPID   string
	LENGTH secs2.Item
}

// DecodeS2F1 decodes the body of an S2F1 (Service Program Load Inquire) message into a [S2F1Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F1Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F1(item secs2.Item) (S2F1Body, error) {
	var out S2F1Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F1 body", 2); err != nil {
		return out, err
	}

	if out.SPID, err = decodeASCII(root.At(0), "SPID"); err != nil {
		return out, err
	}

	if out.LENGTH, err = decodeItem(root.At(1), "LENGTH"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F2Reply is the decoded body of the S2F2 (Service Program Load Grant) message.
//
// Body: B[grant].
//
// It is filled by [DecodeS2F2] and mirrors the parameters of [S2F2], in order.
type S2F2Reply struct {
	GRANT GRANT
}

// DecodeS2F2 decodes the body of an S2F2 (Service Program Load Grant) message into a [S2F2Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F2Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F2(item secs2.Item) (S2F2Reply, error) {
	var out S2F2Reply

	var err error

	root := secs2.NewCursor(item)

	if out.GRANT, err = decodeByteAs[GRANT](root, "GRANT"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F3Body is the decoded body of the S2F3 (Service Program Send) message.
//
// Body: B[spd].
//
// It is filled by [DecodeS2F3] and mirrors the parameters of [S2F3], in order.
type S2F3Body struct {
	SPD byte
}

// DecodeS2F3 decodes the body of an S2F3 (Service Program Send) message into a [S2F3Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F3Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F3(item secs2.Item) (S2F3Body, error) {
	var out S2F3Body

	var err error

	root := secs2.NewCursor(item)

	if out.SPD, err = decodeByteAs[byte](root, "SPD"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F4Reply is the decoded body of the S2F4 (Service Program Send Acknowledge) message.
//
// Body: B[spaack].
//
// It is filled by [DecodeS2F4] and mirrors the parameters of [S2F4], in order.
type S2F4Reply struct {
	SPAACK SPAACK
}

// DecodeS2F4 decodes the body of an S2F4 (Service Program Send Acknowledge) message into a [S2F4Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F4Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F4(item secs2.Item) (S2F4Reply, error) {
	var out S2F4Reply

	var err error

	root := secs2.NewCursor(item)

	if out.SPAACK, err = decodeByteAs[SPAACK](root, "SPAACK"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F5Body is the decoded body of the S2F5 (Service Program Load Request) message.
//
// Body: A[spid].
//
// It is filled by [DecodeS2F5] and mirrors the parameters of [S2F5], in order.
type S2F5Body struct {
	SPID string
}

// DecodeS2F5 decodes the body of an S2F5 (Service Program Load Request) message into a [S2F5Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F5Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F5(item secs2.Item) (S2F5Body, error) {
	var out S2F5Body

	var err error

	root := secs2.NewCursor(item)

	if out.SPID, err = decodeASCII(root, "SPID"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F6Reply is the decoded body of the S2F6 (Service Program Load Data) message.
//
// Body: B[spd].
//
// It is filled by [DecodeS2F6] and mirrors the parameters of [S2F6], in order.
type S2F6Reply struct {
	SPD byte
}

// DecodeS2F6 decodes the body of an S2F6 (Service Program Load Data) message into a [S2F6Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F6Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F6(item secs2.Item) (S2F6Reply, error) {
	var out S2F6Reply

	var err error

	root := secs2.NewCursor(item)

	if out.SPD, err = decodeByteAs[byte](root, "SPD"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F7Body is the decoded body of the S2F7 (Service Program Run Send) message.
//
// Body: A[spid].
//
// It is filled by [DecodeS2F7] and mirrors the parameters of [S2F7], in order.
type S2F7Body struct {
	SPID string
}

// DecodeS2F7 decodes the body of an S2F7 (Service Program Run Send) message into a [S2F7Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F7Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F7(item secs2.Item) (S2F7Body, error) {
	var out S2F7Body

	var err error

	root := secs2.NewCursor(item)

	if out.SPID, err = decodeASCII(root, "SPID"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F8Reply is the decoded body of the S2F8 (Service Program Run Acknowledge) message.
//
// Body: B[csaack].
//
// It is filled by [DecodeS2F8] and mirrors the parameters of [S2F8], in order.
type S2F8Reply struct {
	CSAACK CSAACK
}

// DecodeS2F8 decodes the body of an S2F8 (Service Program Run Acknowledge) message into a [S2F8Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F8Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F8(item secs2.Item) (S2F8Reply, error) {
	var out S2F8Reply

	var err error

	root := secs2.NewCursor(item)

	if out.CSAACK, err = decodeByteAs[CSAACK](root, "CSAACK"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F9Body is the decoded body of the S2F9 (Service Program Results Request) message.
//
// Body: A[spid].
//
// It is filled by [DecodeS2F9] and mirrors the parameters of [S2F9], in order.
type S2F9Body struct {
	SPID string
}

// DecodeS2F9 decodes the body of an S2F9 (Service Program Results Request) message into a [S2F9Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F9Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F9(item secs2.Item) (S2F9Body, error) {
	var out S2F9Body

	var err error

	root := secs2.NewCursor(item)

	if out.SPID, err = decodeASCII(root, "SPID"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F10Reply is the decoded body of the S2F10 (Service Program Results Data) message.
//
// Body: <spr>.
//
// It is filled by [DecodeS2F10] and mirrors the parameters of [S2F10], in order.
type S2F10Reply struct {
	SPR secs2.Item
}

// DecodeS2F10 decodes the body of an S2F10 (Service Program Results Data) message into a [S2F10Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F10Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F10(item secs2.Item) (S2F10Reply, error) {
	var out S2F10Reply

	var err error

	root := secs2.NewCursor(item)

	if out.SPR, err = decodeItem(root, "SPR"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F12Reply is the decoded body of the S2F12 (Service Program Directory Data) message.
//
// Body: L[n]{ <spids>... }.
//
// It is filled by [DecodeS2F12] and mirrors the parameters of [S2F12], in order.
type S2F12Reply struct {
	SPIDS []secs2.Item
}

// DecodeS2F12 decodes the body of an S2F12 (Service Program Directory Data) message into a [S2F12Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F12Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F12(item secs2.Item) (S2F12Reply, error) {
	var out S2F12Reply

	var err error

	root := secs2.NewCursor(item)

	if out.SPIDS, err = decodeItems(root, "SPIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F13Body is the decoded body of the S2F13 (Equipment Constant Request) message.
//
// Body: L[n]{ <ecids>... }.
//
// It is filled by [DecodeS2F13] and mirrors the parameters of [S2F13], in order.
type S2F13Body struct {
	ECIDS []secs2.Item
}

// DecodeS2F13 decodes the body of an S2F13 (Equipment Constant Request) message into a [S2F13Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F13Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F13(item secs2.Item) (S2F13Body, error) {
	var out S2F13Body

	var err error

	root := secs2.NewCursor(item)

	if out.ECIDS, err = decodeItems(root, "ECIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F14Reply is the decoded body of the S2F14 (Equipment Constant Data) message.
//
// Body: L[n]{ <ecvs>... }.
//
// It is filled by [DecodeS2F14] and mirrors the parameters of [S2F14], in order.
type S2F14Reply struct {
	ECVS []secs2.Item
}

// DecodeS2F14 decodes the body of an S2F14 (Equipment Constant Data) message into a [S2F14Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F14Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F14(item secs2.Item) (S2F14Reply, error) {
	var out S2F14Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ECVS, err = decodeItems(root, "ECVS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F15Body is the decoded body of the S2F15 (New Equipment Constant Send) message.
//
// Body: L[n]{ <constants>... }.
//
// It is filled by [DecodeS2F15] and mirrors the parameters of [S2F15], in order.
type S2F15Body struct {
	CONSTANTS []secs2.Item
}

// DecodeS2F15 decodes the body of an S2F15 (New Equipment Constant Send) message into a [S2F15Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F15Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F15(item secs2.Item) (S2F15Body, error) {
	var out S2F15Body

	var err error

	root := secs2.NewCursor(item)

	if out.CONSTANTS, err = decodeItems(root, "CONSTANTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F16Reply is the decoded body of the S2F16 (New Equipment Constant Acknowledge) message.
//
// Body: B[eac].
//
// It is filled by [DecodeS2F16] and mirrors the parameters of [S2F16], in order.
type S2F16Reply struct {
	EAC EAC
}

// DecodeS2F16 decodes the body of an S2F16 (New Equipment Constant Acknowledge) message into a [S2F16Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F16Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F16(item secs2.Item) (S2F16Reply, error) {
	var out S2F16Reply

	var err error

	root := secs2.NewCursor(item)

	if out.EAC, err = decodeByteAs[EAC](root, "EAC"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F18Reply is the decoded body of the S2F18 (Date and Time Data) message.
//
// Body: A[time].
//
// It is filled by [DecodeS2F18] and mirrors the parameters of [S2F18], in order.
type S2F18Reply struct {
	TIME string
}

// DecodeS2F18 decodes the body of an S2F18 (Date and Time Data) message into a [S2F18Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F18Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F18(item secs2.Item) (S2F18Reply, error) {
	var out S2F18Reply

	var err error

	root := secs2.NewCursor(item)

	if out.TIME, err = decodeASCII(root, "TIME"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F19Body is the decoded body of the S2F19 (Reset/Initialize Send) message.
//
// Body: <ric>.
//
// It is filled by [DecodeS2F19] and mirrors the parameters of [S2F19], in order.
type S2F19Body struct {
	RIC secs2.Item
}

// DecodeS2F19 decodes the body of an S2F19 (Reset/Initialize Send) message into a [S2F19Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F19Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F19(item secs2.Item) (S2F19Body, error) {
	var out S2F19Body

	var err error

	root := secs2.NewCursor(item)

	if out.RIC, err = decodeItem(root, "RIC"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F20Reply is the decoded body of the S2F20 (Reset Acknowledge) message.
//
// Body: <rac>.
//
// It is filled by [DecodeS2F20] and mirrors the parameters of [S2F20], in order.
type S2F20Reply struct {
	RAC secs2.Item
}

// DecodeS2F20 decodes the body of an S2F20 (Reset Acknowledge) message into a [S2F20Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F20Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F20(item secs2.Item) (S2F20Reply, error) {
	var out S2F20Reply

	var err error

	root := secs2.NewCursor(item)

	if out.RAC, err = decodeItem(root, "RAC"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F21Body is the decoded body of the S2F21 (Remote Command Send) message.
//
// Body: <rcmd>.
//
// It is filled by [DecodeS2F21] and mirrors the parameters of [S2F21], in order.
type S2F21Body struct {
	RCMD secs2.Item
}

// DecodeS2F21 decodes the body of an S2F21 (Remote Command Send) message into a [S2F21Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F21Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F21(item secs2.Item) (S2F21Body, error) {
	var out S2F21Body

	var err error

	root := secs2.NewCursor(item)

	if out.RCMD, err = decodeItem(root, "RCMD"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F22Reply is the decoded body of the S2F22 (Remote Command Acknowledge) message.
//
// Body: <cmda>.
//
// It is filled by [DecodeS2F22] and mirrors the parameters of [S2F22], in order.
type S2F22Reply struct {
	CMDA secs2.Item
}

// DecodeS2F22 decodes the body of an S2F22 (Remote Command Acknowledge) message into a [S2F22Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F22Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F22(item secs2.Item) (S2F22Reply, error) {
	var out S2F22Reply

	var err error

	root := secs2.NewCursor(item)

	if out.CMDA, err = decodeItem(root, "CMDA"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F23Body is the decoded body of the S2F23 (Trace Initialize Send) message.
//
// Body: L[5]{ <trid> A[dsper] <totsmp> <repgsz> L[n]{ <svids>... } }.
//
// It is filled by [DecodeS2F23] and mirrors the parameters of [S2F23], in order.
type S2F23Body struct {
	TRID   secs2.Item
	DSPER  string
	TOTSMP secs2.Item
	REPGSZ secs2.Item
	SVIDS  []secs2.Item
}

// DecodeS2F23 decodes the body of an S2F23 (Trace Initialize Send) message into a [S2F23Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F23Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F23(item secs2.Item) (S2F23Body, error) {
	var out S2F23Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F23 body", 5); err != nil {
		return out, err
	}

	if out.TRID, err = decodeItem(root.At(0), "TRID"); err != nil {
		return out, err
	}

	if out.DSPER, err = decodeASCII(root.At(1), "DSPER"); err != nil {
		return out, err
	}

	if out.TOTSMP, err = decodeItem(root.At(2), "TOTSMP"); err != nil {
		return out, err
	}

	if out.REPGSZ, err = decodeItem(root.At(3), "REPGSZ"); err != nil {
		return out, err
	}

	if out.SVIDS, err = decodeItems(root.At(4), "SVIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F24Reply is the decoded body of the S2F24 (Trace Initialize Acknowledge) message.
//
// Body: B[tiaack].
//
// It is filled by [DecodeS2F24] and mirrors the parameters of [S2F24], in order.
type S2F24Reply struct {
	TIAACK TIAACK
}

// DecodeS2F24 decodes the body of an S2F24 (Trace Initialize Acknowledge) message into a [S2F24Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F24Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F24(item secs2.Item) (S2F24Reply, error) {
	var out S2F24Reply

	var err error

	root := secs2.NewCursor(item)

	if out.TIAACK, err = decodeByteAs[TIAACK](root, "TIAACK"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F25Body is the decoded body of the S2F25 (Loopback Diagnostic Request) message.
//
// Body: B[abs].
//
// It is filled by [DecodeS2F25] and mirrors the parameters of [S2F25], in order.
type S2F25Body struct {
	ABS []byte
}

// DecodeS2F25 decodes the body of an S2F25 (Loopback Diagnostic Request) message into a [S2F25Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F25Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F25(item secs2.Item) (S2F25Body, error) {
	var out S2F25Body

	var err error

	root := secs2.NewCursor(item)

	if out.ABS, err = decodeBinary(root, "ABS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F26Reply is the decoded body of the S2F26 (Loopback Diagnostic Data) message.
//
// Body: B[abs].
//
// It is filled by [DecodeS2F26] and mirrors the parameters of [S2F26], in order.
type S2F26Reply struct {
	ABS []byte
}

// DecodeS2F26 decodes the body of an S2F26 (Loopback Diagnostic Data) message into a [S2F26Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F26Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F26(item secs2.Item) (S2F26Reply, error) {
	var out S2F26Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ABS, err = decodeBinary(root, "ABS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F27Body is the decoded body of the S2F27 (Initiate Processing Request) message.
//
// Body: L[3]{ B[loc] <ppid> L[n]{ <mids>... } }.
//
// It is filled by [DecodeS2F27] and mirrors the parameters of [S2F27], in order.
type S2F27Body struct {
	LOC  byte
	PPID secs2.Item
	MIDS []secs2.Item
}

// DecodeS2F27 decodes the body of an S2F27 (Initiate Processing Request) message into a [S2F27Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F27Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F27(item secs2.Item) (S2F27Body, error) {
	var out S2F27Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F27 body", 3); err != nil {
		return out, err
	}

	if out.LOC, err = decodeByteAs[byte](root.At(0), "LOC"); err != nil {
		return out, err
	}

	if out.PPID, err = decodeItem(root.At(1), "PPID"); err != nil {
		return out, err
	}

	if out.MIDS, err = decodeItems(root.At(2), "MIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F28Reply is the decoded body of the S2F28 (Initiate Processing Acknowledge) message.
//
// Body: <cmda>.
//
// It is filled by [DecodeS2F28] and mirrors the parameters of [S2F28], in order.
type S2F28Reply struct {
	CMDA secs2.Item
}

// DecodeS2F28 decodes the body of an S2F28 (Initiate Processing Acknowledge) message into a [S2F28Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F28Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F28(item secs2.Item) (S2F28Reply, error) {
	var out S2F28Reply

	var err error

	root := secs2.NewCursor(item)

	if out.CMDA, err = decodeItem(root, "CMDA"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F29Body is the decoded body of the S2F29 (Equipment Constant Namelist Request) message.
//
// Body: L[n]{ <ecids>... }.
//
// It is filled by [DecodeS2F29] and mirrors the parameters of [S2F29], in order.
type S2F29Body struct {
	ECIDS []secs2.Item
}

// DecodeS2F29 decodes the body of an S2F29 (Equipment Constant Namelist Request) message into a [S2F29Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F29Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F29(item secs2.Item) (S2F29Body, error) {
	var out S2F29Body

	var err error

	root := secs2.NewCursor(item)

	if out.ECIDS, err = decodeItems(root, "ECIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F30Reply is the decoded body of the S2F30 (Equipment Constant Namelist) message.
//
// Body: L[n]{ <constants>... }.
//
// It is filled by [DecodeS2F30] and mirrors the parameters of [S2F30], in order.
type S2F30Reply struct {
	CONSTANTS []secs2.Item
}

// DecodeS2F30 decodes the body of an S2F30 (Equipment Constant Namelist) message into a [S2F30Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F30Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F30(item secs2.Item) (S2F30Reply, error) {
	var out S2F30Reply

	var err error

	root := secs2.NewCursor(item)

	if out.CONSTANTS, err = decodeItems(root, "CONSTANTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F31Body is the decoded body of the S2F31 (Date and Time Set Request) message.
//
// Body: A[time].
//
// It is filled by [DecodeS2F31] and mirrors the parameters of [S2F31], in order.
type S2F31Body struct {
	TIME string
}

// DecodeS2F31 decodes the body of an S2F31 (Date and Time Set Request) message into a [S2F31Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F31Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F31(item secs2.Item) (S2F31Body, error) {
	var out S2F31Body

	var err error

	root := secs2.NewCursor(item)

	if out.TIME, err = decodeASCII(root, "TIME"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F32Reply is the decoded body of the S2F32 (Date and Time Set Acknowledge) message.
//
// Body: B[tiack].
//
// It is filled by [DecodeS2F32] and mirrors the parameters of [S2F32], in order.
type S2F32Reply struct {
	TIACK TIACK
}

// DecodeS2F32 decodes the body of an S2F32 (Date and Time Set Acknowledge) message into a [S2F32Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F32Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F32(item secs2.Item) (S2F32Reply, error) {
	var out S2F32Reply

	var err error

	root := secs2.NewCursor(item)

	if out.TIACK, err = decodeByteAs[TIACK](root, "TIACK"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F33Body is the decoded body of the S2F33 (Define Report) message.
//
// Body: L[2]{ <dataid> L[n]{ <reports>... } }.
//
// It is filled by [DecodeS2F33] and mirrors the parameters of [S2F33], in order.
type S2F33Body struct {
	DATAID  secs2.Item
	REPORTS []secs2.Item
}

// DecodeS2F33 decodes the body of an S2F33 (Define Report) message into a [S2F33Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F33Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F33(item secs2.Item) (S2F33Body, error) {
	var out S2F33Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F33 body", 2); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.REPORTS, err = decodeItems(root.At(1), "REPORTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F34Reply is the decoded body of the S2F34 (Define Report Acknowledge) message.
//
// Body: B[drack].
//
// It is filled by [DecodeS2F34] and mirrors the parameters of [S2F34], in order.
type S2F34Reply struct {
	DRACK DRACK
}

// DecodeS2F34 decodes the body of an S2F34 (Define Report Acknowledge) message into a [S2F34Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F34Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F34(item secs2.Item) (S2F34Reply, error) {
	var out S2F34Reply

	var err error

	root := secs2.NewCursor(item)

	if out.DRACK, err = decodeByteAs[DRACK](root, "DRACK"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F35Body is the decoded body of the S2F35 (Link Event Report) message.
//
// Body: L[2]{ <dataid> L[n]{ <events>... } }.
//
// It is filled by [DecodeS2F35] and mirrors the parameters of [S2F35], in order.
type S2F35Body struct {
	DATAID secs2.Item
	EVENTS []secs2.Item
}

// DecodeS2F35 decodes the body of an S2F35 (Link Event Report) message into a [S2F35Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F35Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F35(item secs2.Item) (S2F35Body, error) {
	var out S2F35Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F35 body", 2); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.EVENTS, err = decodeItems(root.At(1), "EVENTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F36Reply is the decoded body of the S2F36 (Link Event Report Acknowledge) message.
//
// Body: B[lrack].
//
// It is filled by [DecodeS2F36] and mirrors the parameters of [S2F36], in order.
type S2F36Reply struct {
	LRACK LRACK
}

// DecodeS2F36 decodes the body of an S2F36 (Link Event Report Acknowledge) message into a [S2F36Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F36Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F36(item secs2.Item) (S2F36Reply, error) {
	var out S2F36Reply

	var err error

	root := secs2.NewCursor(item)

	if out.LRACK, err = decodeByteAs[LRACK](root, "LRACK"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F37Body is the decoded body of the S2F37 (Enable/Disable Event Report) message.
//
// Body: L[2]{ BOOLEAN[ceed] L[n]{ <ceids>... } }.
//
// It is filled by [DecodeS2F37] and mirrors the parameters of [S2F37], in order.
type S2F37Body struct {
	CEED  bool
	CEIDS []secs2.Item
}

// DecodeS2F37 decodes the body of an S2F37 (Enable/Disable Event Report) message into a [S2F37Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F37Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F37(item secs2.Item) (S2F37Body, error) {
	var out S2F37Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F37 body", 2); err != nil {
		return out, err
	}

	if out.CEED, err = decodeBool(root.At(0), "CEED"); err != nil {
		return out, err
	}

	if out.CEIDS, err = decodeItems(root.At(1), "CEIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F38Reply is the decoded body of the S2F38 (Enable/Disable Event Report Acknowledge) message.
//
// Body: B[erack].
//
// It is filled by [DecodeS2F38] and mirrors the parameters of [S2F38], in order.
type S2F38Reply struct {
	ERACK ERACK
}

// DecodeS2F38 decodes the body of an S2F38 (Enable/Disable Event Report Acknowledge) message into a [S2F38Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F38Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F38(item secs2.Item) (S2F38Reply, error) {
	var out S2F38Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ERACK, err = decodeByteAs[ERACK](root, "ERACK"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F39Body is the decoded body of the S2F39 (Multi-block Inquire) message.
//
// Body: L[2]{ <dataid> <datalength> }.
//
// It is filled by [DecodeS2F39] and mirrors the parameters of [S2F39], in order.
type S2F39Body struct {
	DATAID     secs2.Item
	DATALENGTH secs2.Item
}

// DecodeS2F39 decodes the body of an S2F39 (Multi-block Inquire) message into a [S2F39Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F39Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F39(item secs2.Item) (S2F39Body, error) {
	var out S2F39Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F39 body", 2); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.DATALENGTH, err = decodeItem(root.At(1), "DATALENGTH"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F40Reply is the decoded body of the S2F40 (Multi-block Grant) message.
//
// Body: B[grant].
//
// It is filled by [DecodeS2F40] and mirrors the parameters of [S2F40], in order.
type S2F40Reply struct {
	GRANT GRANT
}

// DecodeS2F40 decodes the body of an S2F40 (Multi-block Grant) message into a [S2F40Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F40Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F40(item secs2.Item) (S2F40Reply, error) {
	var out S2F40Reply

	var err error

	root := secs2.NewCursor(item)

	if out.GRANT, err = decodeByteAs[GRANT](root, "GRANT"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F41Body is the decoded body of the S2F41 (Host Command Send) message.
//
// Body: L[2]{ <rcmd> L[n]{ <params>... } }.
//
// It is filled by [DecodeS2F41] and mirrors the parameters of [S2F41], in order.
type S2F41Body struct {
	RCMD   secs2.Item
	PARAMS []secs2.Item
}

// DecodeS2F41 decodes the body of an S2F41 (Host Command Send) message into a [S2F41Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F41Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F41(item secs2.Item) (S2F41Body, error) {
	var out S2F41Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F41 body", 2); err != nil {
		return out, err
	}

	if out.RCMD, err = decodeItem(root.At(0), "RCMD"); err != nil {
		return out, err
	}

	if out.PARAMS, err = decodeItems(root.At(1), "PARAMS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F42Reply is the decoded body of the S2F42 (Host Command Acknowledge) message.
//
// Body: L[2]{ B[hcack] L[n]{ <params>... } }.
//
// It is filled by [DecodeS2F42] and mirrors the parameters of [S2F42], in order.
type S2F42Reply struct {
	HCACK  HCACK
	PARAMS []secs2.Item
}

// DecodeS2F42 decodes the body of an S2F42 (Host Command Acknowledge) message into a [S2F42Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F42Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F42(item secs2.Item) (S2F42Reply, error) {
	var out S2F42Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F42 body", 2); err != nil {
		return out, err
	}

	if out.HCACK, err = decodeByteAs[HCACK](root.At(0), "HCACK"); err != nil {
		return out, err
	}

	if out.PARAMS, err = decodeItems(root.At(1), "PARAMS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F43Body is the decoded body of the S2F43 (Reset Spooling Streams and Functions) message.
//
// Body: L[n]{ <streams>... }.
//
// It is filled by [DecodeS2F43] and mirrors the parameters of [S2F43], in order.
type S2F43Body struct {
	STREAMS []secs2.Item
}

// DecodeS2F43 decodes the body of an S2F43 (Reset Spooling Streams and Functions) message into a [S2F43Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F43Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F43(item secs2.Item) (S2F43Body, error) {
	var out S2F43Body

	var err error

	root := secs2.NewCursor(item)

	if out.STREAMS, err = decodeItems(root, "STREAMS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F44Reply is the decoded body of the S2F44 (Reset Spooling Acknowledge) message.
//
// Body: L[2]{ B[rspack] L[n]{ <streams>... } }.
//
// It is filled by [DecodeS2F44] and mirrors the parameters of [S2F44], in order.
type S2F44Reply struct {
	RSPACK  RSPACK
	STREAMS []secs2.Item
}

// DecodeS2F44 decodes the body of an S2F44 (Reset Spooling Acknowledge) message into a [S2F44Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F44Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F44(item secs2.Item) (S2F44Reply, error) {
	var out S2F44Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F44 body", 2); err != nil {
		return out, err
	}

	if out.RSPACK, err = decodeByteAs[RSPACK](root.At(0), "RSPACK"); err != nil {
		return out, err
	}

	if out.STREAMS, err = decodeItems(root.At(1), "STREAMS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F45Body is the decoded body of the S2F45 (Define Variable Limit Attributes) message.
//
// Body: L[2]{ <dataid> L[n]{ <variables>... } }.
//
// It is filled by [DecodeS2F45] and mirrors the parameters of [S2F45], in order.
type S2F45Body struct {
	DATAID    secs2.Item
	VARIABLES []secs2.Item
}

// DecodeS2F45 decodes the body of an S2F45 (Define Variable Limit Attributes) message into a [S2F45Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F45Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F45(item secs2.Item) (S2F45Body, error) {
	var out S2F45Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F45 body", 2); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.VARIABLES, err = decodeItems(root.At(1), "VARIABLES"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F46Reply is the decoded body of the S2F46 (Variable Limit Attribute Acknowledge) message.
//
// Body: L[2]{ B[vlaack] L[n]{ <variables>... } }.
//
// It is filled by [DecodeS2F46] and mirrors the parameters of [S2F46], in order.
type S2F46Reply struct {
	VLAACK    VLAACK
	VARIABLES []secs2.Item
}

// DecodeS2F46 decodes the body of an S2F46 (Variable Limit Attribute Acknowledge) message into a [S2F46Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F46Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F46(item secs2.Item) (S2F46Reply, error) {
	var out S2F46Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S2F46 body", 2); err != nil {
		return out, err
	}

	if out.VLAACK, err = decodeByteAs[VLAACK](root.At(0), "VLAACK"); err != nil {
		return out, err
	}

	if out.VARIABLES, err = decodeItems(root.At(1), "VARIABLES"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F47Body is the decoded body of the S2F47 (Variable Limit Attribute Request) message.
//
// Body: L[n]{ <vids>... }.
//
// It is filled by [DecodeS2F47] and mirrors the parameters of [S2F47], in order.
type S2F47Body struct {
	VIDS []secs2.Item
}

// DecodeS2F47 decodes the body of an S2F47 (Variable Limit Attribute Request) message into a [S2F47Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F47Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F47(item secs2.Item) (S2F47Body, error) {
	var out S2F47Body

	var err error

	root := secs2.NewCursor(item)

	if out.VIDS, err = decodeItems(root, "VIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F48Reply is the decoded body of the S2F48 (Variable Limit Attributes Send) message.
//
// Body: L[n]{ <variables>... }.
//
// It is filled by [DecodeS2F48] and mirrors the parameters of [S2F48], in order.
type S2F48Reply struct {
	VARIABLES []secs2.Item
}

// DecodeS2F48 decodes the body of an S2F48 (Variable Limit Attributes Send) message into a [S2F48Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F48Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F48(item secs2.Item) (S2F48Reply, error) {
	var out S2F48Reply

	var err error

	root := secs2.NewCursor(item)

	if out.VARIABLES, err = decodeItems(root, "VARIABLES"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F49Body is the decoded body of the S2F49 (Enhanced Remote Command) message.
//
// Body: form-dependent (see description).
//
// It is filled by [DecodeS2F49] and mirrors the parameters of [S2F49], in order.
type S2F49Body struct {
	BODY secs2.Item
}

// DecodeS2F49 decodes the body of an S2F49 (Enhanced Remote Command) message into a [S2F49Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F49Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F49(item secs2.Item) (S2F49Body, error) {
	var out S2F49Body

	var err error

	root := secs2.NewCursor(item)

	if out.BODY, err = decodeItem(root, "body"); err != nil {
		return out, err
	}

	return out, nil
}

// S2F50Reply is the decoded body of the S2F50 (Enhanced Remote Command Acknowledge) message.
//
// Body: form-dependent (see description).
//
// It is filled by [DecodeS2F50] and mirrors the parameters of [S2F50], in order.
type S2F50Reply struct {
	BODY secs2.Item
}

// DecodeS2F50 decodes the body of an S2F50 (Enhanced Remote Command Acknowledge) message into a [S2F50Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S2F50Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS2F50(item secs2.Item) (S2F50Reply, error) {
	var out S2F50Reply

	var err error

	root := secs2.NewCursor(item)

	if out.BODY, err = decodeItem(root, "body"); err != nil {
		return out, err
	}

	return out, nil
}
