// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

func TestDecodeS2F1RoundTrip(t *testing.T) {
	msg := gem.S2F1("spid", secs2.A("length"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F1(body)
	if err != nil {
		t.Fatalf("DecodeS2F1: %v", err)
	}

	if got.SPID != "spid" {
		t.Errorf("SPID: got %v, want %v", got.SPID, "spid")
	}

	if !bytes.Equal(got.LENGTH.ToBytes(), secs2.A("length").ToBytes()) {
		t.Errorf("LENGTH: got %x, want %x", got.LENGTH.ToBytes(), secs2.A("length").ToBytes())
	}
}

func TestDecodeS2F2RoundTrip(t *testing.T) {
	msg := gem.S2F2(0xee)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F2(body)
	if err != nil {
		t.Fatalf("DecodeS2F2: %v", err)
	}

	if got.GRANT != 0xee {
		t.Errorf("GRANT: got %v, want %v", got.GRANT, 0xee)
	}
}

func TestDecodeS2F3RoundTrip(t *testing.T) {
	msg := gem.S2F3(0x29)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F3(body)
	if err != nil {
		t.Fatalf("DecodeS2F3: %v", err)
	}

	if got.SPD != 0x29 {
		t.Errorf("SPD: got %v, want %v", got.SPD, 0x29)
	}
}

func TestDecodeS2F4RoundTrip(t *testing.T) {
	msg := gem.S2F4(0x1e)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F4(body)
	if err != nil {
		t.Fatalf("DecodeS2F4: %v", err)
	}

	if got.SPAACK != 0x1e {
		t.Errorf("SPAACK: got %v, want %v", got.SPAACK, 0x1e)
	}
}

func TestDecodeS2F5RoundTrip(t *testing.T) {
	msg := gem.S2F5("spid")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F5(body)
	if err != nil {
		t.Fatalf("DecodeS2F5: %v", err)
	}

	if got.SPID != "spid" {
		t.Errorf("SPID: got %v, want %v", got.SPID, "spid")
	}
}

func TestDecodeS2F6RoundTrip(t *testing.T) {
	msg := gem.S2F6(0x29)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F6(body)
	if err != nil {
		t.Fatalf("DecodeS2F6: %v", err)
	}

	if got.SPD != 0x29 {
		t.Errorf("SPD: got %v, want %v", got.SPD, 0x29)
	}
}

func TestDecodeS2F7RoundTrip(t *testing.T) {
	msg := gem.S2F7("spid")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F7(body)
	if err != nil {
		t.Fatalf("DecodeS2F7: %v", err)
	}

	if got.SPID != "spid" {
		t.Errorf("SPID: got %v, want %v", got.SPID, "spid")
	}
}

func TestDecodeS2F8RoundTrip(t *testing.T) {
	msg := gem.S2F8(0x94)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F8(body)
	if err != nil {
		t.Fatalf("DecodeS2F8: %v", err)
	}

	if got.CSAACK != 0x94 {
		t.Errorf("CSAACK: got %v, want %v", got.CSAACK, 0x94)
	}
}

func TestDecodeS2F9RoundTrip(t *testing.T) {
	msg := gem.S2F9("spid")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F9(body)
	if err != nil {
		t.Fatalf("DecodeS2F9: %v", err)
	}

	if got.SPID != "spid" {
		t.Errorf("SPID: got %v, want %v", got.SPID, "spid")
	}
}

func TestDecodeS2F10RoundTrip(t *testing.T) {
	msg := gem.S2F10(secs2.A("spr"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F10(body)
	if err != nil {
		t.Fatalf("DecodeS2F10: %v", err)
	}

	if !bytes.Equal(got.SPR.ToBytes(), secs2.A("spr").ToBytes()) {
		t.Errorf("SPR: got %x, want %x", got.SPR.ToBytes(), secs2.A("spr").ToBytes())
	}
}

func TestDecodeS2F12RoundTrip(t *testing.T) {
	msg := gem.S2F12(secs2.A("spids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F12(body)
	if err != nil {
		t.Fatalf("DecodeS2F12: %v", err)
	}

	if len(got.SPIDS) != 1 {
		t.Fatalf("SPIDS: got %d elements, want 1", len(got.SPIDS))
	}

	if !bytes.Equal(got.SPIDS[0].ToBytes(), secs2.A("spids").ToBytes()) {
		t.Errorf("SPIDS: got %x, want %x", got.SPIDS[0].ToBytes(), secs2.A("spids").ToBytes())
	}
}

func TestDecodeS2F13RoundTrip(t *testing.T) {
	msg := gem.S2F13(secs2.A("ecids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F13(body)
	if err != nil {
		t.Fatalf("DecodeS2F13: %v", err)
	}

	if len(got.ECIDS) != 1 {
		t.Fatalf("ECIDS: got %d elements, want 1", len(got.ECIDS))
	}

	if !bytes.Equal(got.ECIDS[0].ToBytes(), secs2.A("ecids").ToBytes()) {
		t.Errorf("ECIDS: got %x, want %x", got.ECIDS[0].ToBytes(), secs2.A("ecids").ToBytes())
	}
}

func TestDecodeS2F14RoundTrip(t *testing.T) {
	msg := gem.S2F14(secs2.A("ecvs"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F14(body)
	if err != nil {
		t.Fatalf("DecodeS2F14: %v", err)
	}

	if len(got.ECVS) != 1 {
		t.Fatalf("ECVS: got %d elements, want 1", len(got.ECVS))
	}

	if !bytes.Equal(got.ECVS[0].ToBytes(), secs2.A("ecvs").ToBytes()) {
		t.Errorf("ECVS: got %x, want %x", got.ECVS[0].ToBytes(), secs2.A("ecvs").ToBytes())
	}
}

func TestDecodeS2F15RoundTrip(t *testing.T) {
	msg := gem.S2F15(secs2.A("constants"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F15(body)
	if err != nil {
		t.Fatalf("DecodeS2F15: %v", err)
	}

	if len(got.CONSTANTS) != 1 {
		t.Fatalf("CONSTANTS: got %d elements, want 1", len(got.CONSTANTS))
	}

	if !bytes.Equal(got.CONSTANTS[0].ToBytes(), secs2.A("constants").ToBytes()) {
		t.Errorf("CONSTANTS: got %x, want %x", got.CONSTANTS[0].ToBytes(), secs2.A("constants").ToBytes())
	}
}

func TestDecodeS2F16RoundTrip(t *testing.T) {
	msg := gem.S2F16(0x78)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F16(body)
	if err != nil {
		t.Fatalf("DecodeS2F16: %v", err)
	}

	if got.EAC != 0x78 {
		t.Errorf("EAC: got %v, want %v", got.EAC, 0x78)
	}
}

func TestDecodeS2F18RoundTrip(t *testing.T) {
	msg := gem.S2F18("time")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F18(body)
	if err != nil {
		t.Fatalf("DecodeS2F18: %v", err)
	}

	if got.TIME != "time" {
		t.Errorf("TIME: got %v, want %v", got.TIME, "time")
	}
}

func TestDecodeS2F19RoundTrip(t *testing.T) {
	msg := gem.S2F19(secs2.A("ric"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F19(body)
	if err != nil {
		t.Fatalf("DecodeS2F19: %v", err)
	}

	if !bytes.Equal(got.RIC.ToBytes(), secs2.A("ric").ToBytes()) {
		t.Errorf("RIC: got %x, want %x", got.RIC.ToBytes(), secs2.A("ric").ToBytes())
	}
}

func TestDecodeS2F20RoundTrip(t *testing.T) {
	msg := gem.S2F20(secs2.A("rac"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F20(body)
	if err != nil {
		t.Fatalf("DecodeS2F20: %v", err)
	}

	if !bytes.Equal(got.RAC.ToBytes(), secs2.A("rac").ToBytes()) {
		t.Errorf("RAC: got %x, want %x", got.RAC.ToBytes(), secs2.A("rac").ToBytes())
	}
}

func TestDecodeS2F21RoundTrip(t *testing.T) {
	msg := gem.S2F21(secs2.A("rcmd"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F21(body)
	if err != nil {
		t.Fatalf("DecodeS2F21: %v", err)
	}

	if !bytes.Equal(got.RCMD.ToBytes(), secs2.A("rcmd").ToBytes()) {
		t.Errorf("RCMD: got %x, want %x", got.RCMD.ToBytes(), secs2.A("rcmd").ToBytes())
	}
}

func TestDecodeS2F22RoundTrip(t *testing.T) {
	msg := gem.S2F22(secs2.A("cmda"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F22(body)
	if err != nil {
		t.Fatalf("DecodeS2F22: %v", err)
	}

	if !bytes.Equal(got.CMDA.ToBytes(), secs2.A("cmda").ToBytes()) {
		t.Errorf("CMDA: got %x, want %x", got.CMDA.ToBytes(), secs2.A("cmda").ToBytes())
	}
}

func TestDecodeS2F23RoundTrip(t *testing.T) {
	msg := gem.S2F23(secs2.A("trid"), "dsper", secs2.A("totsmp"), secs2.A("repgsz"), secs2.A("svids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F23(body)
	if err != nil {
		t.Fatalf("DecodeS2F23: %v", err)
	}

	if !bytes.Equal(got.TRID.ToBytes(), secs2.A("trid").ToBytes()) {
		t.Errorf("TRID: got %x, want %x", got.TRID.ToBytes(), secs2.A("trid").ToBytes())
	}

	if got.DSPER != "dsper" {
		t.Errorf("DSPER: got %v, want %v", got.DSPER, "dsper")
	}

	if !bytes.Equal(got.TOTSMP.ToBytes(), secs2.A("totsmp").ToBytes()) {
		t.Errorf("TOTSMP: got %x, want %x", got.TOTSMP.ToBytes(), secs2.A("totsmp").ToBytes())
	}

	if !bytes.Equal(got.REPGSZ.ToBytes(), secs2.A("repgsz").ToBytes()) {
		t.Errorf("REPGSZ: got %x, want %x", got.REPGSZ.ToBytes(), secs2.A("repgsz").ToBytes())
	}

	if len(got.SVIDS) != 1 {
		t.Fatalf("SVIDS: got %d elements, want 1", len(got.SVIDS))
	}

	if !bytes.Equal(got.SVIDS[0].ToBytes(), secs2.A("svids").ToBytes()) {
		t.Errorf("SVIDS: got %x, want %x", got.SVIDS[0].ToBytes(), secs2.A("svids").ToBytes())
	}
}

func TestDecodeS2F24RoundTrip(t *testing.T) {
	msg := gem.S2F24(0xe7)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F24(body)
	if err != nil {
		t.Fatalf("DecodeS2F24: %v", err)
	}

	if got.TIAACK != 0xe7 {
		t.Errorf("TIAACK: got %v, want %v", got.TIAACK, 0xe7)
	}
}

func TestDecodeS2F25RoundTrip(t *testing.T) {
	msg := gem.S2F25([]byte{0xa7, 0x49, 0xdc, 0x66})

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F25(body)
	if err != nil {
		t.Fatalf("DecodeS2F25: %v", err)
	}

	if !bytes.Equal(got.ABS, []byte{0xa7, 0x49, 0xdc, 0x66}) {
		t.Errorf("ABS: got %x, want %x", got.ABS, []byte{0xa7, 0x49, 0xdc, 0x66})
	}
}

func TestDecodeS2F26RoundTrip(t *testing.T) {
	msg := gem.S2F26([]byte{0xa7, 0x49, 0xdc, 0x66})

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F26(body)
	if err != nil {
		t.Fatalf("DecodeS2F26: %v", err)
	}

	if !bytes.Equal(got.ABS, []byte{0xa7, 0x49, 0xdc, 0x66}) {
		t.Errorf("ABS: got %x, want %x", got.ABS, []byte{0xa7, 0x49, 0xdc, 0x66})
	}
}

func TestDecodeS2F27RoundTrip(t *testing.T) {
	msg := gem.S2F27(0xd8, secs2.A("ppid"), secs2.A("mids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F27(body)
	if err != nil {
		t.Fatalf("DecodeS2F27: %v", err)
	}

	if got.LOC != 0xd8 {
		t.Errorf("LOC: got %v, want %v", got.LOC, 0xd8)
	}

	if !bytes.Equal(got.PPID.ToBytes(), secs2.A("ppid").ToBytes()) {
		t.Errorf("PPID: got %x, want %x", got.PPID.ToBytes(), secs2.A("ppid").ToBytes())
	}

	if len(got.MIDS) != 1 {
		t.Fatalf("MIDS: got %d elements, want 1", len(got.MIDS))
	}

	if !bytes.Equal(got.MIDS[0].ToBytes(), secs2.A("mids").ToBytes()) {
		t.Errorf("MIDS: got %x, want %x", got.MIDS[0].ToBytes(), secs2.A("mids").ToBytes())
	}
}

func TestDecodeS2F28RoundTrip(t *testing.T) {
	msg := gem.S2F28(secs2.A("cmda"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F28(body)
	if err != nil {
		t.Fatalf("DecodeS2F28: %v", err)
	}

	if !bytes.Equal(got.CMDA.ToBytes(), secs2.A("cmda").ToBytes()) {
		t.Errorf("CMDA: got %x, want %x", got.CMDA.ToBytes(), secs2.A("cmda").ToBytes())
	}
}

func TestDecodeS2F29RoundTrip(t *testing.T) {
	msg := gem.S2F29(secs2.A("ecids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F29(body)
	if err != nil {
		t.Fatalf("DecodeS2F29: %v", err)
	}

	if len(got.ECIDS) != 1 {
		t.Fatalf("ECIDS: got %d elements, want 1", len(got.ECIDS))
	}

	if !bytes.Equal(got.ECIDS[0].ToBytes(), secs2.A("ecids").ToBytes()) {
		t.Errorf("ECIDS: got %x, want %x", got.ECIDS[0].ToBytes(), secs2.A("ecids").ToBytes())
	}
}

func TestDecodeS2F30RoundTrip(t *testing.T) {
	msg := gem.S2F30(secs2.A("constants"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F30(body)
	if err != nil {
		t.Fatalf("DecodeS2F30: %v", err)
	}

	if len(got.CONSTANTS) != 1 {
		t.Fatalf("CONSTANTS: got %d elements, want 1", len(got.CONSTANTS))
	}

	if !bytes.Equal(got.CONSTANTS[0].ToBytes(), secs2.A("constants").ToBytes()) {
		t.Errorf("CONSTANTS: got %x, want %x", got.CONSTANTS[0].ToBytes(), secs2.A("constants").ToBytes())
	}
}

func TestDecodeS2F31RoundTrip(t *testing.T) {
	msg := gem.S2F31("time")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F31(body)
	if err != nil {
		t.Fatalf("DecodeS2F31: %v", err)
	}

	if got.TIME != "time" {
		t.Errorf("TIME: got %v, want %v", got.TIME, "time")
	}
}

func TestDecodeS2F32RoundTrip(t *testing.T) {
	msg := gem.S2F32(0xe6)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F32(body)
	if err != nil {
		t.Fatalf("DecodeS2F32: %v", err)
	}

	if got.TIACK != 0xe6 {
		t.Errorf("TIACK: got %v, want %v", got.TIACK, 0xe6)
	}
}

func TestDecodeS2F33RoundTrip(t *testing.T) {
	msg := gem.S2F33(secs2.A("dataid"), secs2.A("reports"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F33(body)
	if err != nil {
		t.Fatalf("DecodeS2F33: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if len(got.REPORTS) != 1 {
		t.Fatalf("REPORTS: got %d elements, want 1", len(got.REPORTS))
	}

	if !bytes.Equal(got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes()) {
		t.Errorf("REPORTS: got %x, want %x", got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes())
	}
}

func TestDecodeS2F34RoundTrip(t *testing.T) {
	msg := gem.S2F34(0x94)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F34(body)
	if err != nil {
		t.Fatalf("DecodeS2F34: %v", err)
	}

	if got.DRACK != 0x94 {
		t.Errorf("DRACK: got %v, want %v", got.DRACK, 0x94)
	}
}

func TestDecodeS2F35RoundTrip(t *testing.T) {
	msg := gem.S2F35(secs2.A("dataid"), secs2.A("events"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F35(body)
	if err != nil {
		t.Fatalf("DecodeS2F35: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if len(got.EVENTS) != 1 {
		t.Fatalf("EVENTS: got %d elements, want 1", len(got.EVENTS))
	}

	if !bytes.Equal(got.EVENTS[0].ToBytes(), secs2.A("events").ToBytes()) {
		t.Errorf("EVENTS: got %x, want %x", got.EVENTS[0].ToBytes(), secs2.A("events").ToBytes())
	}
}

func TestDecodeS2F36RoundTrip(t *testing.T) {
	msg := gem.S2F36(0xe5)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F36(body)
	if err != nil {
		t.Fatalf("DecodeS2F36: %v", err)
	}

	if got.LRACK != 0xe5 {
		t.Errorf("LRACK: got %v, want %v", got.LRACK, 0xe5)
	}
}

func TestDecodeS2F37RoundTrip(t *testing.T) {
	msg := gem.S2F37(true, secs2.A("ceids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F37(body)
	if err != nil {
		t.Fatalf("DecodeS2F37: %v", err)
	}

	if !got.CEED {
		t.Errorf("CEED: got %v, want true", got.CEED)
	}

	if len(got.CEIDS) != 1 {
		t.Fatalf("CEIDS: got %d elements, want 1", len(got.CEIDS))
	}

	if !bytes.Equal(got.CEIDS[0].ToBytes(), secs2.A("ceids").ToBytes()) {
		t.Errorf("CEIDS: got %x, want %x", got.CEIDS[0].ToBytes(), secs2.A("ceids").ToBytes())
	}
}

func TestDecodeS2F38RoundTrip(t *testing.T) {
	msg := gem.S2F38(0xc3)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F38(body)
	if err != nil {
		t.Fatalf("DecodeS2F38: %v", err)
	}

	if got.ERACK != 0xc3 {
		t.Errorf("ERACK: got %v, want %v", got.ERACK, 0xc3)
	}
}

func TestDecodeS2F39RoundTrip(t *testing.T) {
	msg := gem.S2F39(secs2.A("dataid"), secs2.A("datalength"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F39(body)
	if err != nil {
		t.Fatalf("DecodeS2F39: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.DATALENGTH.ToBytes(), secs2.A("datalength").ToBytes()) {
		t.Errorf("DATALENGTH: got %x, want %x", got.DATALENGTH.ToBytes(), secs2.A("datalength").ToBytes())
	}
}

func TestDecodeS2F40RoundTrip(t *testing.T) {
	msg := gem.S2F40(0xee)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F40(body)
	if err != nil {
		t.Fatalf("DecodeS2F40: %v", err)
	}

	if got.GRANT != 0xee {
		t.Errorf("GRANT: got %v, want %v", got.GRANT, 0xee)
	}
}

func TestDecodeS2F41RoundTrip(t *testing.T) {
	msg := gem.S2F41(secs2.A("rcmd"), secs2.A("params"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F41(body)
	if err != nil {
		t.Fatalf("DecodeS2F41: %v", err)
	}

	if !bytes.Equal(got.RCMD.ToBytes(), secs2.A("rcmd").ToBytes()) {
		t.Errorf("RCMD: got %x, want %x", got.RCMD.ToBytes(), secs2.A("rcmd").ToBytes())
	}

	if len(got.PARAMS) != 1 {
		t.Fatalf("PARAMS: got %d elements, want 1", len(got.PARAMS))
	}

	if !bytes.Equal(got.PARAMS[0].ToBytes(), secs2.A("params").ToBytes()) {
		t.Errorf("PARAMS: got %x, want %x", got.PARAMS[0].ToBytes(), secs2.A("params").ToBytes())
	}
}

func TestDecodeS2F42RoundTrip(t *testing.T) {
	msg := gem.S2F42(0x1f, secs2.A("params"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F42(body)
	if err != nil {
		t.Fatalf("DecodeS2F42: %v", err)
	}

	if got.HCACK != 0x1f {
		t.Errorf("HCACK: got %v, want %v", got.HCACK, 0x1f)
	}

	if len(got.PARAMS) != 1 {
		t.Fatalf("PARAMS: got %d elements, want 1", len(got.PARAMS))
	}

	if !bytes.Equal(got.PARAMS[0].ToBytes(), secs2.A("params").ToBytes()) {
		t.Errorf("PARAMS: got %x, want %x", got.PARAMS[0].ToBytes(), secs2.A("params").ToBytes())
	}
}

func TestDecodeS2F43RoundTrip(t *testing.T) {
	msg := gem.S2F43(secs2.A("streams"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F43(body)
	if err != nil {
		t.Fatalf("DecodeS2F43: %v", err)
	}

	if len(got.STREAMS) != 1 {
		t.Fatalf("STREAMS: got %d elements, want 1", len(got.STREAMS))
	}

	if !bytes.Equal(got.STREAMS[0].ToBytes(), secs2.A("streams").ToBytes()) {
		t.Errorf("STREAMS: got %x, want %x", got.STREAMS[0].ToBytes(), secs2.A("streams").ToBytes())
	}
}

func TestDecodeS2F44RoundTrip(t *testing.T) {
	msg := gem.S2F44(0xc9, secs2.A("streams"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F44(body)
	if err != nil {
		t.Fatalf("DecodeS2F44: %v", err)
	}

	if got.RSPACK != 0xc9 {
		t.Errorf("RSPACK: got %v, want %v", got.RSPACK, 0xc9)
	}

	if len(got.STREAMS) != 1 {
		t.Fatalf("STREAMS: got %d elements, want 1", len(got.STREAMS))
	}

	if !bytes.Equal(got.STREAMS[0].ToBytes(), secs2.A("streams").ToBytes()) {
		t.Errorf("STREAMS: got %x, want %x", got.STREAMS[0].ToBytes(), secs2.A("streams").ToBytes())
	}
}

func TestDecodeS2F45RoundTrip(t *testing.T) {
	msg := gem.S2F45(secs2.A("dataid"), secs2.A("variables"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F45(body)
	if err != nil {
		t.Fatalf("DecodeS2F45: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if len(got.VARIABLES) != 1 {
		t.Fatalf("VARIABLES: got %d elements, want 1", len(got.VARIABLES))
	}

	if !bytes.Equal(got.VARIABLES[0].ToBytes(), secs2.A("variables").ToBytes()) {
		t.Errorf("VARIABLES: got %x, want %x", got.VARIABLES[0].ToBytes(), secs2.A("variables").ToBytes())
	}
}

func TestDecodeS2F46RoundTrip(t *testing.T) {
	msg := gem.S2F46(0xea, secs2.A("variables"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F46(body)
	if err != nil {
		t.Fatalf("DecodeS2F46: %v", err)
	}

	if got.VLAACK != 0xea {
		t.Errorf("VLAACK: got %v, want %v", got.VLAACK, 0xea)
	}

	if len(got.VARIABLES) != 1 {
		t.Fatalf("VARIABLES: got %d elements, want 1", len(got.VARIABLES))
	}

	if !bytes.Equal(got.VARIABLES[0].ToBytes(), secs2.A("variables").ToBytes()) {
		t.Errorf("VARIABLES: got %x, want %x", got.VARIABLES[0].ToBytes(), secs2.A("variables").ToBytes())
	}
}

func TestDecodeS2F47RoundTrip(t *testing.T) {
	msg := gem.S2F47(secs2.A("vids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F47(body)
	if err != nil {
		t.Fatalf("DecodeS2F47: %v", err)
	}

	if len(got.VIDS) != 1 {
		t.Fatalf("VIDS: got %d elements, want 1", len(got.VIDS))
	}

	if !bytes.Equal(got.VIDS[0].ToBytes(), secs2.A("vids").ToBytes()) {
		t.Errorf("VIDS: got %x, want %x", got.VIDS[0].ToBytes(), secs2.A("vids").ToBytes())
	}
}

func TestDecodeS2F48RoundTrip(t *testing.T) {
	msg := gem.S2F48(secs2.A("variables"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F48(body)
	if err != nil {
		t.Fatalf("DecodeS2F48: %v", err)
	}

	if len(got.VARIABLES) != 1 {
		t.Fatalf("VARIABLES: got %d elements, want 1", len(got.VARIABLES))
	}

	if !bytes.Equal(got.VARIABLES[0].ToBytes(), secs2.A("variables").ToBytes()) {
		t.Errorf("VARIABLES: got %x, want %x", got.VARIABLES[0].ToBytes(), secs2.A("variables").ToBytes())
	}
}

func TestDecodeS2F49RoundTrip(t *testing.T) {
	msg := gem.S2F49(secs2.A("body"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F49(body)
	if err != nil {
		t.Fatalf("DecodeS2F49: %v", err)
	}

	if !bytes.Equal(got.BODY.ToBytes(), secs2.A("body").ToBytes()) {
		t.Errorf("BODY: got %x, want %x", got.BODY.ToBytes(), secs2.A("body").ToBytes())
	}
}

func TestDecodeS2F50RoundTrip(t *testing.T) {
	msg := gem.S2F50(secs2.A("body"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS2F50(body)
	if err != nil {
		t.Fatalf("DecodeS2F50: %v", err)
	}

	if !bytes.Equal(got.BODY.ToBytes(), secs2.A("body").ToBytes()) {
		t.Errorf("BODY: got %x, want %x", got.BODY.ToBytes(), secs2.A("body").ToBytes())
	}
}
