// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

// assertS2Header checks that msg is an S2 message with the given function code and wait bit.
func assertS2Header(t *testing.T, msg secs2.SECS2Message, function uint8, wantW bool) {
	t.Helper()

	if msg.StreamCode() != 2 {
		t.Errorf("StreamCode: got %d, want 2", msg.StreamCode())
	}

	if msg.FunctionCode() != function {
		t.Errorf("FunctionCode: got %d, want %d", msg.FunctionCode(), function)
	}

	if msg.WaitBit() != wantW {
		t.Errorf("WaitBit: got %v, want %v", msg.WaitBit(), wantW)
	}
}

func TestS2F1(t *testing.T) {
	msg := gem.S2F1("spid", secs2.A("length"))

	assertS2Header(t, msg, 1, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "spid" {
		t.Errorf("spid: got %q, want %q", v2, "spid")
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("length").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("length: got %x, want %x", got3, want3)
	}
}

func TestS2F2(t *testing.T) {
	msg := gem.S2F2(0xee)

	assertS2Header(t, msg, 2, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xee {
		t.Errorf("grant: got %v, want %v", v1, 0xee)
	}
}

func TestS2F3(t *testing.T) {
	msg := gem.S2F3(0x29)

	assertS2Header(t, msg, 3, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x29 {
		t.Errorf("spd: got %v, want %v", v1, 0x29)
	}
}

func TestS2F4(t *testing.T) {
	msg := gem.S2F4(0x1e)

	assertS2Header(t, msg, 4, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x1e {
		t.Errorf("spaack: got %v, want %v", v1, 0x1e)
	}
}

func TestS2F5(t *testing.T) {
	msg := gem.S2F5("spid")

	assertS2Header(t, msg, 5, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToASCII()
	if err != nil {
		t.Fatalf("decoded.ToASCII: %v", err)
	}
	if v1 != "spid" {
		t.Errorf("spid: got %q, want %q", v1, "spid")
	}
}

func TestS2F6(t *testing.T) {
	msg := gem.S2F6(0x29)

	assertS2Header(t, msg, 6, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x29 {
		t.Errorf("spd: got %v, want %v", v1, 0x29)
	}
}

func TestS2F7(t *testing.T) {
	msg := gem.S2F7("spid")

	assertS2Header(t, msg, 7, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToASCII()
	if err != nil {
		t.Fatalf("decoded.ToASCII: %v", err)
	}
	if v1 != "spid" {
		t.Errorf("spid: got %q, want %q", v1, "spid")
	}
}

func TestS2F8(t *testing.T) {
	msg := gem.S2F8(0x94)

	assertS2Header(t, msg, 8, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x94 {
		t.Errorf("csaack: got %v, want %v", v1, 0x94)
	}
}

func TestS2F9(t *testing.T) {
	msg := gem.S2F9("spid")

	assertS2Header(t, msg, 9, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToASCII()
	if err != nil {
		t.Fatalf("decoded.ToASCII: %v", err)
	}
	if v1 != "spid" {
		t.Errorf("spid: got %q, want %q", v1, "spid")
	}
}

func TestS2F10(t *testing.T) {
	msg := gem.S2F10(secs2.A("spr"))

	assertS2Header(t, msg, 10, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("spr").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("spr: got %x, want %x", got1, want1)
	}
}

func TestS2F11(t *testing.T) {
	msg := gem.S2F11()

	assertS2Header(t, msg, 11, true)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS2F12(t *testing.T) {
	msg := gem.S2F12(secs2.A("spids"))

	assertS2Header(t, msg, 12, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("spids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("spids: got %x, want %x", got2, want2)
	}
}

func TestS2F13(t *testing.T) {
	msg := gem.S2F13(secs2.A("ecids"))

	assertS2Header(t, msg, 13, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("ecids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("ecids: got %x, want %x", got2, want2)
	}
}

func TestS2F14(t *testing.T) {
	msg := gem.S2F14(secs2.A("ecvs"))

	assertS2Header(t, msg, 14, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("ecvs").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("ecvs: got %x, want %x", got2, want2)
	}
}

func TestS2F15(t *testing.T) {
	msg := gem.S2F15(secs2.A("constants"))

	assertS2Header(t, msg, 15, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("constants").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("constants: got %x, want %x", got2, want2)
	}
}

func TestS2F16(t *testing.T) {
	msg := gem.S2F16(0x78)

	assertS2Header(t, msg, 16, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x78 {
		t.Errorf("eac: got %v, want %v", v1, 0x78)
	}
}

func TestS2F17(t *testing.T) {
	msg := gem.S2F17()

	assertS2Header(t, msg, 17, true)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS2F18(t *testing.T) {
	msg := gem.S2F18("time")

	assertS2Header(t, msg, 18, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToASCII()
	if err != nil {
		t.Fatalf("decoded.ToASCII: %v", err)
	}
	if v1 != "time" {
		t.Errorf("time: got %q, want %q", v1, "time")
	}
}

func TestS2F19(t *testing.T) {
	msg := gem.S2F19(secs2.A("ric"))

	assertS2Header(t, msg, 19, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("ric").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("ric: got %x, want %x", got1, want1)
	}
}

func TestS2F20(t *testing.T) {
	msg := gem.S2F20(secs2.A("rac"))

	assertS2Header(t, msg, 20, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("rac").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("rac: got %x, want %x", got1, want1)
	}
}

func TestS2F21(t *testing.T) {
	msg := gem.S2F21(secs2.A("rcmd"))

	assertS2Header(t, msg, 21, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("rcmd").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("rcmd: got %x, want %x", got1, want1)
	}
}

func TestS2F22(t *testing.T) {
	msg := gem.S2F22(secs2.A("cmda"))

	assertS2Header(t, msg, 22, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("cmda").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("cmda: got %x, want %x", got1, want1)
	}
}

func TestS2F23(t *testing.T) {
	msg := gem.S2F23(secs2.A("trid"), "dsper", secs2.A("totsmp"), secs2.A("repgsz"), secs2.A("svids"))

	assertS2Header(t, msg, 23, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 5 {
		t.Fatalf("list length: got %d, want 5", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("trid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("trid: got %x, want %x", got2, want2)
	}
	v3, err := list1[1].ToASCII()
	if err != nil {
		t.Fatalf("list1[1].ToASCII: %v", err)
	}
	if v3 != "dsper" {
		t.Errorf("dsper: got %q, want %q", v3, "dsper")
	}
	got4 := list1[2].ToBytes()
	want4 := secs2.A("totsmp").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("totsmp: got %x, want %x", got4, want4)
	}
	got5 := list1[3].ToBytes()
	want5 := secs2.A("repgsz").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("repgsz: got %x, want %x", got5, want5)
	}
	list6, err := list1[4].ToList()
	if err != nil {
		t.Fatalf("list1[4].ToList: %v", err)
	}
	if len(list6) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list6))
	}
	got7 := list6[0].ToBytes()
	want7 := secs2.A("svids").ToBytes()
	if !bytes.Equal(got7, want7) {
		t.Errorf("svids: got %x, want %x", got7, want7)
	}
}

func TestS2F24(t *testing.T) {
	msg := gem.S2F24(0xe7)

	assertS2Header(t, msg, 24, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xe7 {
		t.Errorf("tiaack: got %v, want %v", v1, 0xe7)
	}
}

func TestS2F25(t *testing.T) {
	msg := gem.S2F25([]byte{0xa7, 0x49, 0xdc, 0x66})

	assertS2Header(t, msg, 25, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if !bytes.Equal(v1, []byte{0xa7, 0x49, 0xdc, 0x66}) {
		t.Errorf("abs: got %x, want %x", v1, []byte{0xa7, 0x49, 0xdc, 0x66})
	}
}

func TestS2F26(t *testing.T) {
	msg := gem.S2F26([]byte{0xa7, 0x49, 0xdc, 0x66})

	assertS2Header(t, msg, 26, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if !bytes.Equal(v1, []byte{0xa7, 0x49, 0xdc, 0x66}) {
		t.Errorf("abs: got %x, want %x", v1, []byte{0xa7, 0x49, 0xdc, 0x66})
	}
}

func TestS2F27(t *testing.T) {
	msg := gem.S2F27(0xd8, secs2.A("ppid"), secs2.A("mids"))

	assertS2Header(t, msg, 27, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0xd8 {
		t.Errorf("loc: got %v, want %v", v2, 0xd8)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("ppid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("ppid: got %x, want %x", got3, want3)
	}
	list4, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list4) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list4))
	}
	got5 := list4[0].ToBytes()
	want5 := secs2.A("mids").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("mids: got %x, want %x", got5, want5)
	}
}

func TestS2F28(t *testing.T) {
	msg := gem.S2F28(secs2.A("cmda"))

	assertS2Header(t, msg, 28, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("cmda").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("cmda: got %x, want %x", got1, want1)
	}
}

func TestS2F29(t *testing.T) {
	msg := gem.S2F29(secs2.A("ecids"))

	assertS2Header(t, msg, 29, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("ecids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("ecids: got %x, want %x", got2, want2)
	}
}

func TestS2F30(t *testing.T) {
	msg := gem.S2F30(secs2.A("constants"))

	assertS2Header(t, msg, 30, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("constants").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("constants: got %x, want %x", got2, want2)
	}
}

func TestS2F31(t *testing.T) {
	msg := gem.S2F31("time")

	assertS2Header(t, msg, 31, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToASCII()
	if err != nil {
		t.Fatalf("decoded.ToASCII: %v", err)
	}
	if v1 != "time" {
		t.Errorf("time: got %q, want %q", v1, "time")
	}
}

func TestS2F32(t *testing.T) {
	msg := gem.S2F32(0xe6)

	assertS2Header(t, msg, 32, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xe6 {
		t.Errorf("tiack: got %v, want %v", v1, 0xe6)
	}
}

func TestS2F33(t *testing.T) {
	msg := gem.S2F33(secs2.A("dataid"), secs2.A("reports"))

	assertS2Header(t, msg, 33, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("reports").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("reports: got %x, want %x", got4, want4)
	}
}

func TestS2F34(t *testing.T) {
	msg := gem.S2F34(0x94)

	assertS2Header(t, msg, 34, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x94 {
		t.Errorf("drack: got %v, want %v", v1, 0x94)
	}
}

func TestS2F35(t *testing.T) {
	msg := gem.S2F35(secs2.A("dataid"), secs2.A("events"))

	assertS2Header(t, msg, 35, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("events").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("events: got %x, want %x", got4, want4)
	}
}

func TestS2F36(t *testing.T) {
	msg := gem.S2F36(0xe5)

	assertS2Header(t, msg, 36, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xe5 {
		t.Errorf("lrack: got %v, want %v", v1, 0xe5)
	}
}

func TestS2F37(t *testing.T) {
	msg := gem.S2F37(true, secs2.A("ceids"))

	assertS2Header(t, msg, 37, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToBoolean()
	if err != nil {
		t.Fatalf("list1[0].ToBoolean: %v", err)
	}
	if len(v2) != 1 || v2[0] != true {
		t.Errorf("ceed: got %v, want %v", v2, true)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("ceids").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("ceids: got %x, want %x", got4, want4)
	}
}

func TestS2F38(t *testing.T) {
	msg := gem.S2F38(0xc3)

	assertS2Header(t, msg, 38, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xc3 {
		t.Errorf("erack: got %v, want %v", v1, 0xc3)
	}
}

func TestS2F39(t *testing.T) {
	msg := gem.S2F39(secs2.A("dataid"), secs2.A("datalength"))

	assertS2Header(t, msg, 39, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("datalength").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("datalength: got %x, want %x", got3, want3)
	}
}

func TestS2F40(t *testing.T) {
	msg := gem.S2F40(0xee)

	assertS2Header(t, msg, 40, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xee {
		t.Errorf("grant: got %v, want %v", v1, 0xee)
	}
}

func TestS2F41(t *testing.T) {
	msg := gem.S2F41(secs2.A("rcmd"), secs2.A("params"))

	assertS2Header(t, msg, 41, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("rcmd").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("rcmd: got %x, want %x", got2, want2)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("params").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("params: got %x, want %x", got4, want4)
	}
}

func TestS2F42(t *testing.T) {
	msg := gem.S2F42(0x1f, secs2.A("params"))

	assertS2Header(t, msg, 42, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0x1f {
		t.Errorf("hcack: got %v, want %v", v2, 0x1f)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("params").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("params: got %x, want %x", got4, want4)
	}
}

func TestS2F43(t *testing.T) {
	msg := gem.S2F43(secs2.A("streams"))

	assertS2Header(t, msg, 43, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("streams").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("streams: got %x, want %x", got2, want2)
	}
}

func TestS2F44(t *testing.T) {
	msg := gem.S2F44(0xc9, secs2.A("streams"))

	assertS2Header(t, msg, 44, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0xc9 {
		t.Errorf("rspack: got %v, want %v", v2, 0xc9)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("streams").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("streams: got %x, want %x", got4, want4)
	}
}

func TestS2F45(t *testing.T) {
	msg := gem.S2F45(secs2.A("dataid"), secs2.A("variables"))

	assertS2Header(t, msg, 45, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("variables").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("variables: got %x, want %x", got4, want4)
	}
}

func TestS2F46(t *testing.T) {
	msg := gem.S2F46(0xea, secs2.A("variables"))

	assertS2Header(t, msg, 46, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0xea {
		t.Errorf("vlaack: got %v, want %v", v2, 0xea)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("variables").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("variables: got %x, want %x", got4, want4)
	}
}

func TestS2F47(t *testing.T) {
	msg := gem.S2F47(secs2.A("vids"))

	assertS2Header(t, msg, 47, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("vids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("vids: got %x, want %x", got2, want2)
	}
}

func TestS2F48(t *testing.T) {
	msg := gem.S2F48(secs2.A("variables"))

	assertS2Header(t, msg, 48, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("variables").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("variables: got %x, want %x", got2, want2)
	}
}

func TestS2F49(t *testing.T) {
	msg := gem.S2F49(secs2.A("body"))

	assertS2Header(t, msg, 49, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("body").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("body: got %x, want %x", got1, want1)
	}
}

func TestS2F50(t *testing.T) {
	msg := gem.S2F50(secs2.A("body"))

	assertS2Header(t, msg, 50, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("body").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("body: got %x, want %x", got1, want1)
	}
}
