// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S5F1 creates the S5F1 (Alarm Report Send) message, direction: equipment-to-host.
//
// This message reports a change in or presence of an alarm condition. One message is issued when the alarm is set and one message is issued when the alarm is cleared. Irrecoverable errors and attention flags may not have a corresponding clear message. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[3]{ B[alcd] <alid> A[altx] }.
//
// Exception: None.
func S5F1(alcd byte, alid secs2.Item, altx string) secs2.SECS2Message {
	return secs2.NewMessage(5, 1, true, secs2.L(secs2.B(alcd), alid, secs2.A(altx)))
}

// S5F2 creates the S5F2 (Alarm Report Acknowledge) message, direction: host-to-equipment.
//
// Acknowledge or error.
//
// Body: B[ackc5].
//
// Exception: None.
func S5F2(ackc5 ACKC5) secs2.SECS2Message {
	return secs2.NewMessage(5, 2, false, secs2.B(byte(ackc5)))
}

// S5F3 creates the S5F3 (Enable/Disable Alarm Send) message, direction: host-to-equipment.
//
// This message changes the state of the enable bit in the equipment. The enable bit determines if the alarm will be sent to the host. Alarms which are not controllable in this way are unaffected by this message. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[2]{ B[aled] <alid> }.
//
// Exception: A zero-length item for ALID means all alarms.
func S5F3(aled byte, alid secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(5, 3, true, secs2.L(secs2.B(aled), alid))
}

// S5F4 creates the S5F4 (Enable/Disable Alarm Acknowledge) message, direction: equipment-to-host.
//
// Acknowledge or error.
//
// Body: B[ackc5].
//
// Exception: None.
func S5F4(ackc5 ACKC5) secs2.SECS2Message {
	return secs2.NewMessage(5, 4, false, secs2.B(byte(ackc5)))
}

// S5F5 creates the S5F5 (List Alarms Request) message, direction: host-to-equipment.
//
// This message requests the equipment to send binary and analog alarm information to the host.
//
// Body: L[n]{ <alids>... }.
//
// Exception: A zero-length item means send all possible alarms regardless of the state of ALED.
func S5F5(alids ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(5, 5, true, secs2.L(alids...))
}

// S5F6 creates the S5F6 (List Alarm Data) message, direction: equipment-to-host.
//
// This message contains the alarm data known to the equipment. There are "m" alarms in the list.
//
// Body: L[n]{ <alarms>... }.
//
// Exception: If m = 0, no response can be made. A zero-length item returned for an ALCD or ALTX means that value does not exist.
func S5F6(alarms ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(5, 6, false, secs2.L(alarms...))
}

// S5F7 creates the S5F7 (List Enabled Alarm Request) message, direction: host-to-equipment.
//
// List alarms which are enabled.
//
// Body: Header only.
//
// Exception: None.
func S5F7() secs2.SECS2Message {
	return secs2.NewMessage(5, 7, true, secs2.NewEmptyItem())
}

// S5F8 creates the S5F8 (List Enabled Alarm Data) message, direction: equipment-to-host.
//
// This message is similar to S5F6 except that it lists only alarms which are enabled.
//
// Body: L[n]{ <alarms>... }.
//
// Exception: None.
func S5F8(alarms ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(5, 8, false, secs2.L(alarms...))
}

// S5F9 creates the S5F9 (Exception Post Notify) message, direction: equipment-to-host.
//
// This message provides the means to inform a host system that an exception condition is set. Optionally, recovery actions for the exception may be sent. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[5]{ A[timestamp] A[exid] A[extype] A[exmessage] L[n]{ <recoveryActions>... } }.
//
// Exception: A zero-length recovery-action list (n = 0) is sent when there are no possible recovery actions. This is a single-block message, so the text of each EXRECVRA may need to be restricted in length to satisfy the single-block requirement.
func S5F9(timestamp string, exid string, extype string, exmessage string, recoveryActions ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(5, 9, true, secs2.L(secs2.A(timestamp), secs2.A(exid), secs2.A(extype), secs2.A(exmessage), secs2.L(recoveryActions...)))
}

// S5F10 creates the S5F10 (Exception Post Confirm) message, direction: host-to-equipment.
//
// Host confirms receipt of the S5F9 message from the equipment.
//
// Body: Header only.
//
// Exception: None.
func S5F10() secs2.SECS2Message {
	return secs2.NewMessage(5, 10, false, secs2.NewEmptyItem())
}

// S5F11 creates the S5F11 (Exception Clear Notify) message, direction: equipment-to-host.
//
// This message provides the means to inform a host system that an exception/alarm condition is no longer active (set). Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[4]{ A[timestamp] A[exid] A[extype] A[exmessage] }.
//
// Exception: EXMESSAGE can be used to provide the reason that the exception cleared.
func S5F11(timestamp string, exid string, extype string, exmessage string) secs2.SECS2Message {
	return secs2.NewMessage(5, 11, true, secs2.L(secs2.A(timestamp), secs2.A(exid), secs2.A(extype), secs2.A(exmessage)))
}

// S5F12 creates the S5F12 (Exception Clear Confirm) message, direction: host-to-equipment.
//
// Host confirms receipt of the S5F11 message from the equipment.
//
// Body: Header only.
//
// Exception: None.
func S5F12() secs2.SECS2Message {
	return secs2.NewMessage(5, 12, false, secs2.NewEmptyItem())
}

// S5F13 creates the S5F13 (Exception Recover Request) message, direction: host-to-equipment.
//
// Request that the entity which is experiencing an error execute a recovery action.
//
// Body: L[2]{ A[exid] A[exrecvra] }.
//
// Exception: None.
func S5F13(exid string, exrecvra string) secs2.SECS2Message {
	return secs2.NewMessage(5, 13, true, secs2.L(secs2.A(exid), secs2.A(exrecvra)))
}

// S5F14 creates the S5F14 (Exception Recover Acknowledge) message, direction: equipment-to-host.
//
// The entity indicates a response to the recovery request.
//
// Body: L[2]{ A[exid] L[2]{ BOOLEAN[acka] L[0,2]{ <errcode> A[errtext] } } }.
//
// Exception: The inner list may be zero length if the recovery request was accepted.
func S5F14(exid string, acka bool, errcode secs2.Item, errtext string) secs2.SECS2Message {
	return secs2.NewMessage(5, 14, false, secs2.L(secs2.A(exid), secs2.L(secs2.BOOLEAN(acka), secs2.L(errcode, secs2.A(errtext)))))
}

// S5F15 creates the S5F15 (Exception Recovery Complete Notify) message, direction: equipment-to-host.
//
// Allows the service provider to inform the controller/host that the recovery operation completed on a specific exception, together with an error code if the recovery terminated abnormally. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[3]{ A[timestamp] A[exid] L[2]{ BOOLEAN[acka] L[0,2]{ <errcode> A[errtext] } } }.
//
// Exception: The inner list may be zero length if the recovery was successful.
func S5F15(timestamp string, exid string, acka bool, errcode secs2.Item, errtext string) secs2.SECS2Message {
	return secs2.NewMessage(5, 15, true, secs2.L(secs2.A(timestamp), secs2.A(exid), secs2.L(secs2.BOOLEAN(acka), secs2.L(errcode, secs2.A(errtext)))))
}

// S5F16 creates the S5F16 (Exception Recovery Complete Confirm) message, direction: host-to-equipment.
//
// Host confirms receipt of the S5F15 message from the equipment.
//
// Body: Header only.
//
// Exception: None.
func S5F16() secs2.SECS2Message {
	return secs2.NewMessage(5, 16, false, secs2.NewEmptyItem())
}

// S5F17 creates the S5F17 (Exception Recovery Abort Request) message, direction: host-to-equipment.
//
// Stop the recovery procedure on a specific exception.
//
// Body: A[exid].
//
// Exception: None.
func S5F17(exid string) secs2.SECS2Message {
	return secs2.NewMessage(5, 17, true, secs2.A(exid))
}

// S5F18 creates the S5F18 (Exception Recovery Abort Acknowledge) message, direction: equipment-to-host.
//
// Indicate the success of the request for Recovery Abort.
//
// Body: L[2]{ A[exid] L[2]{ BOOLEAN[acka] L[0,2]{ <errcode> A[errtext] } } }.
//
// Exception: The inner list may be zero length if the abort was successful.
func S5F18(exid string, acka bool, errcode secs2.Item, errtext string) secs2.SECS2Message {
	return secs2.NewMessage(5, 18, false, secs2.L(secs2.A(exid), secs2.L(secs2.BOOLEAN(acka), secs2.L(errcode, secs2.A(errtext)))))
}
