// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S5F1Body is the decoded body of the S5F1 (Alarm Report Send) message.
//
// Body: L[3]{ B[alcd] <alid> A[altx] }.
//
// It is filled by [DecodeS5F1] and mirrors the parameters of [S5F1], in order.
type S5F1Body struct {
	ALCD byte
	ALID secs2.Item
	ALTX string
}

// DecodeS5F1 decodes the body of an S5F1 (Alarm Report Send) message into a [S5F1Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F1Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F1(item secs2.Item) (S5F1Body, error) {
	var out S5F1Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S5F1 body", 3); err != nil {
		return out, err
	}

	if out.ALCD, err = decodeByteAs[byte](root.At(0), "ALCD"); err != nil {
		return out, err
	}

	if out.ALID, err = decodeItem(root.At(1), "ALID"); err != nil {
		return out, err
	}

	if out.ALTX, err = decodeASCII(root.At(2), "ALTX"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F2Reply is the decoded body of the S5F2 (Alarm Report Acknowledge) message.
//
// Body: B[ackc5].
//
// It is filled by [DecodeS5F2] and mirrors the parameters of [S5F2], in order.
type S5F2Reply struct {
	ACKC5 ACKC5
}

// DecodeS5F2 decodes the body of an S5F2 (Alarm Report Acknowledge) message into a [S5F2Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F2Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F2(item secs2.Item) (S5F2Reply, error) {
	var out S5F2Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ACKC5, err = decodeByteAs[ACKC5](root, "ACKC5"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F3Body is the decoded body of the S5F3 (Enable/Disable Alarm Send) message.
//
// Body: L[2]{ B[aled] <alid> }.
//
// It is filled by [DecodeS5F3] and mirrors the parameters of [S5F3], in order.
type S5F3Body struct {
	ALED byte
	ALID secs2.Item
}

// DecodeS5F3 decodes the body of an S5F3 (Enable/Disable Alarm Send) message into a [S5F3Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F3Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F3(item secs2.Item) (S5F3Body, error) {
	var out S5F3Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S5F3 body", 2); err != nil {
		return out, err
	}

	if out.ALED, err = decodeByteAs[byte](root.At(0), "ALED"); err != nil {
		return out, err
	}

	if out.ALID, err = decodeItem(root.At(1), "ALID"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F4Reply is the decoded body of the S5F4 (Enable/Disable Alarm Acknowledge) message.
//
// Body: B[ackc5].
//
// It is filled by [DecodeS5F4] and mirrors the parameters of [S5F4], in order.
type S5F4Reply struct {
	ACKC5 ACKC5
}

// DecodeS5F4 decodes the body of an S5F4 (Enable/Disable Alarm Acknowledge) message into a [S5F4Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F4Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F4(item secs2.Item) (S5F4Reply, error) {
	var out S5F4Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ACKC5, err = decodeByteAs[ACKC5](root, "ACKC5"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F5Body is the decoded body of the S5F5 (List Alarms Request) message.
//
// Body: L[n]{ <alids>... }.
//
// It is filled by [DecodeS5F5] and mirrors the parameters of [S5F5], in order.
type S5F5Body struct {
	ALIDS []secs2.Item
}

// DecodeS5F5 decodes the body of an S5F5 (List Alarms Request) message into a [S5F5Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F5Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F5(item secs2.Item) (S5F5Body, error) {
	var out S5F5Body

	var err error

	root := secs2.NewCursor(item)

	if out.ALIDS, err = decodeItems(root, "ALIDS"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F6Reply is the decoded body of the S5F6 (List Alarm Data) message.
//
// Body: L[n]{ <alarms>... }.
//
// It is filled by [DecodeS5F6] and mirrors the parameters of [S5F6], in order.
type S5F6Reply struct {
	ALARMS []secs2.Item
}

// DecodeS5F6 decodes the body of an S5F6 (List Alarm Data) message into a [S5F6Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F6Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F6(item secs2.Item) (S5F6Reply, error) {
	var out S5F6Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ALARMS, err = decodeItems(root, "ALARMS"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F8Reply is the decoded body of the S5F8 (List Enabled Alarm Data) message.
//
// Body: L[n]{ <alarms>... }.
//
// It is filled by [DecodeS5F8] and mirrors the parameters of [S5F8], in order.
type S5F8Reply struct {
	ALARMS []secs2.Item
}

// DecodeS5F8 decodes the body of an S5F8 (List Enabled Alarm Data) message into a [S5F8Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F8Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F8(item secs2.Item) (S5F8Reply, error) {
	var out S5F8Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ALARMS, err = decodeItems(root, "ALARMS"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F9Body is the decoded body of the S5F9 (Exception Post Notify) message.
//
// Body: L[5]{ A[timestamp] A[exid] A[extype] A[exmessage] L[n]{ <recoveryActions>... } }.
//
// It is filled by [DecodeS5F9] and mirrors the parameters of [S5F9], in order.
type S5F9Body struct {
	TIMESTAMP       string
	EXID            string
	EXTYPE          string
	EXMESSAGE       string
	RECOVERYACTIONS []secs2.Item
}

// DecodeS5F9 decodes the body of an S5F9 (Exception Post Notify) message into a [S5F9Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F9Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F9(item secs2.Item) (S5F9Body, error) {
	var out S5F9Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S5F9 body", 5); err != nil {
		return out, err
	}

	if out.TIMESTAMP, err = decodeASCII(root.At(0), "TIMESTAMP"); err != nil {
		return out, err
	}

	if out.EXID, err = decodeASCII(root.At(1), "EXID"); err != nil {
		return out, err
	}

	if out.EXTYPE, err = decodeASCII(root.At(2), "EXTYPE"); err != nil {
		return out, err
	}

	if out.EXMESSAGE, err = decodeASCII(root.At(3), "EXMESSAGE"); err != nil {
		return out, err
	}

	if out.RECOVERYACTIONS, err = decodeItems(root.At(4), "RECOVERYACTIONS"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F11Body is the decoded body of the S5F11 (Exception Clear Notify) message.
//
// Body: L[4]{ A[timestamp] A[exid] A[extype] A[exmessage] }.
//
// It is filled by [DecodeS5F11] and mirrors the parameters of [S5F11], in order.
type S5F11Body struct {
	TIMESTAMP string
	EXID      string
	EXTYPE    string
	EXMESSAGE string
}

// DecodeS5F11 decodes the body of an S5F11 (Exception Clear Notify) message into a [S5F11Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F11Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F11(item secs2.Item) (S5F11Body, error) {
	var out S5F11Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S5F11 body", 4); err != nil {
		return out, err
	}

	if out.TIMESTAMP, err = decodeASCII(root.At(0), "TIMESTAMP"); err != nil {
		return out, err
	}

	if out.EXID, err = decodeASCII(root.At(1), "EXID"); err != nil {
		return out, err
	}

	if out.EXTYPE, err = decodeASCII(root.At(2), "EXTYPE"); err != nil {
		return out, err
	}

	if out.EXMESSAGE, err = decodeASCII(root.At(3), "EXMESSAGE"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F13Body is the decoded body of the S5F13 (Exception Recover Request) message.
//
// Body: L[2]{ A[exid] A[exrecvra] }.
//
// It is filled by [DecodeS5F13] and mirrors the parameters of [S5F13], in order.
type S5F13Body struct {
	EXID     string
	EXRECVRA string
}

// DecodeS5F13 decodes the body of an S5F13 (Exception Recover Request) message into a [S5F13Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F13Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F13(item secs2.Item) (S5F13Body, error) {
	var out S5F13Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S5F13 body", 2); err != nil {
		return out, err
	}

	if out.EXID, err = decodeASCII(root.At(0), "EXID"); err != nil {
		return out, err
	}

	if out.EXRECVRA, err = decodeASCII(root.At(1), "EXRECVRA"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F14Reply is the decoded body of the S5F14 (Exception Recover Acknowledge) message.
//
// Body: L[2]{ A[exid] L[2]{ BOOLEAN[acka] L[0,2]{ <errcode> A[errtext] } } }.
//
// It is filled by [DecodeS5F14] and mirrors the parameters of [S5F14], in order.
type S5F14Reply struct {
	EXID    string
	ACKA    bool
	ERRCODE secs2.Item
	ERRTEXT string
}

// DecodeS5F14 decodes the body of an S5F14 (Exception Recover Acknowledge) message into a [S5F14Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F14Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F14(item secs2.Item) (S5F14Reply, error) {
	var out S5F14Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S5F14 body", 2); err != nil {
		return out, err
	}

	if out.EXID, err = decodeASCII(root.At(0), "EXID"); err != nil {
		return out, err
	}

	if err = requireArity(root.At(1), "S5F14 body[1]", 2); err != nil {
		return out, err
	}

	if out.ACKA, err = decodeBool(root.At(1, 0), "ACKA"); err != nil {
		return out, err
	}

	n1, err := optionalArity(root.At(1, 1), "S5F14 body[1][1]", 0, 2)
	if err != nil {
		return out, err
	}

	if n1 == 2 {
		if out.ERRCODE, err = decodeItem(root.At(1, 1, 0), "ERRCODE"); err != nil {
			return out, err
		}

		if out.ERRTEXT, err = decodeASCII(root.At(1, 1, 1), "ERRTEXT"); err != nil {
			return out, err
		}
	}

	return out, nil
}

// S5F15Body is the decoded body of the S5F15 (Exception Recovery Complete Notify) message.
//
// Body: L[3]{ A[timestamp] A[exid] L[2]{ BOOLEAN[acka] L[0,2]{ <errcode> A[errtext] } } }.
//
// It is filled by [DecodeS5F15] and mirrors the parameters of [S5F15], in order.
type S5F15Body struct {
	TIMESTAMP string
	EXID      string
	ACKA      bool
	ERRCODE   secs2.Item
	ERRTEXT   string
}

// DecodeS5F15 decodes the body of an S5F15 (Exception Recovery Complete Notify) message into a [S5F15Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F15Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F15(item secs2.Item) (S5F15Body, error) {
	var out S5F15Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S5F15 body", 3); err != nil {
		return out, err
	}

	if out.TIMESTAMP, err = decodeASCII(root.At(0), "TIMESTAMP"); err != nil {
		return out, err
	}

	if out.EXID, err = decodeASCII(root.At(1), "EXID"); err != nil {
		return out, err
	}

	if err = requireArity(root.At(2), "S5F15 body[2]", 2); err != nil {
		return out, err
	}

	if out.ACKA, err = decodeBool(root.At(2, 0), "ACKA"); err != nil {
		return out, err
	}

	n1, err := optionalArity(root.At(2, 1), "S5F15 body[2][1]", 0, 2)
	if err != nil {
		return out, err
	}

	if n1 == 2 {
		if out.ERRCODE, err = decodeItem(root.At(2, 1, 0), "ERRCODE"); err != nil {
			return out, err
		}

		if out.ERRTEXT, err = decodeASCII(root.At(2, 1, 1), "ERRTEXT"); err != nil {
			return out, err
		}
	}

	return out, nil
}

// S5F17Body is the decoded body of the S5F17 (Exception Recovery Abort Request) message.
//
// Body: A[exid].
//
// It is filled by [DecodeS5F17] and mirrors the parameters of [S5F17], in order.
type S5F17Body struct {
	EXID string
}

// DecodeS5F17 decodes the body of an S5F17 (Exception Recovery Abort Request) message into a [S5F17Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F17Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F17(item secs2.Item) (S5F17Body, error) {
	var out S5F17Body

	var err error

	root := secs2.NewCursor(item)

	if out.EXID, err = decodeASCII(root, "EXID"); err != nil {
		return out, err
	}

	return out, nil
}

// S5F18Reply is the decoded body of the S5F18 (Exception Recovery Abort Acknowledge) message.
//
// Body: L[2]{ A[exid] L[2]{ BOOLEAN[acka] L[0,2]{ <errcode> A[errtext] } } }.
//
// It is filled by [DecodeS5F18] and mirrors the parameters of [S5F18], in order.
type S5F18Reply struct {
	EXID    string
	ACKA    bool
	ERRCODE secs2.Item
	ERRTEXT string
}

// DecodeS5F18 decodes the body of an S5F18 (Exception Recovery Abort Acknowledge) message into a [S5F18Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S5F18Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS5F18(item secs2.Item) (S5F18Reply, error) {
	var out S5F18Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S5F18 body", 2); err != nil {
		return out, err
	}

	if out.EXID, err = decodeASCII(root.At(0), "EXID"); err != nil {
		return out, err
	}

	if err = requireArity(root.At(1), "S5F18 body[1]", 2); err != nil {
		return out, err
	}

	if out.ACKA, err = decodeBool(root.At(1, 0), "ACKA"); err != nil {
		return out, err
	}

	n1, err := optionalArity(root.At(1, 1), "S5F18 body[1][1]", 0, 2)
	if err != nil {
		return out, err
	}

	if n1 == 2 {
		if out.ERRCODE, err = decodeItem(root.At(1, 1, 0), "ERRCODE"); err != nil {
			return out, err
		}

		if out.ERRTEXT, err = decodeASCII(root.At(1, 1, 1), "ERRTEXT"); err != nil {
			return out, err
		}
	}

	return out, nil
}
