// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

func TestDecodeS5F1RoundTrip(t *testing.T) {
	msg := gem.S5F1(0x87, secs2.A("alid"), "altx")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F1(body)
	if err != nil {
		t.Fatalf("DecodeS5F1: %v", err)
	}

	if got.ALCD != 0x87 {
		t.Errorf("ALCD: got %v, want %v", got.ALCD, 0x87)
	}

	if !bytes.Equal(got.ALID.ToBytes(), secs2.A("alid").ToBytes()) {
		t.Errorf("ALID: got %x, want %x", got.ALID.ToBytes(), secs2.A("alid").ToBytes())
	}

	if got.ALTX != "altx" {
		t.Errorf("ALTX: got %v, want %v", got.ALTX, "altx")
	}
}

func TestDecodeS5F2RoundTrip(t *testing.T) {
	msg := gem.S5F2(0xe0)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F2(body)
	if err != nil {
		t.Fatalf("DecodeS5F2: %v", err)
	}

	if got.ACKC5 != 0xe0 {
		t.Errorf("ACKC5: got %v, want %v", got.ACKC5, 0xe0)
	}
}

func TestDecodeS5F3RoundTrip(t *testing.T) {
	msg := gem.S5F3(0x85, secs2.A("alid"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F3(body)
	if err != nil {
		t.Fatalf("DecodeS5F3: %v", err)
	}

	if got.ALED != 0x85 {
		t.Errorf("ALED: got %v, want %v", got.ALED, 0x85)
	}

	if !bytes.Equal(got.ALID.ToBytes(), secs2.A("alid").ToBytes()) {
		t.Errorf("ALID: got %x, want %x", got.ALID.ToBytes(), secs2.A("alid").ToBytes())
	}
}

func TestDecodeS5F4RoundTrip(t *testing.T) {
	msg := gem.S5F4(0xe0)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F4(body)
	if err != nil {
		t.Fatalf("DecodeS5F4: %v", err)
	}

	if got.ACKC5 != 0xe0 {
		t.Errorf("ACKC5: got %v, want %v", got.ACKC5, 0xe0)
	}
}

func TestDecodeS5F5RoundTrip(t *testing.T) {
	msg := gem.S5F5(secs2.A("alids"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F5(body)
	if err != nil {
		t.Fatalf("DecodeS5F5: %v", err)
	}

	if len(got.ALIDS) != 1 {
		t.Fatalf("ALIDS: got %d elements, want 1", len(got.ALIDS))
	}

	if !bytes.Equal(got.ALIDS[0].ToBytes(), secs2.A("alids").ToBytes()) {
		t.Errorf("ALIDS: got %x, want %x", got.ALIDS[0].ToBytes(), secs2.A("alids").ToBytes())
	}
}

func TestDecodeS5F6RoundTrip(t *testing.T) {
	msg := gem.S5F6(secs2.A("alarms"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F6(body)
	if err != nil {
		t.Fatalf("DecodeS5F6: %v", err)
	}

	if len(got.ALARMS) != 1 {
		t.Fatalf("ALARMS: got %d elements, want 1", len(got.ALARMS))
	}

	if !bytes.Equal(got.ALARMS[0].ToBytes(), secs2.A("alarms").ToBytes()) {
		t.Errorf("ALARMS: got %x, want %x", got.ALARMS[0].ToBytes(), secs2.A("alarms").ToBytes())
	}
}

func TestDecodeS5F8RoundTrip(t *testing.T) {
	msg := gem.S5F8(secs2.A("alarms"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F8(body)
	if err != nil {
		t.Fatalf("DecodeS5F8: %v", err)
	}

	if len(got.ALARMS) != 1 {
		t.Fatalf("ALARMS: got %d elements, want 1", len(got.ALARMS))
	}

	if !bytes.Equal(got.ALARMS[0].ToBytes(), secs2.A("alarms").ToBytes()) {
		t.Errorf("ALARMS: got %x, want %x", got.ALARMS[0].ToBytes(), secs2.A("alarms").ToBytes())
	}
}

func TestDecodeS5F9RoundTrip(t *testing.T) {
	msg := gem.S5F9("timestamp", "exid", "extype", "exmessage", secs2.A("recoveryActions"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F9(body)
	if err != nil {
		t.Fatalf("DecodeS5F9: %v", err)
	}

	if got.TIMESTAMP != "timestamp" {
		t.Errorf("TIMESTAMP: got %v, want %v", got.TIMESTAMP, "timestamp")
	}

	if got.EXID != "exid" {
		t.Errorf("EXID: got %v, want %v", got.EXID, "exid")
	}

	if got.EXTYPE != "extype" {
		t.Errorf("EXTYPE: got %v, want %v", got.EXTYPE, "extype")
	}

	if got.EXMESSAGE != "exmessage" {
		t.Errorf("EXMESSAGE: got %v, want %v", got.EXMESSAGE, "exmessage")
	}

	if len(got.RECOVERYACTIONS) != 1 {
		t.Fatalf("RECOVERYACTIONS: got %d elements, want 1", len(got.RECOVERYACTIONS))
	}

	if !bytes.Equal(got.RECOVERYACTIONS[0].ToBytes(), secs2.A("recoveryActions").ToBytes()) {
		t.Errorf("RECOVERYACTIONS: got %x, want %x", got.RECOVERYACTIONS[0].ToBytes(), secs2.A("recoveryActions").ToBytes())
	}
}

func TestDecodeS5F11RoundTrip(t *testing.T) {
	msg := gem.S5F11("timestamp", "exid", "extype", "exmessage")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F11(body)
	if err != nil {
		t.Fatalf("DecodeS5F11: %v", err)
	}

	if got.TIMESTAMP != "timestamp" {
		t.Errorf("TIMESTAMP: got %v, want %v", got.TIMESTAMP, "timestamp")
	}

	if got.EXID != "exid" {
		t.Errorf("EXID: got %v, want %v", got.EXID, "exid")
	}

	if got.EXTYPE != "extype" {
		t.Errorf("EXTYPE: got %v, want %v", got.EXTYPE, "extype")
	}

	if got.EXMESSAGE != "exmessage" {
		t.Errorf("EXMESSAGE: got %v, want %v", got.EXMESSAGE, "exmessage")
	}
}

func TestDecodeS5F13RoundTrip(t *testing.T) {
	msg := gem.S5F13("exid", "exrecvra")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F13(body)
	if err != nil {
		t.Fatalf("DecodeS5F13: %v", err)
	}

	if got.EXID != "exid" {
		t.Errorf("EXID: got %v, want %v", got.EXID, "exid")
	}

	if got.EXRECVRA != "exrecvra" {
		t.Errorf("EXRECVRA: got %v, want %v", got.EXRECVRA, "exrecvra")
	}
}

func TestDecodeS5F14RoundTrip(t *testing.T) {
	msg := gem.S5F14("exid", true, secs2.A("errcode"), "errtext")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F14(body)
	if err != nil {
		t.Fatalf("DecodeS5F14: %v", err)
	}

	if got.EXID != "exid" {
		t.Errorf("EXID: got %v, want %v", got.EXID, "exid")
	}

	if !got.ACKA {
		t.Errorf("ACKA: got %v, want true", got.ACKA)
	}

	if !bytes.Equal(got.ERRCODE.ToBytes(), secs2.A("errcode").ToBytes()) {
		t.Errorf("ERRCODE: got %x, want %x", got.ERRCODE.ToBytes(), secs2.A("errcode").ToBytes())
	}

	if got.ERRTEXT != "errtext" {
		t.Errorf("ERRTEXT: got %v, want %v", got.ERRTEXT, "errtext")
	}
}

func TestDecodeS5F15RoundTrip(t *testing.T) {
	msg := gem.S5F15("timestamp", "exid", true, secs2.A("errcode"), "errtext")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F15(body)
	if err != nil {
		t.Fatalf("DecodeS5F15: %v", err)
	}

	if got.TIMESTAMP != "timestamp" {
		t.Errorf("TIMESTAMP: got %v, want %v", got.TIMESTAMP, "timestamp")
	}

	if got.EXID != "exid" {
		t.Errorf("EXID: got %v, want %v", got.EXID, "exid")
	}

	if !got.ACKA {
		t.Errorf("ACKA: got %v, want true", got.ACKA)
	}

	if !bytes.Equal(got.ERRCODE.ToBytes(), secs2.A("errcode").ToBytes()) {
		t.Errorf("ERRCODE: got %x, want %x", got.ERRCODE.ToBytes(), secs2.A("errcode").ToBytes())
	}

	if got.ERRTEXT != "errtext" {
		t.Errorf("ERRTEXT: got %v, want %v", got.ERRTEXT, "errtext")
	}
}

func TestDecodeS5F17RoundTrip(t *testing.T) {
	msg := gem.S5F17("exid")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F17(body)
	if err != nil {
		t.Fatalf("DecodeS5F17: %v", err)
	}

	if got.EXID != "exid" {
		t.Errorf("EXID: got %v, want %v", got.EXID, "exid")
	}
}

func TestDecodeS5F18RoundTrip(t *testing.T) {
	msg := gem.S5F18("exid", true, secs2.A("errcode"), "errtext")

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS5F18(body)
	if err != nil {
		t.Fatalf("DecodeS5F18: %v", err)
	}

	if got.EXID != "exid" {
		t.Errorf("EXID: got %v, want %v", got.EXID, "exid")
	}

	if !got.ACKA {
		t.Errorf("ACKA: got %v, want true", got.ACKA)
	}

	if !bytes.Equal(got.ERRCODE.ToBytes(), secs2.A("errcode").ToBytes()) {
		t.Errorf("ERRCODE: got %x, want %x", got.ERRCODE.ToBytes(), secs2.A("errcode").ToBytes())
	}

	if got.ERRTEXT != "errtext" {
		t.Errorf("ERRTEXT: got %v, want %v", got.ERRTEXT, "errtext")
	}
}
