// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

// assertS5Header checks that msg is an S5 message with the given function code and wait bit.
func assertS5Header(t *testing.T, msg secs2.SECS2Message, function uint8, wantW bool) {
	t.Helper()

	if msg.StreamCode() != 5 {
		t.Errorf("StreamCode: got %d, want 5", msg.StreamCode())
	}

	if msg.FunctionCode() != function {
		t.Errorf("FunctionCode: got %d, want %d", msg.FunctionCode(), function)
	}

	if msg.WaitBit() != wantW {
		t.Errorf("WaitBit: got %v, want %v", msg.WaitBit(), wantW)
	}
}

func TestS5F1(t *testing.T) {
	msg := gem.S5F1(0x87, secs2.A("alid"), "altx")

	assertS5Header(t, msg, 1, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0x87 {
		t.Errorf("alcd: got %v, want %v", v2, 0x87)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("alid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("alid: got %x, want %x", got3, want3)
	}
	v4, err := list1[2].ToASCII()
	if err != nil {
		t.Fatalf("list1[2].ToASCII: %v", err)
	}
	if v4 != "altx" {
		t.Errorf("altx: got %q, want %q", v4, "altx")
	}
}

func TestS5F2(t *testing.T) {
	msg := gem.S5F2(0xe0)

	assertS5Header(t, msg, 2, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xe0 {
		t.Errorf("ackc5: got %v, want %v", v1, 0xe0)
	}
}

func TestS5F3(t *testing.T) {
	msg := gem.S5F3(0x85, secs2.A("alid"))

	assertS5Header(t, msg, 3, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0x85 {
		t.Errorf("aled: got %v, want %v", v2, 0x85)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("alid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("alid: got %x, want %x", got3, want3)
	}
}

func TestS5F4(t *testing.T) {
	msg := gem.S5F4(0xe0)

	assertS5Header(t, msg, 4, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0xe0 {
		t.Errorf("ackc5: got %v, want %v", v1, 0xe0)
	}
}

func TestS5F5(t *testing.T) {
	msg := gem.S5F5(secs2.A("alids"))

	assertS5Header(t, msg, 5, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("alids").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("alids: got %x, want %x", got2, want2)
	}
}

func TestS5F6(t *testing.T) {
	msg := gem.S5F6(secs2.A("alarms"))

	assertS5Header(t, msg, 6, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("alarms").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("alarms: got %x, want %x", got2, want2)
	}
}

func TestS5F7(t *testing.T) {
	msg := gem.S5F7()

	assertS5Header(t, msg, 7, true)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS5F8(t *testing.T) {
	msg := gem.S5F8(secs2.A("alarms"))

	assertS5Header(t, msg, 8, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("alarms").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("alarms: got %x, want %x", got2, want2)
	}
}

func TestS5F9(t *testing.T) {
	msg := gem.S5F9("timestamp", "exid", "extype", "exmessage", secs2.A("recovery_actions"))

	assertS5Header(t, msg, 9, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 5 {
		t.Fatalf("list length: got %d, want 5", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "timestamp" {
		t.Errorf("timestamp: got %q, want %q", v2, "timestamp")
	}
	v3, err := list1[1].ToASCII()
	if err != nil {
		t.Fatalf("list1[1].ToASCII: %v", err)
	}
	if v3 != "exid" {
		t.Errorf("exid: got %q, want %q", v3, "exid")
	}
	v4, err := list1[2].ToASCII()
	if err != nil {
		t.Fatalf("list1[2].ToASCII: %v", err)
	}
	if v4 != "extype" {
		t.Errorf("extype: got %q, want %q", v4, "extype")
	}
	v5, err := list1[3].ToASCII()
	if err != nil {
		t.Fatalf("list1[3].ToASCII: %v", err)
	}
	if v5 != "exmessage" {
		t.Errorf("exmessage: got %q, want %q", v5, "exmessage")
	}
	list6, err := list1[4].ToList()
	if err != nil {
		t.Fatalf("list1[4].ToList: %v", err)
	}
	if len(list6) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list6))
	}
	got7 := list6[0].ToBytes()
	want7 := secs2.A("recovery_actions").ToBytes()
	if !bytes.Equal(got7, want7) {
		t.Errorf("recovery_actions: got %x, want %x", got7, want7)
	}
}

func TestS5F10(t *testing.T) {
	msg := gem.S5F10()

	assertS5Header(t, msg, 10, false)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS5F11(t *testing.T) {
	msg := gem.S5F11("timestamp", "exid", "extype", "exmessage")

	assertS5Header(t, msg, 11, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 4 {
		t.Fatalf("list length: got %d, want 4", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "timestamp" {
		t.Errorf("timestamp: got %q, want %q", v2, "timestamp")
	}
	v3, err := list1[1].ToASCII()
	if err != nil {
		t.Fatalf("list1[1].ToASCII: %v", err)
	}
	if v3 != "exid" {
		t.Errorf("exid: got %q, want %q", v3, "exid")
	}
	v4, err := list1[2].ToASCII()
	if err != nil {
		t.Fatalf("list1[2].ToASCII: %v", err)
	}
	if v4 != "extype" {
		t.Errorf("extype: got %q, want %q", v4, "extype")
	}
	v5, err := list1[3].ToASCII()
	if err != nil {
		t.Fatalf("list1[3].ToASCII: %v", err)
	}
	if v5 != "exmessage" {
		t.Errorf("exmessage: got %q, want %q", v5, "exmessage")
	}
}

func TestS5F12(t *testing.T) {
	msg := gem.S5F12()

	assertS5Header(t, msg, 12, false)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS5F13(t *testing.T) {
	msg := gem.S5F13("exid", "exrecvra")

	assertS5Header(t, msg, 13, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "exid" {
		t.Errorf("exid: got %q, want %q", v2, "exid")
	}
	v3, err := list1[1].ToASCII()
	if err != nil {
		t.Fatalf("list1[1].ToASCII: %v", err)
	}
	if v3 != "exrecvra" {
		t.Errorf("exrecvra: got %q, want %q", v3, "exrecvra")
	}
}

func TestS5F14(t *testing.T) {
	msg := gem.S5F14("exid", true, secs2.A("errcode"), "errtext")

	assertS5Header(t, msg, 14, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "exid" {
		t.Errorf("exid: got %q, want %q", v2, "exid")
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list3))
	}
	v4, err := list3[0].ToBoolean()
	if err != nil {
		t.Fatalf("list3[0].ToBoolean: %v", err)
	}
	if len(v4) != 1 || v4[0] != true {
		t.Errorf("acka: got %v, want %v", v4, true)
	}
	list5, err := list3[1].ToList()
	if err != nil {
		t.Fatalf("list3[1].ToList: %v", err)
	}
	if len(list5) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list5))
	}
	got6 := list5[0].ToBytes()
	want6 := secs2.A("errcode").ToBytes()
	if !bytes.Equal(got6, want6) {
		t.Errorf("errcode: got %x, want %x", got6, want6)
	}
	v7, err := list5[1].ToASCII()
	if err != nil {
		t.Fatalf("list5[1].ToASCII: %v", err)
	}
	if v7 != "errtext" {
		t.Errorf("errtext: got %q, want %q", v7, "errtext")
	}
}

func TestS5F15(t *testing.T) {
	msg := gem.S5F15("timestamp", "exid", true, secs2.A("errcode"), "errtext")

	assertS5Header(t, msg, 15, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "timestamp" {
		t.Errorf("timestamp: got %q, want %q", v2, "timestamp")
	}
	v3, err := list1[1].ToASCII()
	if err != nil {
		t.Fatalf("list1[1].ToASCII: %v", err)
	}
	if v3 != "exid" {
		t.Errorf("exid: got %q, want %q", v3, "exid")
	}
	list4, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list4) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list4))
	}
	v5, err := list4[0].ToBoolean()
	if err != nil {
		t.Fatalf("list4[0].ToBoolean: %v", err)
	}
	if len(v5) != 1 || v5[0] != true {
		t.Errorf("acka: got %v, want %v", v5, true)
	}
	list6, err := list4[1].ToList()
	if err != nil {
		t.Fatalf("list4[1].ToList: %v", err)
	}
	if len(list6) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list6))
	}
	got7 := list6[0].ToBytes()
	want7 := secs2.A("errcode").ToBytes()
	if !bytes.Equal(got7, want7) {
		t.Errorf("errcode: got %x, want %x", got7, want7)
	}
	v8, err := list6[1].ToASCII()
	if err != nil {
		t.Fatalf("list6[1].ToASCII: %v", err)
	}
	if v8 != "errtext" {
		t.Errorf("errtext: got %q, want %q", v8, "errtext")
	}
}

func TestS5F16(t *testing.T) {
	msg := gem.S5F16()

	assertS5Header(t, msg, 16, false)

	if !msg.Item().IsEmpty() {
		t.Errorf("item type: got %s, want empty", msg.Item().Type())
	}
}

func TestS5F17(t *testing.T) {
	msg := gem.S5F17("exid")

	assertS5Header(t, msg, 17, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToASCII()
	if err != nil {
		t.Fatalf("decoded.ToASCII: %v", err)
	}
	if v1 != "exid" {
		t.Errorf("exid: got %q, want %q", v1, "exid")
	}
}

func TestS5F18(t *testing.T) {
	msg := gem.S5F18("exid", true, secs2.A("errcode"), "errtext")

	assertS5Header(t, msg, 18, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "exid" {
		t.Errorf("exid: got %q, want %q", v2, "exid")
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list3))
	}
	v4, err := list3[0].ToBoolean()
	if err != nil {
		t.Fatalf("list3[0].ToBoolean: %v", err)
	}
	if len(v4) != 1 || v4[0] != true {
		t.Errorf("acka: got %v, want %v", v4, true)
	}
	list5, err := list3[1].ToList()
	if err != nil {
		t.Fatalf("list3[1].ToList: %v", err)
	}
	if len(list5) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list5))
	}
	got6 := list5[0].ToBytes()
	want6 := secs2.A("errcode").ToBytes()
	if !bytes.Equal(got6, want6) {
		t.Errorf("errcode: got %x, want %x", got6, want6)
	}
	v7, err := list5[1].ToASCII()
	if err != nil {
		t.Fatalf("list5[1].ToASCII: %v", err)
	}
	if v7 != "errtext" {
		t.Errorf("errtext: got %q, want %q", v7, "errtext")
	}
}
