// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S6F1 creates the S6F1 (Trace Data Send) message, direction: equipment-to-host.
//
// This function sends samples to the host according to the trace setup done by S2F23. Trace is a time-driven form of equipment status. Even if S6F1 is multi-block, it is not preceded by an Inquire/Grant transaction, because the host S2F23 is an implicit grant. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[4]{ <trid> <smpln> A[stime] L[n]{ <samples>... } }.
//
// Exception: A zero-length STIME means no value is given and the time is to be derived from SMPLN along with knowledge of the request.
func S6F1(trid secs2.Item, smpln secs2.Item, stime string, samples ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 1, true, secs2.L(trid, smpln, secs2.A(stime), secs2.L(samples...)))
}

// S6F2 creates the S6F2 (Trace Data Acknowledge) message, direction: host-to-equipment.
//
// Acknowledge or error.
//
// Body: B[ackc6].
//
// Exception: None.
func S6F2(ackc6 ACKC6) secs2.SECS2Message {
	return secs2.NewMessage(6, 2, false, secs2.B(byte(ackc6)))
}

// S6F3 creates the S6F3 (Discrete Variable Data Send) message, direction: equipment-to-host.
//
// Any data report initiated by an event, such as the completion of a measurement, rather than by the passage of time is called a discrete variable. S2F15 selects the desired reporting events. Reports requiring only one block of data may report directly to the host with this message. If S6F3 is multi-block, it must be preceded by the S6F5/S6F6 Inquire/Grant transaction. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// Exception: None.
func S6F3(dataid secs2.Item, ceid secs2.Item, reports ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 3, true, secs2.L(dataid, ceid, secs2.L(reports...)))
}

// S6F4 creates the S6F4 (Discrete Variable Data Acknowledge) message, direction: host-to-equipment.
//
// Acknowledge or error.
//
// Body: B[ackc6].
//
// Exception: None.
func S6F4(ackc6 ACKC6) secs2.SECS2Message {
	return secs2.NewMessage(6, 4, false, secs2.B(byte(ackc6)))
}

// S6F5 creates the S6F5 (Multi-block Data Send Inquire) message, direction: equipment-to-host.
//
// If the discrete data report S6F3, S6F9, S6F11, or S6F13 can involve more than one block, this transaction must precede the transmission.
//
// Body: L[2]{ <dataid> <datalength> }.
//
// Exception: None.
func S6F5(dataid secs2.Item, datalength secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 5, true, secs2.L(dataid, datalength))
}

// S6F6 creates the S6F6 (Multi-block Grant) message, direction: host-to-equipment.
//
// Grant permission to send.
//
// Body: B[grant6].
//
// Exception: None.
func S6F6(grant6 byte) secs2.SECS2Message {
	return secs2.NewMessage(6, 6, false, secs2.B(grant6))
}

// S6F7 creates the S6F7 (Data Transfer Request) message, direction: host-to-equipment.
//
// The host may initiate a data transfer of specified data stored in the equipment with this function.
//
// Body: <dataid>.
//
// Exception: None.
func S6F7(dataid secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 7, true, dataid)
}

// S6F8 creates the S6F8 (Data Transfer Data) message, direction: equipment-to-host.
//
// Equipment sends data to the host. The structure is the same as S6F3.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// Exception: A zero-length item returned means the requested data cannot be sent.
func S6F8(dataid secs2.Item, ceid secs2.Item, reports ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 8, false, secs2.L(dataid, ceid, secs2.L(reports...)))
}

// S6F9 creates the S6F9 (Formatted Variable Send) message, direction: equipment-to-host.
//
// The same function as S6F3 except that the DVNAMEs are supplied from a predefined form known to the host, so the data are more compact. If S6F9 is multi-block, it must be preceded by the S6F5/S6F6 Inquire/Grant transaction. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[4]{ B[pfcd] <dataid> <ceid> L[n]{ <reports>... } }.
//
// Exception: None.
func S6F9(pfcd byte, dataid secs2.Item, ceid secs2.Item, reports ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 9, true, secs2.L(secs2.B(pfcd), dataid, ceid, secs2.L(reports...)))
}

// S6F10 creates the S6F10 (Formatted Variable Acknowledge) message, direction: host-to-equipment.
//
// Acknowledge or error.
//
// Body: B[ackc6].
//
// Exception: None.
func S6F10(ackc6 ACKC6) secs2.SECS2Message {
	return secs2.NewMessage(6, 10, false, secs2.B(byte(ackc6)))
}

// S6F11 creates the S6F11 (Event Report Send) message, direction: equipment-to-host.
//
// The purpose of this message is for the equipment to send a defined, linked, and enabled group of reports to the host upon the occurrence of an event (CEID). If S6F11 is multi-block, it must be preceded by the S6F5/S6F6 Inquire/Grant transaction. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// Exception: If there are no reports linked to the event a 'null' report is assumed. A zero-length list for the report count means there are no reports linked to the given CEID.
func S6F11(dataid secs2.Item, ceid secs2.Item, reports ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 11, true, secs2.L(dataid, ceid, secs2.L(reports...)))
}

// S6F12 creates the S6F12 (Event Report Acknowledge) message, direction: host-to-equipment.
//
// Acknowledge or error.
//
// Body: B[ackc6].
//
// Exception: None.
func S6F12(ackc6 ACKC6) secs2.SECS2Message {
	return secs2.NewMessage(6, 12, false, secs2.B(byte(ackc6)))
}

// S6F13 creates the S6F13 (Annotated Event Report Send) message, direction: equipment-to-host.
//
// The purpose of this message is for the equipment to send a defined, linked, and enabled group of reports to the host upon the occurrence of an event (CEID), with each variable value annotated by its VID. This is the annotated form of S6F11.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// Exception: If there are no reports linked to the event a 'null' report is assumed. A zero-length list for the report count means there are no reports linked to the given CEID.
//
// Source: reconstructed from an external reference, not verified against the purchased SEMI standard.
func S6F13(dataid secs2.Item, ceid secs2.Item, reports ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 13, true, secs2.L(dataid, ceid, secs2.L(reports...)))
}

// S6F14 creates the S6F14 (Annotated Event Report Acknowledge) message, direction: host-to-equipment.
//
// Acknowledge or error.
//
// Body: B[ackc6].
//
// Exception: None.
func S6F14(ackc6 ACKC6) secs2.SECS2Message {
	return secs2.NewMessage(6, 14, false, secs2.B(byte(ackc6)))
}

// S6F15 creates the S6F15 (Event Report Request) message, direction: host-to-equipment.
//
// The purpose of this message is for the host to demand a given report group from the equipment.
//
// Body: <ceid>.
//
// Exception: None.
func S6F15(ceid secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 15, true, ceid)
}

// S6F16 creates the S6F16 (Event Report Data) message, direction: equipment-to-host.
//
// Equipment sends the reports linked to the given CEID to the host. The structure is identical to S6F11.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// Exception: A zero-length item means there are no reports linked to the given CEID.
func S6F16(dataid secs2.Item, ceid secs2.Item, reports ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 16, false, secs2.L(dataid, ceid, secs2.L(reports...)))
}

// S6F17 creates the S6F17 (Annotated Event Report Request) message, direction: host-to-equipment.
//
// Same as S6F15, but requests annotated reports.
//
// Body: <ceid>.
//
// Exception: None.
func S6F17(ceid secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 17, true, ceid)
}

// S6F18 creates the S6F18 (Annotated Event Report Data) message, direction: equipment-to-host.
//
// Equipment sends the annotated reports linked to the given CEID. The structure is the same as S6F13.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// Exception: A zero-length item means there are no reports linked to the given CEID.
func S6F18(dataid secs2.Item, ceid secs2.Item, reports ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 18, false, secs2.L(dataid, ceid, secs2.L(reports...)))
}

// S6F19 creates the S6F19 (Individual Report Request) message, direction: host-to-equipment.
//
// The purpose of this message is for the host to request a defined report from the equipment.
//
// Body: <rptid>.
//
// Exception: None.
func S6F19(rptid secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 19, true, rptid)
}

// S6F20 creates the S6F20 (Individual Report Data) message, direction: equipment-to-host.
//
// Equipment sends the variable data defined for the given RPTID to the host.
//
// Body: L[n]{ <values>... }.
//
// Exception: None.
func S6F20(values ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 20, false, secs2.L(values...))
}

// S6F21 creates the S6F21 (Annotated Individual Report Request) message, direction: host-to-equipment.
//
// The purpose of this message is for the host to request an annotated defined report from the equipment.
//
// Body: <rptid>.
//
// Exception: None.
func S6F21(rptid secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 21, true, rptid)
}

// S6F22 creates the S6F22 (Annotated Individual Report Data) message, direction: equipment-to-host.
//
// Equipment sends the annotated variable data defined for the given RPTID to the host.
//
// Body: L[n]{ <values>... }.
//
// Exception: A zero-length list for the variable-data-item count means the RPTID is not defined.
func S6F22(values ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 22, false, secs2.L(values...))
}

// S6F23 creates the S6F23 (Request Spooled Data) message, direction: host-to-equipment.
//
// The purpose of this message is for the host to request transmission or deletion of the messages currently spooled by the equipment.
//
// Body: U1[rsdc].
//
// Exception: None.
func S6F23(rsdc uint8) secs2.SECS2Message {
	return secs2.NewMessage(6, 23, true, secs2.U1(rsdc))
}

// S6F24 creates the S6F24 (Request Spooled Data Acknowledgement Send) message, direction: equipment-to-host.
//
// The purpose of this message is to acknowledge the receipt of the Request Spooled Data (S6F23) and to respond with an appropriate acknowledge code.
//
// Body: B[rsda].
//
// Exception: None.
func S6F24(rsda RSDA) secs2.SECS2Message {
	return secs2.NewMessage(6, 24, false, secs2.B(byte(rsda)))
}

// S6F25 creates the S6F25 (Notification Report Send) message, direction: bidirectional.
//
// This message is used for change notifications or confirmation reports. A change notification is a report of an internal action not associated with a prior host request. A confirmation report is always associated with an earlier request for action and is sent to the initial requestor of a delayed action at the time the action completes. OPID contains the value of OPID in the initial request. LINKID is set to a non-zero value if and only if additional completion reports with the same OPID will be sent. If S6F25 is multi-block, it must be preceded by the S6F5/S6F6 Inquire/Grant transaction. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[7]{ <dataid> <opid> U4[linkid] A[rcpspec] <rmchgstat> L[n]{ <attributes>... } L[2]{ U1[rmack] L[n]{ <errors>... } } }.
//
// Exception: OPID and LINKID are zero-length items when and only when S6F25 is sent as a change notification rather than as a confirmation report. p = 0 if and only if RMACK indicates no errors.
func S6F25(dataid secs2.Item, opid secs2.Item, linkid uint32, rcpspec string, rmchgstat secs2.Item, attributes []secs2.Item, rmack RMACK, errors ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 25, true, secs2.L(dataid, opid, secs2.U4(linkid), secs2.A(rcpspec), rmchgstat, secs2.L(attributes...), secs2.L(secs2.U1(uint8(rmack)), secs2.L(errors...))))
}

// S6F26 creates the S6F26 (Notification Report Send Acknowledge) message, direction: bidirectional.
//
// This message is used to acknowledge the confirmation report. It is defined for completeness and as an aid to the user in identifying problems.
//
// Body: B[ackc6].
//
// Exception: None.
func S6F26(ackc6 ACKC6) secs2.SECS2Message {
	return secs2.NewMessage(6, 26, false, secs2.B(byte(ackc6)))
}

// S6F27 creates the S6F27 (Trace Report Send) message, direction: equipment-to-host.
//
// The equipment sends a completed Trace Report to the host. The outer list carries up to the trace group size specified by S2F53 samples; each sample carries one entry per report, and each report pairs its RPTID with the list of variable values for that report. Callers that require a no-reply variant should use [secs2.NewMessage] directly.
//
// Body: L[3]{ <dataid> <trid> L[n]{ <samples>... } }.
//
// Exception: The list of variables associated with each unique RPTID is itself unique; this structure illustrates the form of the message only, so in general V1 for one RPTID and V1 for another do not reference the same variable.
func S6F27(dataid secs2.Item, trid secs2.Item, samples ...secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 27, true, secs2.L(dataid, trid, secs2.L(samples...)))
}

// S6F28 creates the S6F28 (Trace Report Send Acknowledge) message, direction: host-to-equipment.
//
// The host acknowledges receipt of the Trace Report.
//
// Body: <trid>.
//
// Exception: None.
func S6F28(trid secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 28, false, trid)
}

// S6F29 creates the S6F29 (Trace Report Request) message, direction: host-to-equipment.
//
// Request that the data reports assigned to the trace report be sampled and returned to the host.
//
// Body: <trid>.
//
// Exception: None.
func S6F29(trid secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 29, false, trid)
}

// S6F30 creates the S6F30 (Trace Report Data) message, direction: equipment-to-host.
//
// Message containing the requested data reports associated with the TRID of a trace data report definition.
//
// Body: L[3]{ <trid> L[n]{ <reports>... } <errcode> }.
//
// Exception: If TRID is unknown, a zero-length list (n = 0) is sent. ERRCODE is set to zero length when there is no error.
func S6F30(trid secs2.Item, reports []secs2.Item, errcode secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(6, 30, false, secs2.L(trid, secs2.L(reports...), errcode))
}
