// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S6F1Body is the decoded body of the S6F1 (Trace Data Send) message.
//
// Body: L[4]{ <trid> <smpln> A[stime] L[n]{ <samples>... } }.
//
// It is filled by [DecodeS6F1] and mirrors the parameters of [S6F1], in order.
type S6F1Body struct {
	TRID    secs2.Item
	SMPLN   secs2.Item
	STIME   string
	SAMPLES []secs2.Item
}

// DecodeS6F1 decodes the body of an S6F1 (Trace Data Send) message into a [S6F1Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F1Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F1(item secs2.Item) (S6F1Body, error) {
	var out S6F1Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F1 body", 4); err != nil {
		return out, err
	}

	if out.TRID, err = decodeItem(root.At(0), "TRID"); err != nil {
		return out, err
	}

	if out.SMPLN, err = decodeItem(root.At(1), "SMPLN"); err != nil {
		return out, err
	}

	if out.STIME, err = decodeASCII(root.At(2), "STIME"); err != nil {
		return out, err
	}

	if out.SAMPLES, err = decodeItems(root.At(3), "SAMPLES"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F2Reply is the decoded body of the S6F2 (Trace Data Acknowledge) message.
//
// Body: B[ackc6].
//
// It is filled by [DecodeS6F2] and mirrors the parameters of [S6F2], in order.
type S6F2Reply struct {
	ACKC6 ACKC6
}

// DecodeS6F2 decodes the body of an S6F2 (Trace Data Acknowledge) message into a [S6F2Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F2Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F2(item secs2.Item) (S6F2Reply, error) {
	var out S6F2Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ACKC6, err = decodeByteAs[ACKC6](root, "ACKC6"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F3Body is the decoded body of the S6F3 (Discrete Variable Data Send) message.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// It is filled by [DecodeS6F3] and mirrors the parameters of [S6F3], in order.
type S6F3Body struct {
	DATAID  secs2.Item
	CEID    secs2.Item
	REPORTS []secs2.Item
}

// DecodeS6F3 decodes the body of an S6F3 (Discrete Variable Data Send) message into a [S6F3Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F3Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F3(item secs2.Item) (S6F3Body, error) {
	var out S6F3Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F3 body", 3); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.CEID, err = decodeItem(root.At(1), "CEID"); err != nil {
		return out, err
	}

	if out.REPORTS, err = decodeItems(root.At(2), "REPORTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F4Reply is the decoded body of the S6F4 (Discrete Variable Data Acknowledge) message.
//
// Body: B[ackc6].
//
// It is filled by [DecodeS6F4] and mirrors the parameters of [S6F4], in order.
type S6F4Reply struct {
	ACKC6 ACKC6
}

// DecodeS6F4 decodes the body of an S6F4 (Discrete Variable Data Acknowledge) message into a [S6F4Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F4Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F4(item secs2.Item) (S6F4Reply, error) {
	var out S6F4Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ACKC6, err = decodeByteAs[ACKC6](root, "ACKC6"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F5Body is the decoded body of the S6F5 (Multi-block Data Send Inquire) message.
//
// Body: L[2]{ <dataid> <datalength> }.
//
// It is filled by [DecodeS6F5] and mirrors the parameters of [S6F5], in order.
type S6F5Body struct {
	DATAID     secs2.Item
	DATALENGTH secs2.Item
}

// DecodeS6F5 decodes the body of an S6F5 (Multi-block Data Send Inquire) message into a [S6F5Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F5Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F5(item secs2.Item) (S6F5Body, error) {
	var out S6F5Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F5 body", 2); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.DATALENGTH, err = decodeItem(root.At(1), "DATALENGTH"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F6Reply is the decoded body of the S6F6 (Multi-block Grant) message.
//
// Body: B[grant6].
//
// It is filled by [DecodeS6F6] and mirrors the parameters of [S6F6], in order.
type S6F6Reply struct {
	GRANT6 byte
}

// DecodeS6F6 decodes the body of an S6F6 (Multi-block Grant) message into a [S6F6Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F6Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F6(item secs2.Item) (S6F6Reply, error) {
	var out S6F6Reply

	var err error

	root := secs2.NewCursor(item)

	if out.GRANT6, err = decodeByteAs[byte](root, "GRANT6"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F7Body is the decoded body of the S6F7 (Data Transfer Request) message.
//
// Body: <dataid>.
//
// It is filled by [DecodeS6F7] and mirrors the parameters of [S6F7], in order.
type S6F7Body struct {
	DATAID secs2.Item
}

// DecodeS6F7 decodes the body of an S6F7 (Data Transfer Request) message into a [S6F7Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F7Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F7(item secs2.Item) (S6F7Body, error) {
	var out S6F7Body

	var err error

	root := secs2.NewCursor(item)

	if out.DATAID, err = decodeItem(root, "DATAID"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F8Reply is the decoded body of the S6F8 (Data Transfer Data) message.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// It is filled by [DecodeS6F8] and mirrors the parameters of [S6F8], in order.
type S6F8Reply struct {
	DATAID  secs2.Item
	CEID    secs2.Item
	REPORTS []secs2.Item
}

// DecodeS6F8 decodes the body of an S6F8 (Data Transfer Data) message into a [S6F8Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F8Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F8(item secs2.Item) (S6F8Reply, error) {
	var out S6F8Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F8 body", 3); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.CEID, err = decodeItem(root.At(1), "CEID"); err != nil {
		return out, err
	}

	if out.REPORTS, err = decodeItems(root.At(2), "REPORTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F9Body is the decoded body of the S6F9 (Formatted Variable Send) message.
//
// Body: L[4]{ B[pfcd] <dataid> <ceid> L[n]{ <reports>... } }.
//
// It is filled by [DecodeS6F9] and mirrors the parameters of [S6F9], in order.
type S6F9Body struct {
	PFCD    byte
	DATAID  secs2.Item
	CEID    secs2.Item
	REPORTS []secs2.Item
}

// DecodeS6F9 decodes the body of an S6F9 (Formatted Variable Send) message into a [S6F9Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F9Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F9(item secs2.Item) (S6F9Body, error) {
	var out S6F9Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F9 body", 4); err != nil {
		return out, err
	}

	if out.PFCD, err = decodeByteAs[byte](root.At(0), "PFCD"); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(1), "DATAID"); err != nil {
		return out, err
	}

	if out.CEID, err = decodeItem(root.At(2), "CEID"); err != nil {
		return out, err
	}

	if out.REPORTS, err = decodeItems(root.At(3), "REPORTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F10Reply is the decoded body of the S6F10 (Formatted Variable Acknowledge) message.
//
// Body: B[ackc6].
//
// It is filled by [DecodeS6F10] and mirrors the parameters of [S6F10], in order.
type S6F10Reply struct {
	ACKC6 ACKC6
}

// DecodeS6F10 decodes the body of an S6F10 (Formatted Variable Acknowledge) message into a [S6F10Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F10Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F10(item secs2.Item) (S6F10Reply, error) {
	var out S6F10Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ACKC6, err = decodeByteAs[ACKC6](root, "ACKC6"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F11Body is the decoded body of the S6F11 (Event Report Send) message.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// It is filled by [DecodeS6F11] and mirrors the parameters of [S6F11], in order.
type S6F11Body struct {
	DATAID  secs2.Item
	CEID    secs2.Item
	REPORTS []secs2.Item
}

// DecodeS6F11 decodes the body of an S6F11 (Event Report Send) message into a [S6F11Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F11Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F11(item secs2.Item) (S6F11Body, error) {
	var out S6F11Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F11 body", 3); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.CEID, err = decodeItem(root.At(1), "CEID"); err != nil {
		return out, err
	}

	if out.REPORTS, err = decodeItems(root.At(2), "REPORTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F12Reply is the decoded body of the S6F12 (Event Report Acknowledge) message.
//
// Body: B[ackc6].
//
// It is filled by [DecodeS6F12] and mirrors the parameters of [S6F12], in order.
type S6F12Reply struct {
	ACKC6 ACKC6
}

// DecodeS6F12 decodes the body of an S6F12 (Event Report Acknowledge) message into a [S6F12Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F12Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F12(item secs2.Item) (S6F12Reply, error) {
	var out S6F12Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ACKC6, err = decodeByteAs[ACKC6](root, "ACKC6"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F13Body is the decoded body of the S6F13 (Annotated Event Report Send) message.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// It is filled by [DecodeS6F13] and mirrors the parameters of [S6F13], in order.
//
// Source: reconstructed from an external reference, not verified against the purchased SEMI standard.
type S6F13Body struct {
	DATAID  secs2.Item
	CEID    secs2.Item
	REPORTS []secs2.Item
}

// DecodeS6F13 decodes the body of an S6F13 (Annotated Event Report Send) message into a [S6F13Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F13Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
//
// Source: reconstructed from an external reference, not verified against the purchased SEMI standard.
func DecodeS6F13(item secs2.Item) (S6F13Body, error) {
	var out S6F13Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F13 body", 3); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.CEID, err = decodeItem(root.At(1), "CEID"); err != nil {
		return out, err
	}

	if out.REPORTS, err = decodeItems(root.At(2), "REPORTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F14Reply is the decoded body of the S6F14 (Annotated Event Report Acknowledge) message.
//
// Body: B[ackc6].
//
// It is filled by [DecodeS6F14] and mirrors the parameters of [S6F14], in order.
type S6F14Reply struct {
	ACKC6 ACKC6
}

// DecodeS6F14 decodes the body of an S6F14 (Annotated Event Report Acknowledge) message into a [S6F14Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F14Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F14(item secs2.Item) (S6F14Reply, error) {
	var out S6F14Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ACKC6, err = decodeByteAs[ACKC6](root, "ACKC6"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F15Body is the decoded body of the S6F15 (Event Report Request) message.
//
// Body: <ceid>.
//
// It is filled by [DecodeS6F15] and mirrors the parameters of [S6F15], in order.
type S6F15Body struct {
	CEID secs2.Item
}

// DecodeS6F15 decodes the body of an S6F15 (Event Report Request) message into a [S6F15Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F15Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F15(item secs2.Item) (S6F15Body, error) {
	var out S6F15Body

	var err error

	root := secs2.NewCursor(item)

	if out.CEID, err = decodeItem(root, "CEID"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F16Reply is the decoded body of the S6F16 (Event Report Data) message.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// It is filled by [DecodeS6F16] and mirrors the parameters of [S6F16], in order.
type S6F16Reply struct {
	DATAID  secs2.Item
	CEID    secs2.Item
	REPORTS []secs2.Item
}

// DecodeS6F16 decodes the body of an S6F16 (Event Report Data) message into a [S6F16Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F16Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F16(item secs2.Item) (S6F16Reply, error) {
	var out S6F16Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F16 body", 3); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.CEID, err = decodeItem(root.At(1), "CEID"); err != nil {
		return out, err
	}

	if out.REPORTS, err = decodeItems(root.At(2), "REPORTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F17Body is the decoded body of the S6F17 (Annotated Event Report Request) message.
//
// Body: <ceid>.
//
// It is filled by [DecodeS6F17] and mirrors the parameters of [S6F17], in order.
type S6F17Body struct {
	CEID secs2.Item
}

// DecodeS6F17 decodes the body of an S6F17 (Annotated Event Report Request) message into a [S6F17Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F17Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F17(item secs2.Item) (S6F17Body, error) {
	var out S6F17Body

	var err error

	root := secs2.NewCursor(item)

	if out.CEID, err = decodeItem(root, "CEID"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F18Reply is the decoded body of the S6F18 (Annotated Event Report Data) message.
//
// Body: L[3]{ <dataid> <ceid> L[n]{ <reports>... } }.
//
// It is filled by [DecodeS6F18] and mirrors the parameters of [S6F18], in order.
type S6F18Reply struct {
	DATAID  secs2.Item
	CEID    secs2.Item
	REPORTS []secs2.Item
}

// DecodeS6F18 decodes the body of an S6F18 (Annotated Event Report Data) message into a [S6F18Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F18Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F18(item secs2.Item) (S6F18Reply, error) {
	var out S6F18Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F18 body", 3); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.CEID, err = decodeItem(root.At(1), "CEID"); err != nil {
		return out, err
	}

	if out.REPORTS, err = decodeItems(root.At(2), "REPORTS"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F19Body is the decoded body of the S6F19 (Individual Report Request) message.
//
// Body: <rptid>.
//
// It is filled by [DecodeS6F19] and mirrors the parameters of [S6F19], in order.
type S6F19Body struct {
	RPTID secs2.Item
}

// DecodeS6F19 decodes the body of an S6F19 (Individual Report Request) message into a [S6F19Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F19Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F19(item secs2.Item) (S6F19Body, error) {
	var out S6F19Body

	var err error

	root := secs2.NewCursor(item)

	if out.RPTID, err = decodeItem(root, "RPTID"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F20Reply is the decoded body of the S6F20 (Individual Report Data) message.
//
// Body: L[n]{ <values>... }.
//
// It is filled by [DecodeS6F20] and mirrors the parameters of [S6F20], in order.
type S6F20Reply struct {
	VALUES []secs2.Item
}

// DecodeS6F20 decodes the body of an S6F20 (Individual Report Data) message into a [S6F20Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F20Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F20(item secs2.Item) (S6F20Reply, error) {
	var out S6F20Reply

	var err error

	root := secs2.NewCursor(item)

	if out.VALUES, err = decodeItems(root, "VALUES"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F21Body is the decoded body of the S6F21 (Annotated Individual Report Request) message.
//
// Body: <rptid>.
//
// It is filled by [DecodeS6F21] and mirrors the parameters of [S6F21], in order.
type S6F21Body struct {
	RPTID secs2.Item
}

// DecodeS6F21 decodes the body of an S6F21 (Annotated Individual Report Request) message into a [S6F21Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F21Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F21(item secs2.Item) (S6F21Body, error) {
	var out S6F21Body

	var err error

	root := secs2.NewCursor(item)

	if out.RPTID, err = decodeItem(root, "RPTID"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F22Reply is the decoded body of the S6F22 (Annotated Individual Report Data) message.
//
// Body: L[n]{ <values>... }.
//
// It is filled by [DecodeS6F22] and mirrors the parameters of [S6F22], in order.
type S6F22Reply struct {
	VALUES []secs2.Item
}

// DecodeS6F22 decodes the body of an S6F22 (Annotated Individual Report Data) message into a [S6F22Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F22Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F22(item secs2.Item) (S6F22Reply, error) {
	var out S6F22Reply

	var err error

	root := secs2.NewCursor(item)

	if out.VALUES, err = decodeItems(root, "VALUES"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F23Body is the decoded body of the S6F23 (Request Spooled Data) message.
//
// Body: U1[rsdc].
//
// It is filled by [DecodeS6F23] and mirrors the parameters of [S6F23], in order.
type S6F23Body struct {
	RSDC uint8
}

// DecodeS6F23 decodes the body of an S6F23 (Request Spooled Data) message into a [S6F23Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F23Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F23(item secs2.Item) (S6F23Body, error) {
	var out S6F23Body

	var err error

	root := secs2.NewCursor(item)

	if out.RSDC, err = decodeUintAs[uint8](root, "RSDC"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F24Reply is the decoded body of the S6F24 (Request Spooled Data Acknowledgement Send) message.
//
// Body: B[rsda].
//
// It is filled by [DecodeS6F24] and mirrors the parameters of [S6F24], in order.
type S6F24Reply struct {
	RSDA RSDA
}

// DecodeS6F24 decodes the body of an S6F24 (Request Spooled Data Acknowledgement Send) message into a [S6F24Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F24Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F24(item secs2.Item) (S6F24Reply, error) {
	var out S6F24Reply

	var err error

	root := secs2.NewCursor(item)

	if out.RSDA, err = decodeByteAs[RSDA](root, "RSDA"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F25Body is the decoded body of the S6F25 (Notification Report Send) message.
//
// Body: L[7]{ <dataid> <opid> U4[linkid] A[rcpspec] <rmchgstat> L[n]{ <attributes>... } L[2]{ U1[rmack] L[n]{ <errors>... } } }.
//
// It is filled by [DecodeS6F25] and mirrors the parameters of [S6F25], in order.
type S6F25Body struct {
	DATAID     secs2.Item
	OPID       secs2.Item
	LINKID     uint32
	RCPSPEC    string
	RMCHGSTAT  secs2.Item
	ATTRIBUTES []secs2.Item
	RMACK      RMACK
	ERRORS     []secs2.Item
}

// DecodeS6F25 decodes the body of an S6F25 (Notification Report Send) message into a [S6F25Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F25Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F25(item secs2.Item) (S6F25Body, error) {
	var out S6F25Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F25 body", 7); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.OPID, err = decodeItem(root.At(1), "OPID"); err != nil {
		return out, err
	}

	if out.LINKID, err = decodeUintAs[uint32](root.At(2), "LINKID"); err != nil {
		return out, err
	}

	if out.RCPSPEC, err = decodeASCII(root.At(3), "RCPSPEC"); err != nil {
		return out, err
	}

	if out.RMCHGSTAT, err = decodeItem(root.At(4), "RMCHGSTAT"); err != nil {
		return out, err
	}

	if out.ATTRIBUTES, err = decodeItems(root.At(5), "ATTRIBUTES"); err != nil {
		return out, err
	}

	if err = requireArity(root.At(6), "S6F25 body[6]", 2); err != nil {
		return out, err
	}

	if out.RMACK, err = decodeUintAs[RMACK](root.At(6, 0), "RMACK"); err != nil {
		return out, err
	}

	if out.ERRORS, err = decodeItems(root.At(6, 1), "ERRORS"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F26Reply is the decoded body of the S6F26 (Notification Report Send Acknowledge) message.
//
// Body: B[ackc6].
//
// It is filled by [DecodeS6F26] and mirrors the parameters of [S6F26], in order.
type S6F26Reply struct {
	ACKC6 ACKC6
}

// DecodeS6F26 decodes the body of an S6F26 (Notification Report Send Acknowledge) message into a [S6F26Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F26Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F26(item secs2.Item) (S6F26Reply, error) {
	var out S6F26Reply

	var err error

	root := secs2.NewCursor(item)

	if out.ACKC6, err = decodeByteAs[ACKC6](root, "ACKC6"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F27Body is the decoded body of the S6F27 (Trace Report Send) message.
//
// Body: L[3]{ <dataid> <trid> L[n]{ <samples>... } }.
//
// It is filled by [DecodeS6F27] and mirrors the parameters of [S6F27], in order.
type S6F27Body struct {
	DATAID  secs2.Item
	TRID    secs2.Item
	SAMPLES []secs2.Item
}

// DecodeS6F27 decodes the body of an S6F27 (Trace Report Send) message into a [S6F27Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F27Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F27(item secs2.Item) (S6F27Body, error) {
	var out S6F27Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F27 body", 3); err != nil {
		return out, err
	}

	if out.DATAID, err = decodeItem(root.At(0), "DATAID"); err != nil {
		return out, err
	}

	if out.TRID, err = decodeItem(root.At(1), "TRID"); err != nil {
		return out, err
	}

	if out.SAMPLES, err = decodeItems(root.At(2), "SAMPLES"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F28Reply is the decoded body of the S6F28 (Trace Report Send Acknowledge) message.
//
// Body: <trid>.
//
// It is filled by [DecodeS6F28] and mirrors the parameters of [S6F28], in order.
type S6F28Reply struct {
	TRID secs2.Item
}

// DecodeS6F28 decodes the body of an S6F28 (Trace Report Send Acknowledge) message into a [S6F28Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F28Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F28(item secs2.Item) (S6F28Reply, error) {
	var out S6F28Reply

	var err error

	root := secs2.NewCursor(item)

	if out.TRID, err = decodeItem(root, "TRID"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F29Body is the decoded body of the S6F29 (Trace Report Request) message.
//
// Body: <trid>.
//
// It is filled by [DecodeS6F29] and mirrors the parameters of [S6F29], in order.
type S6F29Body struct {
	TRID secs2.Item
}

// DecodeS6F29 decodes the body of an S6F29 (Trace Report Request) message into a [S6F29Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F29Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F29(item secs2.Item) (S6F29Body, error) {
	var out S6F29Body

	var err error

	root := secs2.NewCursor(item)

	if out.TRID, err = decodeItem(root, "TRID"); err != nil {
		return out, err
	}

	return out, nil
}

// S6F30Reply is the decoded body of the S6F30 (Trace Report Data) message.
//
// Body: L[3]{ <trid> L[n]{ <reports>... } <errcode> }.
//
// It is filled by [DecodeS6F30] and mirrors the parameters of [S6F30], in order.
type S6F30Reply struct {
	TRID    secs2.Item
	REPORTS []secs2.Item
	ERRCODE secs2.Item
}

// DecodeS6F30 decodes the body of an S6F30 (Trace Report Data) message into a [S6F30Reply].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S6F30Reply] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS6F30(item secs2.Item) (S6F30Reply, error) {
	var out S6F30Reply

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S6F30 body", 3); err != nil {
		return out, err
	}

	if out.TRID, err = decodeItem(root.At(0), "TRID"); err != nil {
		return out, err
	}

	if out.REPORTS, err = decodeItems(root.At(1), "REPORTS"); err != nil {
		return out, err
	}

	if out.ERRCODE, err = decodeItem(root.At(2), "ERRCODE"); err != nil {
		return out, err
	}

	return out, nil
}
