// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

func TestDecodeS6F1RoundTrip(t *testing.T) {
	msg := gem.S6F1(secs2.A("trid"), secs2.A("smpln"), "stime", secs2.A("samples"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F1(body)
	if err != nil {
		t.Fatalf("DecodeS6F1: %v", err)
	}

	if !bytes.Equal(got.TRID.ToBytes(), secs2.A("trid").ToBytes()) {
		t.Errorf("TRID: got %x, want %x", got.TRID.ToBytes(), secs2.A("trid").ToBytes())
	}

	if !bytes.Equal(got.SMPLN.ToBytes(), secs2.A("smpln").ToBytes()) {
		t.Errorf("SMPLN: got %x, want %x", got.SMPLN.ToBytes(), secs2.A("smpln").ToBytes())
	}

	if got.STIME != "stime" {
		t.Errorf("STIME: got %v, want %v", got.STIME, "stime")
	}

	if len(got.SAMPLES) != 1 {
		t.Fatalf("SAMPLES: got %d elements, want 1", len(got.SAMPLES))
	}

	if !bytes.Equal(got.SAMPLES[0].ToBytes(), secs2.A("samples").ToBytes()) {
		t.Errorf("SAMPLES: got %x, want %x", got.SAMPLES[0].ToBytes(), secs2.A("samples").ToBytes())
	}
}

func TestDecodeS6F2RoundTrip(t *testing.T) {
	msg := gem.S6F2(0x4b)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F2(body)
	if err != nil {
		t.Fatalf("DecodeS6F2: %v", err)
	}

	if got.ACKC6 != 0x4b {
		t.Errorf("ACKC6: got %v, want %v", got.ACKC6, 0x4b)
	}
}

func TestDecodeS6F3RoundTrip(t *testing.T) {
	msg := gem.S6F3(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F3(body)
	if err != nil {
		t.Fatalf("DecodeS6F3: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.CEID.ToBytes(), secs2.A("ceid").ToBytes()) {
		t.Errorf("CEID: got %x, want %x", got.CEID.ToBytes(), secs2.A("ceid").ToBytes())
	}

	if len(got.REPORTS) != 1 {
		t.Fatalf("REPORTS: got %d elements, want 1", len(got.REPORTS))
	}

	if !bytes.Equal(got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes()) {
		t.Errorf("REPORTS: got %x, want %x", got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes())
	}
}

func TestDecodeS6F4RoundTrip(t *testing.T) {
	msg := gem.S6F4(0x4b)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F4(body)
	if err != nil {
		t.Fatalf("DecodeS6F4: %v", err)
	}

	if got.ACKC6 != 0x4b {
		t.Errorf("ACKC6: got %v, want %v", got.ACKC6, 0x4b)
	}
}

func TestDecodeS6F5RoundTrip(t *testing.T) {
	msg := gem.S6F5(secs2.A("dataid"), secs2.A("datalength"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F5(body)
	if err != nil {
		t.Fatalf("DecodeS6F5: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.DATALENGTH.ToBytes(), secs2.A("datalength").ToBytes()) {
		t.Errorf("DATALENGTH: got %x, want %x", got.DATALENGTH.ToBytes(), secs2.A("datalength").ToBytes())
	}
}

func TestDecodeS6F6RoundTrip(t *testing.T) {
	msg := gem.S6F6(0x00)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F6(body)
	if err != nil {
		t.Fatalf("DecodeS6F6: %v", err)
	}

	if got.GRANT6 != 0x00 {
		t.Errorf("GRANT6: got %v, want %v", got.GRANT6, 0x00)
	}
}

func TestDecodeS6F7RoundTrip(t *testing.T) {
	msg := gem.S6F7(secs2.A("dataid"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F7(body)
	if err != nil {
		t.Fatalf("DecodeS6F7: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}
}

func TestDecodeS6F8RoundTrip(t *testing.T) {
	msg := gem.S6F8(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F8(body)
	if err != nil {
		t.Fatalf("DecodeS6F8: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.CEID.ToBytes(), secs2.A("ceid").ToBytes()) {
		t.Errorf("CEID: got %x, want %x", got.CEID.ToBytes(), secs2.A("ceid").ToBytes())
	}

	if len(got.REPORTS) != 1 {
		t.Fatalf("REPORTS: got %d elements, want 1", len(got.REPORTS))
	}

	if !bytes.Equal(got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes()) {
		t.Errorf("REPORTS: got %x, want %x", got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes())
	}
}

func TestDecodeS6F9RoundTrip(t *testing.T) {
	msg := gem.S6F9(0xf4, secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F9(body)
	if err != nil {
		t.Fatalf("DecodeS6F9: %v", err)
	}

	if got.PFCD != 0xf4 {
		t.Errorf("PFCD: got %v, want %v", got.PFCD, 0xf4)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.CEID.ToBytes(), secs2.A("ceid").ToBytes()) {
		t.Errorf("CEID: got %x, want %x", got.CEID.ToBytes(), secs2.A("ceid").ToBytes())
	}

	if len(got.REPORTS) != 1 {
		t.Fatalf("REPORTS: got %d elements, want 1", len(got.REPORTS))
	}

	if !bytes.Equal(got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes()) {
		t.Errorf("REPORTS: got %x, want %x", got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes())
	}
}

func TestDecodeS6F10RoundTrip(t *testing.T) {
	msg := gem.S6F10(0x4b)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F10(body)
	if err != nil {
		t.Fatalf("DecodeS6F10: %v", err)
	}

	if got.ACKC6 != 0x4b {
		t.Errorf("ACKC6: got %v, want %v", got.ACKC6, 0x4b)
	}
}

func TestDecodeS6F11RoundTrip(t *testing.T) {
	msg := gem.S6F11(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F11(body)
	if err != nil {
		t.Fatalf("DecodeS6F11: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.CEID.ToBytes(), secs2.A("ceid").ToBytes()) {
		t.Errorf("CEID: got %x, want %x", got.CEID.ToBytes(), secs2.A("ceid").ToBytes())
	}

	if len(got.REPORTS) != 1 {
		t.Fatalf("REPORTS: got %d elements, want 1", len(got.REPORTS))
	}

	if !bytes.Equal(got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes()) {
		t.Errorf("REPORTS: got %x, want %x", got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes())
	}
}

func TestDecodeS6F12RoundTrip(t *testing.T) {
	msg := gem.S6F12(0x4b)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F12(body)
	if err != nil {
		t.Fatalf("DecodeS6F12: %v", err)
	}

	if got.ACKC6 != 0x4b {
		t.Errorf("ACKC6: got %v, want %v", got.ACKC6, 0x4b)
	}
}

func TestDecodeS6F13RoundTrip(t *testing.T) {
	msg := gem.S6F13(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F13(body)
	if err != nil {
		t.Fatalf("DecodeS6F13: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.CEID.ToBytes(), secs2.A("ceid").ToBytes()) {
		t.Errorf("CEID: got %x, want %x", got.CEID.ToBytes(), secs2.A("ceid").ToBytes())
	}

	if len(got.REPORTS) != 1 {
		t.Fatalf("REPORTS: got %d elements, want 1", len(got.REPORTS))
	}

	if !bytes.Equal(got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes()) {
		t.Errorf("REPORTS: got %x, want %x", got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes())
	}
}

func TestDecodeS6F14RoundTrip(t *testing.T) {
	msg := gem.S6F14(0x4b)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F14(body)
	if err != nil {
		t.Fatalf("DecodeS6F14: %v", err)
	}

	if got.ACKC6 != 0x4b {
		t.Errorf("ACKC6: got %v, want %v", got.ACKC6, 0x4b)
	}
}

func TestDecodeS6F15RoundTrip(t *testing.T) {
	msg := gem.S6F15(secs2.A("ceid"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F15(body)
	if err != nil {
		t.Fatalf("DecodeS6F15: %v", err)
	}

	if !bytes.Equal(got.CEID.ToBytes(), secs2.A("ceid").ToBytes()) {
		t.Errorf("CEID: got %x, want %x", got.CEID.ToBytes(), secs2.A("ceid").ToBytes())
	}
}

func TestDecodeS6F16RoundTrip(t *testing.T) {
	msg := gem.S6F16(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F16(body)
	if err != nil {
		t.Fatalf("DecodeS6F16: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.CEID.ToBytes(), secs2.A("ceid").ToBytes()) {
		t.Errorf("CEID: got %x, want %x", got.CEID.ToBytes(), secs2.A("ceid").ToBytes())
	}

	if len(got.REPORTS) != 1 {
		t.Fatalf("REPORTS: got %d elements, want 1", len(got.REPORTS))
	}

	if !bytes.Equal(got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes()) {
		t.Errorf("REPORTS: got %x, want %x", got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes())
	}
}

func TestDecodeS6F17RoundTrip(t *testing.T) {
	msg := gem.S6F17(secs2.A("ceid"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F17(body)
	if err != nil {
		t.Fatalf("DecodeS6F17: %v", err)
	}

	if !bytes.Equal(got.CEID.ToBytes(), secs2.A("ceid").ToBytes()) {
		t.Errorf("CEID: got %x, want %x", got.CEID.ToBytes(), secs2.A("ceid").ToBytes())
	}
}

func TestDecodeS6F18RoundTrip(t *testing.T) {
	msg := gem.S6F18(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F18(body)
	if err != nil {
		t.Fatalf("DecodeS6F18: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.CEID.ToBytes(), secs2.A("ceid").ToBytes()) {
		t.Errorf("CEID: got %x, want %x", got.CEID.ToBytes(), secs2.A("ceid").ToBytes())
	}

	if len(got.REPORTS) != 1 {
		t.Fatalf("REPORTS: got %d elements, want 1", len(got.REPORTS))
	}

	if !bytes.Equal(got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes()) {
		t.Errorf("REPORTS: got %x, want %x", got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes())
	}
}

func TestDecodeS6F19RoundTrip(t *testing.T) {
	msg := gem.S6F19(secs2.A("rptid"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F19(body)
	if err != nil {
		t.Fatalf("DecodeS6F19: %v", err)
	}

	if !bytes.Equal(got.RPTID.ToBytes(), secs2.A("rptid").ToBytes()) {
		t.Errorf("RPTID: got %x, want %x", got.RPTID.ToBytes(), secs2.A("rptid").ToBytes())
	}
}

func TestDecodeS6F20RoundTrip(t *testing.T) {
	msg := gem.S6F20(secs2.A("values"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F20(body)
	if err != nil {
		t.Fatalf("DecodeS6F20: %v", err)
	}

	if len(got.VALUES) != 1 {
		t.Fatalf("VALUES: got %d elements, want 1", len(got.VALUES))
	}

	if !bytes.Equal(got.VALUES[0].ToBytes(), secs2.A("values").ToBytes()) {
		t.Errorf("VALUES: got %x, want %x", got.VALUES[0].ToBytes(), secs2.A("values").ToBytes())
	}
}

func TestDecodeS6F21RoundTrip(t *testing.T) {
	msg := gem.S6F21(secs2.A("rptid"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F21(body)
	if err != nil {
		t.Fatalf("DecodeS6F21: %v", err)
	}

	if !bytes.Equal(got.RPTID.ToBytes(), secs2.A("rptid").ToBytes()) {
		t.Errorf("RPTID: got %x, want %x", got.RPTID.ToBytes(), secs2.A("rptid").ToBytes())
	}
}

func TestDecodeS6F22RoundTrip(t *testing.T) {
	msg := gem.S6F22(secs2.A("values"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F22(body)
	if err != nil {
		t.Fatalf("DecodeS6F22: %v", err)
	}

	if len(got.VALUES) != 1 {
		t.Fatalf("VALUES: got %d elements, want 1", len(got.VALUES))
	}

	if !bytes.Equal(got.VALUES[0].ToBytes(), secs2.A("values").ToBytes()) {
		t.Errorf("VALUES: got %x, want %x", got.VALUES[0].ToBytes(), secs2.A("values").ToBytes())
	}
}

func TestDecodeS6F23RoundTrip(t *testing.T) {
	msg := gem.S6F23(30)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F23(body)
	if err != nil {
		t.Fatalf("DecodeS6F23: %v", err)
	}

	if got.RSDC != 30 {
		t.Errorf("RSDC: got %v, want %v", got.RSDC, 30)
	}
}

func TestDecodeS6F24RoundTrip(t *testing.T) {
	msg := gem.S6F24(0x6e)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F24(body)
	if err != nil {
		t.Fatalf("DecodeS6F24: %v", err)
	}

	if got.RSDA != 0x6e {
		t.Errorf("RSDA: got %v, want %v", got.RSDA, 0x6e)
	}
}

func TestDecodeS6F25RoundTrip(t *testing.T) {
	msg := gem.S6F25(secs2.A("dataid"), secs2.A("opid"), 78, "rcpspec", secs2.A("rmchgstat"), []secs2.Item{secs2.A("attributes")}, 29, secs2.A("errors"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F25(body)
	if err != nil {
		t.Fatalf("DecodeS6F25: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.OPID.ToBytes(), secs2.A("opid").ToBytes()) {
		t.Errorf("OPID: got %x, want %x", got.OPID.ToBytes(), secs2.A("opid").ToBytes())
	}

	if got.LINKID != 78 {
		t.Errorf("LINKID: got %v, want %v", got.LINKID, 78)
	}

	if got.RCPSPEC != "rcpspec" {
		t.Errorf("RCPSPEC: got %v, want %v", got.RCPSPEC, "rcpspec")
	}

	if !bytes.Equal(got.RMCHGSTAT.ToBytes(), secs2.A("rmchgstat").ToBytes()) {
		t.Errorf("RMCHGSTAT: got %x, want %x", got.RMCHGSTAT.ToBytes(), secs2.A("rmchgstat").ToBytes())
	}

	if len(got.ATTRIBUTES) != 1 {
		t.Fatalf("ATTRIBUTES: got %d elements, want 1", len(got.ATTRIBUTES))
	}

	if !bytes.Equal(got.ATTRIBUTES[0].ToBytes(), secs2.A("attributes").ToBytes()) {
		t.Errorf("ATTRIBUTES: got %x, want %x", got.ATTRIBUTES[0].ToBytes(), secs2.A("attributes").ToBytes())
	}

	if got.RMACK != 29 {
		t.Errorf("RMACK: got %v, want %v", got.RMACK, 29)
	}

	if len(got.ERRORS) != 1 {
		t.Fatalf("ERRORS: got %d elements, want 1", len(got.ERRORS))
	}

	if !bytes.Equal(got.ERRORS[0].ToBytes(), secs2.A("errors").ToBytes()) {
		t.Errorf("ERRORS: got %x, want %x", got.ERRORS[0].ToBytes(), secs2.A("errors").ToBytes())
	}
}

func TestDecodeS6F26RoundTrip(t *testing.T) {
	msg := gem.S6F26(0x4b)

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F26(body)
	if err != nil {
		t.Fatalf("DecodeS6F26: %v", err)
	}

	if got.ACKC6 != 0x4b {
		t.Errorf("ACKC6: got %v, want %v", got.ACKC6, 0x4b)
	}
}

func TestDecodeS6F27RoundTrip(t *testing.T) {
	msg := gem.S6F27(secs2.A("dataid"), secs2.A("trid"), secs2.A("samples"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F27(body)
	if err != nil {
		t.Fatalf("DecodeS6F27: %v", err)
	}

	if !bytes.Equal(got.DATAID.ToBytes(), secs2.A("dataid").ToBytes()) {
		t.Errorf("DATAID: got %x, want %x", got.DATAID.ToBytes(), secs2.A("dataid").ToBytes())
	}

	if !bytes.Equal(got.TRID.ToBytes(), secs2.A("trid").ToBytes()) {
		t.Errorf("TRID: got %x, want %x", got.TRID.ToBytes(), secs2.A("trid").ToBytes())
	}

	if len(got.SAMPLES) != 1 {
		t.Fatalf("SAMPLES: got %d elements, want 1", len(got.SAMPLES))
	}

	if !bytes.Equal(got.SAMPLES[0].ToBytes(), secs2.A("samples").ToBytes()) {
		t.Errorf("SAMPLES: got %x, want %x", got.SAMPLES[0].ToBytes(), secs2.A("samples").ToBytes())
	}
}

func TestDecodeS6F28RoundTrip(t *testing.T) {
	msg := gem.S6F28(secs2.A("trid"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F28(body)
	if err != nil {
		t.Fatalf("DecodeS6F28: %v", err)
	}

	if !bytes.Equal(got.TRID.ToBytes(), secs2.A("trid").ToBytes()) {
		t.Errorf("TRID: got %x, want %x", got.TRID.ToBytes(), secs2.A("trid").ToBytes())
	}
}

func TestDecodeS6F29RoundTrip(t *testing.T) {
	msg := gem.S6F29(secs2.A("trid"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F29(body)
	if err != nil {
		t.Fatalf("DecodeS6F29: %v", err)
	}

	if !bytes.Equal(got.TRID.ToBytes(), secs2.A("trid").ToBytes()) {
		t.Errorf("TRID: got %x, want %x", got.TRID.ToBytes(), secs2.A("trid").ToBytes())
	}
}

func TestDecodeS6F30RoundTrip(t *testing.T) {
	msg := gem.S6F30(secs2.A("trid"), []secs2.Item{secs2.A("reports")}, secs2.A("errcode"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS6F30(body)
	if err != nil {
		t.Fatalf("DecodeS6F30: %v", err)
	}

	if !bytes.Equal(got.TRID.ToBytes(), secs2.A("trid").ToBytes()) {
		t.Errorf("TRID: got %x, want %x", got.TRID.ToBytes(), secs2.A("trid").ToBytes())
	}

	if len(got.REPORTS) != 1 {
		t.Fatalf("REPORTS: got %d elements, want 1", len(got.REPORTS))
	}

	if !bytes.Equal(got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes()) {
		t.Errorf("REPORTS: got %x, want %x", got.REPORTS[0].ToBytes(), secs2.A("reports").ToBytes())
	}

	if !bytes.Equal(got.ERRCODE.ToBytes(), secs2.A("errcode").ToBytes()) {
		t.Errorf("ERRCODE: got %x, want %x", got.ERRCODE.ToBytes(), secs2.A("errcode").ToBytes())
	}
}
