// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

// assertS6Header checks that msg is an S6 message with the given function code and wait bit.
func assertS6Header(t *testing.T, msg secs2.SECS2Message, function uint8, wantW bool) {
	t.Helper()

	if msg.StreamCode() != 6 {
		t.Errorf("StreamCode: got %d, want 6", msg.StreamCode())
	}

	if msg.FunctionCode() != function {
		t.Errorf("FunctionCode: got %d, want %d", msg.FunctionCode(), function)
	}

	if msg.WaitBit() != wantW {
		t.Errorf("WaitBit: got %v, want %v", msg.WaitBit(), wantW)
	}
}

func TestS6F1(t *testing.T) {
	msg := gem.S6F1(secs2.A("trid"), secs2.A("smpln"), "stime", secs2.A("samples"))

	assertS6Header(t, msg, 1, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 4 {
		t.Fatalf("list length: got %d, want 4", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("trid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("trid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("smpln").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("smpln: got %x, want %x", got3, want3)
	}
	v4, err := list1[2].ToASCII()
	if err != nil {
		t.Fatalf("list1[2].ToASCII: %v", err)
	}
	if v4 != "stime" {
		t.Errorf("stime: got %q, want %q", v4, "stime")
	}
	list5, err := list1[3].ToList()
	if err != nil {
		t.Fatalf("list1[3].ToList: %v", err)
	}
	if len(list5) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list5))
	}
	got6 := list5[0].ToBytes()
	want6 := secs2.A("samples").ToBytes()
	if !bytes.Equal(got6, want6) {
		t.Errorf("samples: got %x, want %x", got6, want6)
	}
}

func TestS6F2(t *testing.T) {
	msg := gem.S6F2(0x4b)

	assertS6Header(t, msg, 2, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x4b {
		t.Errorf("ackc6: got %v, want %v", v1, 0x4b)
	}
}

func TestS6F3(t *testing.T) {
	msg := gem.S6F3(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	assertS6Header(t, msg, 3, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("ceid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("ceid: got %x, want %x", got3, want3)
	}
	list4, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list4) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list4))
	}
	got5 := list4[0].ToBytes()
	want5 := secs2.A("reports").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("reports: got %x, want %x", got5, want5)
	}
}

func TestS6F4(t *testing.T) {
	msg := gem.S6F4(0x4b)

	assertS6Header(t, msg, 4, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x4b {
		t.Errorf("ackc6: got %v, want %v", v1, 0x4b)
	}
}

func TestS6F5(t *testing.T) {
	msg := gem.S6F5(secs2.A("dataid"), secs2.A("datalength"))

	assertS6Header(t, msg, 5, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("datalength").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("datalength: got %x, want %x", got3, want3)
	}
}

func TestS6F6(t *testing.T) {
	msg := gem.S6F6(0x00)

	assertS6Header(t, msg, 6, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x00 {
		t.Errorf("grant6: got %v, want %v", v1, 0x00)
	}
}

func TestS6F7(t *testing.T) {
	msg := gem.S6F7(secs2.A("dataid"))

	assertS6Header(t, msg, 7, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("dataid: got %x, want %x", got1, want1)
	}
}

func TestS6F8(t *testing.T) {
	msg := gem.S6F8(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	assertS6Header(t, msg, 8, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("ceid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("ceid: got %x, want %x", got3, want3)
	}
	list4, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list4) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list4))
	}
	got5 := list4[0].ToBytes()
	want5 := secs2.A("reports").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("reports: got %x, want %x", got5, want5)
	}
}

func TestS6F9(t *testing.T) {
	msg := gem.S6F9(0xf4, secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	assertS6Header(t, msg, 9, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 4 {
		t.Fatalf("list length: got %d, want 4", len(list1))
	}
	v2, err := list1[0].ToBinary()
	if err != nil {
		t.Fatalf("list1[0].ToBinary: %v", err)
	}
	if len(v2) != 1 || v2[0] != 0xf4 {
		t.Errorf("pfcd: got %v, want %v", v2, 0xf4)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("dataid: got %x, want %x", got3, want3)
	}
	got4 := list1[2].ToBytes()
	want4 := secs2.A("ceid").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("ceid: got %x, want %x", got4, want4)
	}
	list5, err := list1[3].ToList()
	if err != nil {
		t.Fatalf("list1[3].ToList: %v", err)
	}
	if len(list5) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list5))
	}
	got6 := list5[0].ToBytes()
	want6 := secs2.A("reports").ToBytes()
	if !bytes.Equal(got6, want6) {
		t.Errorf("reports: got %x, want %x", got6, want6)
	}
}

func TestS6F10(t *testing.T) {
	msg := gem.S6F10(0x4b)

	assertS6Header(t, msg, 10, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x4b {
		t.Errorf("ackc6: got %v, want %v", v1, 0x4b)
	}
}

func TestS6F11(t *testing.T) {
	msg := gem.S6F11(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	assertS6Header(t, msg, 11, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("ceid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("ceid: got %x, want %x", got3, want3)
	}
	list4, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list4) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list4))
	}
	got5 := list4[0].ToBytes()
	want5 := secs2.A("reports").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("reports: got %x, want %x", got5, want5)
	}
}

func TestS6F12(t *testing.T) {
	msg := gem.S6F12(0x4b)

	assertS6Header(t, msg, 12, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x4b {
		t.Errorf("ackc6: got %v, want %v", v1, 0x4b)
	}
}

func TestS6F13(t *testing.T) {
	msg := gem.S6F13(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	assertS6Header(t, msg, 13, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("ceid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("ceid: got %x, want %x", got3, want3)
	}
	list4, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list4) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list4))
	}
	got5 := list4[0].ToBytes()
	want5 := secs2.A("reports").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("reports: got %x, want %x", got5, want5)
	}
}

func TestS6F14(t *testing.T) {
	msg := gem.S6F14(0x4b)

	assertS6Header(t, msg, 14, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x4b {
		t.Errorf("ackc6: got %v, want %v", v1, 0x4b)
	}
}

func TestS6F15(t *testing.T) {
	msg := gem.S6F15(secs2.A("ceid"))

	assertS6Header(t, msg, 15, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("ceid").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("ceid: got %x, want %x", got1, want1)
	}
}

func TestS6F16(t *testing.T) {
	msg := gem.S6F16(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	assertS6Header(t, msg, 16, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("ceid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("ceid: got %x, want %x", got3, want3)
	}
	list4, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list4) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list4))
	}
	got5 := list4[0].ToBytes()
	want5 := secs2.A("reports").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("reports: got %x, want %x", got5, want5)
	}
}

func TestS6F17(t *testing.T) {
	msg := gem.S6F17(secs2.A("ceid"))

	assertS6Header(t, msg, 17, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("ceid").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("ceid: got %x, want %x", got1, want1)
	}
}

func TestS6F18(t *testing.T) {
	msg := gem.S6F18(secs2.A("dataid"), secs2.A("ceid"), secs2.A("reports"))

	assertS6Header(t, msg, 18, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("ceid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("ceid: got %x, want %x", got3, want3)
	}
	list4, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list4) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list4))
	}
	got5 := list4[0].ToBytes()
	want5 := secs2.A("reports").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("reports: got %x, want %x", got5, want5)
	}
}

func TestS6F19(t *testing.T) {
	msg := gem.S6F19(secs2.A("rptid"))

	assertS6Header(t, msg, 19, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("rptid").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("rptid: got %x, want %x", got1, want1)
	}
}

func TestS6F20(t *testing.T) {
	msg := gem.S6F20(secs2.A("values"))

	assertS6Header(t, msg, 20, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("values").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("values: got %x, want %x", got2, want2)
	}
}

func TestS6F21(t *testing.T) {
	msg := gem.S6F21(secs2.A("rptid"))

	assertS6Header(t, msg, 21, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("rptid").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("rptid: got %x, want %x", got1, want1)
	}
}

func TestS6F22(t *testing.T) {
	msg := gem.S6F22(secs2.A("values"))

	assertS6Header(t, msg, 22, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("values").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("values: got %x, want %x", got2, want2)
	}
}

func TestS6F23(t *testing.T) {
	msg := gem.S6F23(30)

	assertS6Header(t, msg, 23, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToUint()
	if err != nil {
		t.Fatalf("decoded.ToUint: %v", err)
	}
	if len(v1) != 1 || v1[0] != 30 {
		t.Errorf("rsdc: got %v, want %v", v1, 30)
	}
}

func TestS6F24(t *testing.T) {
	msg := gem.S6F24(0x6e)

	assertS6Header(t, msg, 24, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x6e {
		t.Errorf("rsda: got %v, want %v", v1, 0x6e)
	}
}

func TestS6F25(t *testing.T) {
	msg := gem.S6F25(secs2.A("dataid"), secs2.A("opid"), 78, "rcpspec", secs2.A("rmchgstat"), []secs2.Item{secs2.A("attributes")}, 29, secs2.A("errors"))

	assertS6Header(t, msg, 25, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 7 {
		t.Fatalf("list length: got %d, want 7", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("opid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("opid: got %x, want %x", got3, want3)
	}
	v4, err := list1[2].ToUint()
	if err != nil {
		t.Fatalf("list1[2].ToUint: %v", err)
	}
	if len(v4) != 1 || v4[0] != 78 {
		t.Errorf("linkid: got %v, want %v", v4, 78)
	}
	v5, err := list1[3].ToASCII()
	if err != nil {
		t.Fatalf("list1[3].ToASCII: %v", err)
	}
	if v5 != "rcpspec" {
		t.Errorf("rcpspec: got %q, want %q", v5, "rcpspec")
	}
	got6 := list1[4].ToBytes()
	want6 := secs2.A("rmchgstat").ToBytes()
	if !bytes.Equal(got6, want6) {
		t.Errorf("rmchgstat: got %x, want %x", got6, want6)
	}
	list7, err := list1[5].ToList()
	if err != nil {
		t.Fatalf("list1[5].ToList: %v", err)
	}
	if len(list7) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list7))
	}
	got8 := list7[0].ToBytes()
	want8 := secs2.A("attributes").ToBytes()
	if !bytes.Equal(got8, want8) {
		t.Errorf("attributes: got %x, want %x", got8, want8)
	}
	list9, err := list1[6].ToList()
	if err != nil {
		t.Fatalf("list1[6].ToList: %v", err)
	}
	if len(list9) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list9))
	}
	v10, err := list9[0].ToUint()
	if err != nil {
		t.Fatalf("list9[0].ToUint: %v", err)
	}
	if len(v10) != 1 || v10[0] != 29 {
		t.Errorf("rmack: got %v, want %v", v10, 29)
	}
	list11, err := list9[1].ToList()
	if err != nil {
		t.Fatalf("list9[1].ToList: %v", err)
	}
	if len(list11) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list11))
	}
	got12 := list11[0].ToBytes()
	want12 := secs2.A("errors").ToBytes()
	if !bytes.Equal(got12, want12) {
		t.Errorf("errors: got %x, want %x", got12, want12)
	}
}

func TestS6F26(t *testing.T) {
	msg := gem.S6F26(0x4b)

	assertS6Header(t, msg, 26, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if len(v1) != 1 || v1[0] != 0x4b {
		t.Errorf("ackc6: got %v, want %v", v1, 0x4b)
	}
}

func TestS6F27(t *testing.T) {
	msg := gem.S6F27(secs2.A("dataid"), secs2.A("trid"), secs2.A("samples"))

	assertS6Header(t, msg, 27, true)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("dataid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("dataid: got %x, want %x", got2, want2)
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("trid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("trid: got %x, want %x", got3, want3)
	}
	list4, err := list1[2].ToList()
	if err != nil {
		t.Fatalf("list1[2].ToList: %v", err)
	}
	if len(list4) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list4))
	}
	got5 := list4[0].ToBytes()
	want5 := secs2.A("samples").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("samples: got %x, want %x", got5, want5)
	}
}

func TestS6F28(t *testing.T) {
	msg := gem.S6F28(secs2.A("trid"))

	assertS6Header(t, msg, 28, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("trid").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("trid: got %x, want %x", got1, want1)
	}
}

func TestS6F29(t *testing.T) {
	msg := gem.S6F29(secs2.A("trid"))

	assertS6Header(t, msg, 29, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	got1 := decoded.ToBytes()
	want1 := secs2.A("trid").ToBytes()
	if !bytes.Equal(got1, want1) {
		t.Errorf("trid: got %x, want %x", got1, want1)
	}
}

func TestS6F30(t *testing.T) {
	msg := gem.S6F30(secs2.A("trid"), []secs2.Item{secs2.A("reports")}, secs2.A("errcode"))

	assertS6Header(t, msg, 30, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 3 {
		t.Fatalf("list length: got %d, want 3", len(list1))
	}
	got2 := list1[0].ToBytes()
	want2 := secs2.A("trid").ToBytes()
	if !bytes.Equal(got2, want2) {
		t.Errorf("trid: got %x, want %x", got2, want2)
	}
	list3, err := list1[1].ToList()
	if err != nil {
		t.Fatalf("list1[1].ToList: %v", err)
	}
	if len(list3) != 1 {
		t.Fatalf("list length: got %d, want 1", len(list3))
	}
	got4 := list3[0].ToBytes()
	want4 := secs2.A("reports").ToBytes()
	if !bytes.Equal(got4, want4) {
		t.Errorf("reports: got %x, want %x", got4, want4)
	}
	got5 := list1[2].ToBytes()
	want5 := secs2.A("errcode").ToBytes()
	if !bytes.Equal(got5, want5) {
		t.Errorf("errcode: got %x, want %x", got5, want5)
	}
}
