// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S9F1 creates the S9F1 (Unrecognized Device ID) message, direction: equipment-to-host.
//
// The device ID in the message block header did not correspond to any known device ID in the node detecting the error.
//
// Body: B[mhead].
//
// Exception: None.
func S9F1(mhead [10]byte) secs2.SECS2Message {
	return secs2.NewMessage(9, 1, false, secs2.B(mhead[:]))
}

// S9F3 creates the S9F3 (Unrecognized Stream Type) message, direction: equipment-to-host.
//
// The equipment does not recognize the stream type in the message block header.
//
// Body: B[mhead].
//
// Exception: None.
func S9F3(mhead [10]byte) secs2.SECS2Message {
	return secs2.NewMessage(9, 3, false, secs2.B(mhead[:]))
}

// S9F5 creates the S9F5 (Unrecognized Function Type) message, direction: equipment-to-host.
//
// The function in the message ID is not recognized by the receiver.
//
// Body: B[mhead].
//
// Exception: None.
func S9F5(mhead [10]byte) secs2.SECS2Message {
	return secs2.NewMessage(9, 5, false, secs2.B(mhead[:]))
}

// S9F7 creates the S9F7 (Illegal Data) message, direction: equipment-to-host.
//
// The stream and function were recognized, but the message format was incorrect. May indicate the message did not comply with its Message Definition or used a data format or type the receiver does not support.
//
// Body: B[mhead].
//
// Exception: None.
func S9F7(mhead [10]byte) secs2.SECS2Message {
	return secs2.NewMessage(9, 7, false, secs2.B(mhead[:]))
}

// S9F9 creates the S9F9 (Transaction Timer Timeout) message, direction: equipment-to-host.
//
// A transaction (receive) timer has timed out and the corresponding transaction has been aborted. The host must respond appropriately to keep the system operational.
//
// Body: B[shead].
//
// Exception: None.
func S9F9(shead [10]byte) secs2.SECS2Message {
	return secs2.NewMessage(9, 9, false, secs2.B(shead[:]))
}

// S9F11 creates the S9F11 (Data Too Long) message, direction: equipment-to-host.
//
// The equipment has been sent more data than it can handle.
//
// Body: B[mhead].
//
// Exception: None.
func S9F11(mhead [10]byte) secs2.SECS2Message {
	return secs2.NewMessage(9, 11, false, secs2.B(mhead[:]))
}

// S9F13 creates the S9F13 (Conversation Timeout) message, direction: equipment-to-host.
//
// Data were expected but none were received within a reasonable length of time. Resources have been cleared.
//
// Body: L[2]{ A[mexp] <edid> }.
//
// Exception: None.
func S9F13(mexp string, edid secs2.Item) secs2.SECS2Message {
	return secs2.NewMessage(9, 13, false, secs2.L(secs2.A(mexp), edid))
}
