// Code generated by gemgen; DO NOT EDIT.

package gem

import "github.com/arloliu/go-secs/v2/secs2"

// S9F1Body is the decoded body of the S9F1 (Unrecognized Device ID) message.
//
// Body: B[mhead].
//
// It is filled by [DecodeS9F1] and mirrors the parameters of [S9F1], in order.
type S9F1Body struct {
	MHEAD [10]byte
}

// DecodeS9F1 decodes the body of an S9F1 (Unrecognized Device ID) message into a [S9F1Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S9F1Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS9F1(item secs2.Item) (S9F1Body, error) {
	var out S9F1Body

	var err error

	root := secs2.NewCursor(item)

	var b1 []byte
	if b1, err = decodeBinary(root, "MHEAD"); err != nil {
		return out, err
	}

	if len(b1) != 10 {
		return out, errSize("MHEAD", len(b1), 10)
	}

	out.MHEAD = [10]byte(b1)

	return out, nil
}

// S9F3Body is the decoded body of the S9F3 (Unrecognized Stream Type) message.
//
// Body: B[mhead].
//
// It is filled by [DecodeS9F3] and mirrors the parameters of [S9F3], in order.
type S9F3Body struct {
	MHEAD [10]byte
}

// DecodeS9F3 decodes the body of an S9F3 (Unrecognized Stream Type) message into a [S9F3Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S9F3Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS9F3(item secs2.Item) (S9F3Body, error) {
	var out S9F3Body

	var err error

	root := secs2.NewCursor(item)

	var b1 []byte
	if b1, err = decodeBinary(root, "MHEAD"); err != nil {
		return out, err
	}

	if len(b1) != 10 {
		return out, errSize("MHEAD", len(b1), 10)
	}

	out.MHEAD = [10]byte(b1)

	return out, nil
}

// S9F5Body is the decoded body of the S9F5 (Unrecognized Function Type) message.
//
// Body: B[mhead].
//
// It is filled by [DecodeS9F5] and mirrors the parameters of [S9F5], in order.
type S9F5Body struct {
	MHEAD [10]byte
}

// DecodeS9F5 decodes the body of an S9F5 (Unrecognized Function Type) message into a [S9F5Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S9F5Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS9F5(item secs2.Item) (S9F5Body, error) {
	var out S9F5Body

	var err error

	root := secs2.NewCursor(item)

	var b1 []byte
	if b1, err = decodeBinary(root, "MHEAD"); err != nil {
		return out, err
	}

	if len(b1) != 10 {
		return out, errSize("MHEAD", len(b1), 10)
	}

	out.MHEAD = [10]byte(b1)

	return out, nil
}

// S9F7Body is the decoded body of the S9F7 (Illegal Data) message.
//
// Body: B[mhead].
//
// It is filled by [DecodeS9F7] and mirrors the parameters of [S9F7], in order.
type S9F7Body struct {
	MHEAD [10]byte
}

// DecodeS9F7 decodes the body of an S9F7 (Illegal Data) message into a [S9F7Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S9F7Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS9F7(item secs2.Item) (S9F7Body, error) {
	var out S9F7Body

	var err error

	root := secs2.NewCursor(item)

	var b1 []byte
	if b1, err = decodeBinary(root, "MHEAD"); err != nil {
		return out, err
	}

	if len(b1) != 10 {
		return out, errSize("MHEAD", len(b1), 10)
	}

	out.MHEAD = [10]byte(b1)

	return out, nil
}

// S9F9Body is the decoded body of the S9F9 (Transaction Timer Timeout) message.
//
// Body: B[shead].
//
// It is filled by [DecodeS9F9] and mirrors the parameters of [S9F9], in order.
type S9F9Body struct {
	SHEAD [10]byte
}

// DecodeS9F9 decodes the body of an S9F9 (Transaction Timer Timeout) message into a [S9F9Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S9F9Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS9F9(item secs2.Item) (S9F9Body, error) {
	var out S9F9Body

	var err error

	root := secs2.NewCursor(item)

	var b1 []byte
	if b1, err = decodeBinary(root, "SHEAD"); err != nil {
		return out, err
	}

	if len(b1) != 10 {
		return out, errSize("SHEAD", len(b1), 10)
	}

	out.SHEAD = [10]byte(b1)

	return out, nil
}

// S9F11Body is the decoded body of the S9F11 (Data Too Long) message.
//
// Body: B[mhead].
//
// It is filled by [DecodeS9F11] and mirrors the parameters of [S9F11], in order.
type S9F11Body struct {
	MHEAD [10]byte
}

// DecodeS9F11 decodes the body of an S9F11 (Data Too Long) message into a [S9F11Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S9F11Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS9F11(item secs2.Item) (S9F11Body, error) {
	var out S9F11Body

	var err error

	root := secs2.NewCursor(item)

	var b1 []byte
	if b1, err = decodeBinary(root, "MHEAD"); err != nil {
		return out, err
	}

	if len(b1) != 10 {
		return out, errSize("MHEAD", len(b1), 10)
	}

	out.MHEAD = [10]byte(b1)

	return out, nil
}

// S9F13Body is the decoded body of the S9F13 (Conversation Timeout) message.
//
// Body: L[2]{ A[mexp] <edid> }.
//
// It is filled by [DecodeS9F13] and mirrors the parameters of [S9F13], in order.
type S9F13Body struct {
	MEXP string
	EDID secs2.Item
}

// DecodeS9F13 decodes the body of an S9F13 (Conversation Timeout) message into a [S9F13Body].
//
// item is the message body, as returned by SECS2Message.Item.
// The body must match the shape [S9F13Body] documents:
// a wrong list length, a wrong SECS-II type, or a missing position returns an error naming the E5 field that failed.
func DecodeS9F13(item secs2.Item) (S9F13Body, error) {
	var out S9F13Body

	var err error

	root := secs2.NewCursor(item)

	if err = requireArity(root, "S9F13 body", 2); err != nil {
		return out, err
	}

	if out.MEXP, err = decodeASCII(root.At(0), "MEXP"); err != nil {
		return out, err
	}

	if out.EDID, err = decodeItem(root.At(1), "EDID"); err != nil {
		return out, err
	}

	return out, nil
}
