// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

func TestDecodeS9F1RoundTrip(t *testing.T) {
	msg := gem.S9F1([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS9F1(body)
	if err != nil {
		t.Fatalf("DecodeS9F1: %v", err)
	}

	if got.MHEAD != [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc} {
		t.Errorf("MHEAD: got %v, want %v", got.MHEAD, [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestDecodeS9F3RoundTrip(t *testing.T) {
	msg := gem.S9F3([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS9F3(body)
	if err != nil {
		t.Fatalf("DecodeS9F3: %v", err)
	}

	if got.MHEAD != [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc} {
		t.Errorf("MHEAD: got %v, want %v", got.MHEAD, [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestDecodeS9F5RoundTrip(t *testing.T) {
	msg := gem.S9F5([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS9F5(body)
	if err != nil {
		t.Fatalf("DecodeS9F5: %v", err)
	}

	if got.MHEAD != [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc} {
		t.Errorf("MHEAD: got %v, want %v", got.MHEAD, [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestDecodeS9F7RoundTrip(t *testing.T) {
	msg := gem.S9F7([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS9F7(body)
	if err != nil {
		t.Fatalf("DecodeS9F7: %v", err)
	}

	if got.MHEAD != [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc} {
		t.Errorf("MHEAD: got %v, want %v", got.MHEAD, [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestDecodeS9F9RoundTrip(t *testing.T) {
	msg := gem.S9F9([10]byte{0x87, 0x3a, 0xa4, 0xd6, 0xc5, 0x50, 0xe2, 0x0d, 0x44, 0x8e})

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS9F9(body)
	if err != nil {
		t.Fatalf("DecodeS9F9: %v", err)
	}

	if got.SHEAD != [10]byte{0x87, 0x3a, 0xa4, 0xd6, 0xc5, 0x50, 0xe2, 0x0d, 0x44, 0x8e} {
		t.Errorf("SHEAD: got %v, want %v", got.SHEAD, [10]byte{0x87, 0x3a, 0xa4, 0xd6, 0xc5, 0x50, 0xe2, 0x0d, 0x44, 0x8e})
	}
}

func TestDecodeS9F11RoundTrip(t *testing.T) {
	msg := gem.S9F11([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS9F11(body)
	if err != nil {
		t.Fatalf("DecodeS9F11: %v", err)
	}

	if got.MHEAD != [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc} {
		t.Errorf("MHEAD: got %v, want %v", got.MHEAD, [10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestDecodeS9F13RoundTrip(t *testing.T) {
	msg := gem.S9F13("mexp", secs2.A("edid"))

	body, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}

	got, err := gem.DecodeS9F13(body)
	if err != nil {
		t.Fatalf("DecodeS9F13: %v", err)
	}

	if got.MEXP != "mexp" {
		t.Errorf("MEXP: got %v, want %v", got.MEXP, "mexp")
	}

	if !bytes.Equal(got.EDID.ToBytes(), secs2.A("edid").ToBytes()) {
		t.Errorf("EDID: got %x, want %x", got.EDID.ToBytes(), secs2.A("edid").ToBytes())
	}
}
