// Code generated by gemgen; DO NOT EDIT.

package gem_test

import (
	"bytes"
	"testing"

	"github.com/arloliu/go-secs/v2/gem"
	"github.com/arloliu/go-secs/v2/secs2"
)

// assertS9Header checks that msg is an S9 message with the given function code and wait bit.
func assertS9Header(t *testing.T, msg secs2.SECS2Message, function uint8, wantW bool) {
	t.Helper()

	if msg.StreamCode() != 9 {
		t.Errorf("StreamCode: got %d, want 9", msg.StreamCode())
	}

	if msg.FunctionCode() != function {
		t.Errorf("FunctionCode: got %d, want %d", msg.FunctionCode(), function)
	}

	if msg.WaitBit() != wantW {
		t.Errorf("WaitBit: got %v, want %v", msg.WaitBit(), wantW)
	}
}

func TestS9F1(t *testing.T) {
	msg := gem.S9F1([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	assertS9Header(t, msg, 1, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if !bytes.Equal(v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc}) {
		t.Errorf("mhead: got %x, want %x", v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestS9F3(t *testing.T) {
	msg := gem.S9F3([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	assertS9Header(t, msg, 3, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if !bytes.Equal(v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc}) {
		t.Errorf("mhead: got %x, want %x", v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestS9F5(t *testing.T) {
	msg := gem.S9F5([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	assertS9Header(t, msg, 5, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if !bytes.Equal(v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc}) {
		t.Errorf("mhead: got %x, want %x", v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestS9F7(t *testing.T) {
	msg := gem.S9F7([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	assertS9Header(t, msg, 7, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if !bytes.Equal(v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc}) {
		t.Errorf("mhead: got %x, want %x", v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestS9F9(t *testing.T) {
	msg := gem.S9F9([10]byte{0x87, 0x3a, 0xa4, 0xd6, 0xc5, 0x50, 0xe2, 0x0d, 0x44, 0x8e})

	assertS9Header(t, msg, 9, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if !bytes.Equal(v1, []byte{0x87, 0x3a, 0xa4, 0xd6, 0xc5, 0x50, 0xe2, 0x0d, 0x44, 0x8e}) {
		t.Errorf("shead: got %x, want %x", v1, []byte{0x87, 0x3a, 0xa4, 0xd6, 0xc5, 0x50, 0xe2, 0x0d, 0x44, 0x8e})
	}
}

func TestS9F11(t *testing.T) {
	msg := gem.S9F11([10]byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})

	assertS9Header(t, msg, 11, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	v1, err := decoded.ToBinary()
	if err != nil {
		t.Fatalf("decoded.ToBinary: %v", err)
	}
	if !bytes.Equal(v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc}) {
		t.Errorf("mhead: got %x, want %x", v1, []byte{0xe7, 0x49, 0x80, 0x12, 0x36, 0x87, 0xde, 0xa8, 0x1b, 0xfc})
	}
}

func TestS9F13(t *testing.T) {
	msg := gem.S9F13("mexp", secs2.A("edid"))

	assertS9Header(t, msg, 13, false)

	decoded, err := secs2.Decode(msg.Item().ToBytes())
	if err != nil {
		t.Fatalf("secs2.Decode: %v", err)
	}
	list1, err := decoded.ToList()
	if err != nil {
		t.Fatalf("decoded.ToList: %v", err)
	}
	if len(list1) != 2 {
		t.Fatalf("list length: got %d, want 2", len(list1))
	}
	v2, err := list1[0].ToASCII()
	if err != nil {
		t.Fatalf("list1[0].ToASCII: %v", err)
	}
	if v2 != "mexp" {
		t.Errorf("mexp: got %q, want %q", v2, "mexp")
	}
	got3 := list1[1].ToBytes()
	want3 := secs2.A("edid").ToBytes()
	if !bytes.Equal(got3, want3) {
		t.Errorf("edid: got %x, want %x", got3, want3)
	}
}
