// Code generated by gemgen; DO NOT EDIT.

package gem

import (
	"fmt"
	"math"

	"github.com/arloliu/go-secs/v2/secs2"
)

// wrapField labels a [secs2.Cursor] error with the E5 field the generated decoder was reading.
//
// The cursor's own message already carries the position and the got/want type family; the label
// says which named part of the message body that position is.
func wrapField(field string, err error) error {
	return fmt.Errorf("gem: %s: %w", field, err)
}

// errNotList reports that a body position the DSL declares as a list holds some other item type.
func errNotList(field string, got string) error {
	return fmt.Errorf("gem: %s: got %s, want %s", field, got, secs2.ListType)
}

// errArity reports that a list holds a different number of children than the E5 body shape declares.
func errArity(field string, got int, want int) error {
	return fmt.Errorf("gem: %s: list length %d, want %d", field, got, want)
}

// errArityRange reports that an optional list group holds neither its short nor its full form.
func errArityRange(field string, got int, short int, full int) error {
	return fmt.Errorf("gem: %s: list length %d, want %d or %d", field, got, short, full)
}

// errSize reports that an item holds a different number of values than its E5 data type declares.
func errSize(field string, got int, want int) error {
	return fmt.Errorf("gem: %s: size %d, want %d", field, got, want)
}

// errOverflow reports that a decoded numeric value does not fit the E5 data item's declared width.
func errOverflow(field string, got any, want string) error {
	return fmt.Errorf("gem: %s: value %v overflows %s", field, got, want)
}

// listAt returns the list item at c, or an error naming field when the position is unreachable,
// carries a deferred construction error, or holds a non-list item.
func listAt(c secs2.Cursor, field string) (secs2.Item, error) {
	item, err := c.Item()
	if err != nil {
		return nil, wrapField(field, err)
	}

	if err := item.Error(); err != nil {
		return nil, wrapField(field, err)
	}

	if !item.IsList() {
		return nil, errNotList(field, item.Type())
	}

	return item, nil
}

// requireArity checks that the item at c is a list holding exactly want children.
func requireArity(c secs2.Cursor, field string, want int) error {
	item, err := listAt(c, field)
	if err != nil {
		return err
	}

	if got := item.Size(); got != want {
		return errArity(field, got, want)
	}

	return nil
}

// optionalArity returns the child count of the list at c, which must be either short or full.
//
// It implements the DSL's minItems / maxItems bound: SEMI E5 declares a few trailing groups
// (an error code and its text, a set of limit attributes) that a body may omit entirely.
// A count between the two forms is rejected, since a partially filled group names no field.
func optionalArity(c secs2.Cursor, field string, short int, full int) (int, error) {
	item, err := listAt(c, field)
	if err != nil {
		return 0, err
	}

	got := item.Size()
	if got != short && got != full {
		return 0, errArityRange(field, got, short, full)
	}

	return got, nil
}

// decodeItems returns the children of the list at c, one per element of a repeated group.
func decodeItems(c secs2.Cursor, field string) ([]secs2.Item, error) {
	item, err := listAt(c, field)
	if err != nil {
		return nil, err
	}

	values, err := item.ToList()
	if err != nil {
		return nil, wrapField(field, err)
	}

	return values, nil
}

// decodeItem returns the item at c unchanged, for a field whose SECS-II type is equipment-defined.
func decodeItem(c secs2.Cursor, field string) (secs2.Item, error) {
	item, err := c.Item()
	if err != nil {
		return nil, wrapField(field, err)
	}

	if err := item.Error(); err != nil {
		return nil, wrapField(field, err)
	}

	return item, nil
}

// decodeASCII returns the ASCII item at c as a string.
func decodeASCII(c secs2.Cursor, field string) (string, error) {
	value, err := c.ASCII()
	if err != nil {
		return "", wrapField(field, err)
	}

	return value, nil
}

// decodeBool returns the single-value boolean item at c.
func decodeBool(c secs2.Cursor, field string) (bool, error) {
	value, err := c.Bool()
	if err != nil {
		return false, wrapField(field, err)
	}

	return value, nil
}

// decodeBinary returns a copy of the bytes of the binary item at c, whatever its length.
func decodeBinary(c secs2.Cursor, field string) ([]byte, error) {
	value, err := c.Binary()
	if err != nil {
		return nil, wrapField(field, err)
	}

	return value, nil
}

// decodeByteAs returns the single-byte binary item at c as T, the E5 item's own defined type.
func decodeByteAs[T ~byte](c secs2.Cursor, field string) (T, error) {
	value, err := c.Binary()
	if err != nil {
		return 0, wrapField(field, err)
	}

	if len(value) != 1 {
		return 0, errSize(field, len(value), 1)
	}

	return T(value[0]), nil
}

// decodeUintAs returns the single-value unsigned item at c as T.
//
// Any unsigned width (U1, U2, U4, U8) decodes; the value must fit T, the width the E5 data item
// declares, so a wider item carrying an out-of-range value is rejected rather than truncated.
func decodeUintAs[T ~uint8 | ~uint16 | ~uint32 | ~uint64](c secs2.Cursor, field string) (T, error) {
	value, err := c.Uint()
	if err != nil {
		return 0, wrapField(field, err)
	}

	out := T(value)
	if uint64(out) != value {
		return 0, errOverflow(field, value, fmt.Sprintf("%T", out))
	}

	return out, nil
}

// decodeIntAs returns the single-value signed item at c as T.
//
// Any signed width (I1, I2, I4, I8) decodes; the value must fit T, the width the E5 data item
// declares, so a wider item carrying an out-of-range value is rejected rather than truncated.
func decodeIntAs[T ~int8 | ~int16 | ~int32 | ~int64](c secs2.Cursor, field string) (T, error) {
	value, err := c.Int()
	if err != nil {
		return 0, wrapField(field, err)
	}

	out := T(value)
	if int64(out) != value {
		return 0, errOverflow(field, value, fmt.Sprintf("%T", out))
	}

	return out, nil
}

// decodeFloatAs returns the single-value floating-point item at c as T.
//
// Either width (F4, F8) decodes; the value must survive the conversion to T, the width the E5
// data item declares, so an F8 value with no exact F4 representation is rejected rather than
// silently rounded. NaN is accepted, since it never compares equal to itself.
func decodeFloatAs[T ~float32 | ~float64](c secs2.Cursor, field string) (T, error) {
	value, err := c.Float()
	if err != nil {
		return 0, wrapField(field, err)
	}

	out := T(value)
	if float64(out) != value && !math.IsNaN(value) {
		return 0, errOverflow(field, value, fmt.Sprintf("%T", out))
	}

	return out, nil
}
